package org.apache.hadoop.yarn.server.resourcemanager;

import edu.illinois.instance.Instance;
import java.io.IOException;
import java.lang.reflect.Method;
import java.lang.reflect.Constructor;
import java.util.Arrays;
import java.util.stream.Collectors;

/**
 * Instance helper class for creating ResourceManager instances
 * using version-specific classloaders.
 * Generated by UpgradableClusterGenerator.
 */
public class ResourceManagerInstance extends Instance {

    public ResourceManagerInstance() {
        super("3.3.5");
    }

    /**
     * Creates a ResourceManager instance for use in InJVM cluster.
     * This method uses reflection to instantiate the node with the version-specific classloader.
     */
    public ResourceManagerJVMInterface createResourceManagerForInJVMCluster(Object... args) {
        // Set the thread context classloader to the version classloader
        versionClassLoader.setCurrentThreadClassLoader();
        
        try {
            // Load the ResourceManager class from the version classloader
            Class<?> nodeClass = versionClassLoader.loadClass("org.apache.hadoop.yarn.server.resourcemanager.ResourceManager");
            
            // Find appropriate constructor based on argument types
            Constructor<?> constructor = findMatchingConstructor(nodeClass, args);
            
            // Create instance
            Object instance = constructor.newInstance(args);

            System.out.println("rm class         = " + instance.getClass() + " | loader = " + instance.getClass().getClassLoader());
            System.out.println("iface (app)      = " + ResourceManagerJVMInterface.class + " | loader = " + ResourceManagerJVMInterface.class.getClassLoader());
            System.out.println("rm implements?   = " + Arrays.stream(instance.getClass().getInterfaces())
                    .map(c -> c.getName() + " @loader=" + c.getClassLoader()).collect(Collectors.joining(", ")));

            // Return as interface type
            return (ResourceManagerJVMInterface) instance;
        } catch (Exception e) {
            throw new RuntimeException("Failed to create ResourceManager instance: " + e.getMessage(), e);
        } finally {
            // Reset the thread context classloader
            versionClassLoader.resetCurrentThreadClassLoader();
        }
    }

    private Constructor<?> findMatchingConstructor(Class<?> clazz, Object... args) {
        Constructor<?>[] constructors = clazz.getConstructors();
        
        for (Constructor<?> constructor : constructors) {
            if (constructor.getParameterCount() == args.length) {
                // Simple matching - can be enhanced for better type matching
                return constructor;
            }
        }
        
        throw new RuntimeException("No matching constructor found for " + clazz.getName() + 
                                 " with " + args.length + " arguments");
    }
}
