package org.apache.hadoop.yarn.server.resourcemanager;

import edu.illinois.core.instance.UpgradableInstance;
import java.lang.reflect.Constructor;

/**
 * Instance helper class for creating ResourceManager instances
 * using version-specific classloaders.
 * Generated by UpgradableClusterGenerator.
 */
public class ResourceManagerInstance extends UpgradableInstance {

    public ResourceManagerInstance(UpgradableInstance delegate) {
        super(delegate.getNodeName(), delegate.getVersion(),
                delegate.getLoader(), delegate.getPlan(),
                delegate.isMarkedForUpgrade());
        // Set the DefaultMetricsSystem.setMiniClusterMode(true) through reflection
        try {
            Class<?> metricsSystemClass = getLoader().loadClass("org.apache.hadoop.metrics2.lib.DefaultMetricsSystem");
            java.lang.reflect.Method m = metricsSystemClass.getDeclaredMethod("setMiniClusterMode", boolean.class);
            m.setAccessible(true);
            m.invoke(null, true); // static
        } catch (Exception e) {
            throw new RuntimeException("Failed to set miniClusterMode: " + e.getMessage(), e);
        }
    }
    /**
     * Creates a ResourceManager instance for use in InJVM cluster.
     * This method uses reflection to instantiate the node with the version-specific classloader.
     */
    public ResourceManagerJVMInterface createResourceManagerForInJVMCluster(Object... args) {
        // Set the thread context classloader to the version classloader
        enter();
        
        try {
            // Load the ResourceManager class from the version classloader
            Class<?> nodeClass = getLoader().loadClass("org.apache.hadoop.yarn.server.resourcemanager.ResourceManager");
            
            // Find appropriate constructor based on argument types
            Constructor<?> constructor = findMatchingConstructor(nodeClass, args);
            
            // Create instance
            Object instance = constructor.newInstance(args);
            
            // Return as interface type
            return (ResourceManagerJVMInterface) instance;
        } catch (Exception e) {
            throw new RuntimeException("Failed to create ResourceManager instance: " + e.getMessage(), e);
        } finally {
            // Reset the thread context classloader
            exit();
        }
    }

    private Constructor<?> findMatchingConstructor(Class<?> clazz, Object... args) {
        Constructor<?>[] constructors = clazz.getConstructors();
        
        for (Constructor<?> constructor : constructors) {
            if (constructor.getParameterCount() == args.length) {
                // Simple matching - can be enhanced for better type matching
                return constructor;
            }
        }
        
        throw new RuntimeException("No matching constructor found for " + clazz.getName() + 
                                 " with " + args.length + " arguments");
    }
}
