package org.apache.hadoop.yarn.server.nodemanager;

import edu.illinois.core.instance.UpgradableInstance;
import java.lang.reflect.Constructor;

/**
 * Instance helper class for creating NodeManager instances
 * using version-specific classloaders.
 * Generated by UpgradableClusterGenerator.
 */
public class NodeManagerInstance extends UpgradableInstance {

    public NodeManagerInstance(UpgradableInstance delegate) {
        super(delegate.getNodeName(), delegate.getVersion(),
                delegate.getLoader(), delegate.getPlan(),
                delegate.isMarkedForUpgrade());
    }
    /**
     * Creates a NodeManager instance for use in InJVM cluster.
     * This method uses reflection to instantiate the node with the version-specific classloader.
     */
    public NodeManagerJVMInterface createNodeManagerForInJVMCluster(Object... args) {
        // Set the thread context classloader to the version classloader
        enter();

        try {
            // Load the NodeManager class from the version classloader
            Class<?> nodeClass = getLoader().loadClass("org.apache.hadoop.yarn.server.nodemanager.NodeManager");

            // Find appropriate constructor based on argument types
            Constructor<?> constructor = findMatchingConstructor(nodeClass, args);

            // Create instance
            Object instance = constructor.newInstance(args);

            // Return as interface type
            return (NodeManagerJVMInterface) instance;
        } catch (Exception e) {
            throw new RuntimeException("Failed to create NodeManager instance: " + e.getMessage(), e);
        } finally {
            // Reset the thread context classloader
            exit();
        }
    }

    private Constructor<?> findMatchingConstructor(Class<?> clazz, Object... args) {
        Constructor<?>[] constructors = clazz.getConstructors();

        for (Constructor<?> constructor : constructors) {
            if (constructor.getParameterCount() == args.length) {
                // Simple matching - can be enhanced for better type matching
                return constructor;
            }
        }

        throw new RuntimeException("No matching constructor found for " + clazz.getName() +
                " with " + args.length + " arguments");
    }
}