package org.apache.hadoop.hdfs.server.namenode;

import org.apache.hadoop.crypto.key.KeyProviderJVMInterface;
import org.apache.hadoop.fs.permission.AclStatusJVMInterface;
import org.apache.hadoop.hdfs.protocol.LocatedBlocksJVMInterface;
import org.apache.hadoop.hdfs.protocol.RollingUpgradeInfoJVMInterface;
import org.apache.hadoop.hdfs.security.token.delegation.DelegationTokenSecretManagerJVMInterface;
import org.apache.hadoop.hdfs.server.blockmanagement.BlockManagerJVMInterface;
import org.apache.hadoop.hdfs.server.namenode.ha.EditLogTailerJVMInterface;
import org.apache.hadoop.hdfs.server.namenode.snapshot.SnapshotManagerJVMInterface;
import org.apache.hadoop.ipc.RetryCacheJVMInterface;


import java.io.IOException;
import java.util.Collection;
import java.util.concurrent.locks.ReentrantReadWriteLock;

public interface FSNamesystemJVMInterface {
    boolean isExternalInvocation();
    boolean isUpgradeFinalized();
    boolean recoverLease(String src, String holder, String clientMachine) throws IOException;
    int getNumDeadDataNodes();
    Collection<?> listCorruptFileBlocks(String path, String[] cookieTab) throws IOException;
    String getNameDirSize();
    String getNameDirStatuses();
    int getCorruptFilesCount();
    String getCorruptFiles();
    String getCompileInfo();
    String getJournalTransactionInfo();
    String getNameJournalStatus();
    String getNodeUsage();
    String getDeadNodes();
    String getLiveNodes();
    float getPercentRemaining();
    long getTotalBlocks();
    long getNonDfsUsedSpace();
    long getTotal();
    long getUsed();
    String getVersion();
    boolean getCallerContextEnabled();
    void close();
    boolean setReplication(String src, short replication) throws IOException;
    long getPostponedMisreplicatedBlocks();
    int getNumLiveDataNodes();
    long getTransactionsSinceLastLogRoll();
    boolean isInStartupSafeMode();
    RetryCacheJVMInterface getRetryCache();
    boolean isInStandbyState();
    LocatedBlocksJVMInterface getBlockLocations(String clientMachine, String srcArg, long offset, long length) throws IOException;
    long getNumFilesUnderConstruction();
    int getNumDecomLiveDataNodes();
    int getNumDecomDeadDataNodes();
    KeyProviderJVMInterface getProvider();
    void leaveSafeMode(boolean force);
    SnapshotManagerJVMInterface getSnapshotManager();
    CacheManagerJVMInterface getCacheManager();
    int getPendingDataNodeMessageCount();
    long getMillisSinceLastLoadedEdits();
    String getHAState();
    EditLogTailerJVMInterface getEditLogTailer();
    long getFilesTotal();
    String getClusterId();
    //float getReconstructionQueuesInitProgress();
    boolean hasWriteLock();
    void writeLock();
    void writeUnlock();
    AclStatusJVMInterface getAclStatus(String src) throws IOException;
    FSEditLogJVMInterface getEditLog();
    boolean saveNamespace(final long timeWindow, final long txGap) throws IOException;
    void enterSafeMode(boolean resourcesLow) throws IOException;
    int getVolumeFailuresTotal();
    long getCompleteBlocksTotal();
    DelegationTokenSecretManagerJVMInterface getDelegationTokenSecretManager();
    ReentrantReadWriteLock getFsLockForTests();
    void setFsLockForTests(ReentrantReadWriteLock lock);
    boolean isInSafeMode();
    long getPendingReplicationBlocks();
    long getCorruptReplicaBlocks();
    long getMissingBlocksCount();
    FSImageJVMInterface getFSImage();
    void readLock();
    BlockManagerJVMInterface getBlockManager();
    void readUnlock();
    LeaseManagerJVMInterface getLeaseManager();
    long[] getStats();
    boolean isHaEnabled();
    String getBlockPoolId();
    FSDirectoryJVMInterface getFSDirectory();
    String getSafemode();
    long getBlocksTotal();
    long getPendingDeletionBlocks();
    long getNNStartedTimeInMillis();
    long getBlockDeletionStartTime();
    long getUnderReplicatedBlocks();
}
