package org.apache.hadoop.hdfs.remoteProxies;

public interface BuilderInterface {
    org.apache.hadoop.thirdparty.protobuf.Message.Builder mergeFrom(byte[] arg0, int arg1, int arg2) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    org.apache.hadoop.thirdparty.protobuf.Message.Builder setRepeatedField(FieldDescriptorInterface arg0, int arg1, java.lang.Object arg2);
    org.apache.hadoop.thirdparty.protobuf.MessageLite buildPartial();
    BuilderInterface mergeFrom(CodedInputStreamInterface arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
//    BuilderType mergeFrom(ByteStringInterface arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
//    BuilderType setRepeatedField(FieldDescriptorInterface arg0, int arg1, java.lang.Object arg2);
    org.apache.hadoop.thirdparty.protobuf.Message.Builder mergeFrom(java.io.InputStream arg0) throws java.io.IOException;
//    <Type> Type getExtension(ExtensionInterface<MessageType, java.util.List<Type>> arg0, int arg1);
    org.apache.hadoop.thirdparty.protobuf.Message getDefaultInstanceForType();
    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder clear();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder mergeFrom(CodedInputStreamInterface arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
//    <Type> boolean hasExtension(GeneratedExtensionInterface<MessageType, Type> arg0);
    UnknownFieldSetInterface getUnknownFields();
    BuilderInterface setField(FieldDescriptorInterface arg0, java.lang.Object arg1);
//    <Type> Type getExtension(ExtensionInterface<MessageType, Type> arg0);
    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder mergeFrom(ByteStringInterface arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    org.apache.hadoop.thirdparty.protobuf.Message.Builder setUnknownFields(UnknownFieldSetInterface arg0);
    <Type> BuilderInterface setExtension(GeneratedExtensionInterface<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.MethodOptions, java.util.List<Type>> arg0, int arg1, Type arg2);
    org.apache.hadoop.thirdparty.protobuf.Message.Builder getFieldBuilder(FieldDescriptorInterface arg0);
//    BuilderType mergeFrom(byte[] arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
//    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder mergeFrom(byte[] arg0, int arg1, int arg2) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    org.apache.hadoop.thirdparty.protobuf.Message.Builder mergeUnknownFields(UnknownFieldSetInterface arg0);
//    <Type> Type getExtension(ExtensionLiteInterface<MessageType, java.util.List<Type>> arg0, int arg1);
    org.apache.hadoop.thirdparty.protobuf.Message.Builder mergeFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsMutable();
    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder mergeFrom(byte[] arg0, int arg1, int arg2, ExtensionRegistryLiteInterface arg3) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
//    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder mergeFrom(java.io.InputStream arg0) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.Message buildPartial();
//    BuilderInterface setRepeatedField(FieldDescriptorInterface arg0, int arg1, java.lang.Object arg2);
    void ensureUninterpretedOptionIsMutable();
//    BuilderType setUnknownFieldsProto3(UnknownFieldSetInterface arg0);
//    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder mergeFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
//    MethodOptionsInterface buildPartial();
    BuilderInterface addUninterpretedOption(int arg0, BuilderInterface arg1);
//    MethodOptionsInterface getDefaultInstanceForType();
    org.apache.hadoop.thirdparty.protobuf.Message.Builder mergeFrom(byte[] arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    BuilderInterface clearDeprecated();
    MethodOptionsInterface build();
    boolean mergeDelimitedFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    void onBuilt();
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.List<? super T> arg1);
    BuilderInterface setDeprecated(boolean arg0);
    BuilderInterface clearUninterpretedOption();
    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder mergeFrom(org.apache.hadoop.thirdparty.protobuf.MessageLite arg0);
//    <Type> BuilderType addExtension(ExtensionInterface<MessageType, java.util.List<Type>> arg0, Type arg1);
    BuilderInterface addUninterpretedOption(UninterpretedOptionInterface arg0);
//    BuilderType internalMergeFrom(AbstractMessageLiteInterface arg0);
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder setField(FieldDescriptorInterface arg0, java.lang.Object arg1);
//    <Type> BuilderType setExtension(GeneratedExtensionInterface<MessageType, Type> arg0, Type arg1);
//    BuilderType clearField(FieldDescriptorInterface arg0);
//    BuilderInterface mergeUnknownFields(UnknownFieldSetInterface arg0);
    void dispose();
//    BuilderType mergeFrom(CodedInputStreamInterface arg0) throws java.io.IOException;
//    BuilderType mergeFrom(byte[] arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    void maybeForceBuilderInitialization();
//    <Type> boolean hasExtension(ExtensionLiteInterface<MessageType, Type> arg0);
//    <Type> BuilderType setExtension(ExtensionLiteInterface<MessageType, java.util.List<Type>> arg0, int arg1, Type arg2);
//    <Type> BuilderType clearExtension(ExtensionLiteInterface<MessageType, ?> arg0);
    org.apache.hadoop.thirdparty.protobuf.Message.Builder addRepeatedField(FieldDescriptorInterface arg0, java.lang.Object arg1);
    java.util.List<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOption.Builder> getUninterpretedOptionBuilderList();
//    BuilderType internalMergeFrom(MessageType arg0);
    UninterpretedOptionInterface getUninterpretedOption(int arg0);
    BuilderInterface mergeFrom(MethodOptionsInterface arg0);
    <Type> BuilderInterface addExtension(GeneratedExtensionInterface<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.MethodOptions, java.util.List<Type>> arg0, Type arg1);
    UninitializedMessageExceptionInterface newUninitializedMessageException(org.apache.hadoop.thirdparty.protobuf.MessageLite arg0);
    java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOptionOrBuilder> getUninterpretedOptionOrBuilderList();
//    <Type> int getExtensionCount(ExtensionLiteInterface<MessageType, java.util.List<Type>> arg0);
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.Collection<? super T> arg1);
    boolean hasIdempotencyLevel();
    boolean hasField(FieldDescriptorInterface arg0);
//    <Type> BuilderType addExtension(ExtensionLiteInterface<MessageType, java.util.List<Type>> arg0, Type arg1);
    java.lang.String getInitializationErrorString();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder clear();
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFields();
//    BuilderType mergeFrom(byte[] arg0, int arg1, int arg2) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    BuilderInterface addAllUninterpretedOption(java.lang.Iterable<? extends org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOption> arg0);
    FieldAccessorTableInterface internalGetFieldAccessorTable();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder mergeFrom(byte[] arg0, int arg1, int arg2, ExtensionRegistryLiteInterface arg3) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
//    BuilderType clearOneof(OneofDescriptorInterface arg0);
    BuilderInterface setUninterpretedOption(int arg0, UninterpretedOptionInterface arg1);
//    BuilderInterface addRepeatedField(FieldDescriptorInterface arg0, java.lang.Object arg1);
    boolean hasOneof(OneofDescriptorInterface arg0);
//    BuilderType mergeFrom(ByteStringInterface arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
//    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder mergeFrom(CodedInputStreamInterface arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
//    <Type> Type getExtension(GeneratedExtensionInterface<MessageType, java.util.List<Type>> arg0, int arg1);
//    BuilderType setField(FieldDescriptorInterface arg0, java.lang.Object arg1);
    BuilderInterface removeUninterpretedOption(int arg0);
//    BuilderType mergeFrom(org.apache.hadoop.thirdparty.protobuf.MessageLite arg0);
//    BuilderType mergeFrom(java.io.InputStream arg0) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.MessageLite build();
    MapFieldInterface internalGetMutableMapField(int arg0);
    int getRepeatedFieldCount(FieldDescriptorInterface arg0);
    <Type> BuilderInterface setExtension(GeneratedExtensionInterface<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.MethodOptions, Type> arg0, Type arg1);
//    BuilderType mergeFrom(org.apache.hadoop.thirdparty.protobuf.Message arg0);
    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder mergeFrom(ByteStringInterface arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
//    <Type> Type getExtension(ExtensionLiteInterface<MessageType, Type> arg0);
    BuilderInterface getUninterpretedOptionBuilder(int arg0);
//    <Type> BuilderType setExtension(ExtensionLiteInterface<MessageType, Type> arg0, Type arg1);
//    BuilderType mergeUnknownFields(UnknownFieldSetInterface arg0);
    RepeatedFieldBuilderV3Interface<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOption, org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOption.Builder, org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOptionOrBuilder> getUninterpretedOptionFieldBuilder();
//    org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent getParentForChildren();
    java.lang.Object getField(FieldDescriptorInterface arg0);
    java.lang.String getReadingExceptionMessage(java.lang.String arg0);
    int getUninterpretedOptionCount();
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.MethodOptions.IdempotencyLevel getIdempotencyLevel();
    <Type> BuilderInterface clearExtension(GeneratedExtensionInterface<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.MethodOptions, ?> arg0);
    BuilderInterface clearField(FieldDescriptorInterface arg0);
//    <Type> boolean hasExtension(ExtensionInterface<MessageType, Type> arg0);
//    BuilderType mergeFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
//    BuilderType mergeFrom(byte[] arg0, int arg1, int arg2, ExtensionRegistryLiteInterface arg3) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder mergeFrom(ByteStringInterface arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    java.lang.String toString();
//    org.apache.hadoop.thirdparty.protobuf.MessageLite getDefaultInstanceForType();
    BuilderInterface addUninterpretedOptionBuilder();
//    BuilderType mergeFrom(CodedInputStreamInterface arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.Message build();
//    <Type> BuilderType clearExtension(GeneratedExtensionInterface<MessageType, ?> arg0);
    BuilderInterface clearOneof(OneofDescriptorInterface arg0);
    BuilderInterface addUninterpretedOption(int arg0, UninterpretedOptionInterface arg1);
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder clearOneof(OneofDescriptorInterface arg0);
    BuilderInterface setUninterpretedOption(int arg0, BuilderInterface arg1);
    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder mergeFrom(byte[] arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder clearField(FieldDescriptorInterface arg0);
    void onChanged();
    java.lang.Object getRepeatedField(FieldDescriptorInterface arg0, int arg1);
    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder mergeFrom(CodedInputStreamInterface arg0) throws java.io.IOException;
    <T> void addAllCheckingNulls(java.lang.Iterable<T> arg0, java.util.List<? super T> arg1);
    BuilderInterface addUninterpretedOption(BuilderInterface arg0);
    void mergeExtensionFields(ExtendableMessageInterface arg0);
//    <Type> Type getExtension(GeneratedExtensionInterface<MessageType, Type> arg0);
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder mergeFrom(ByteStringInterface arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
//    <Type> BuilderType addExtension(GeneratedExtensionInterface<MessageType, java.util.List<Type>> arg0, Type arg1);
    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder clone();
    BuilderInterface mergeFrom(org.apache.hadoop.thirdparty.protobuf.Message arg0);
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder mergeFrom(byte[] arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
//    <Type> BuilderType setExtension(ExtensionInterface<MessageType, java.util.List<Type>> arg0, int arg1, Type arg2);
//    <Type> BuilderType setExtension(GeneratedExtensionInterface<MessageType, java.util.List<Type>> arg0, int arg1, Type arg2);
    DescriptorInterface getDescriptor();
//    BuilderType clear();
    UninitializedMessageExceptionInterface newUninitializedMessageException(org.apache.hadoop.thirdparty.protobuf.Message arg0);
    MapFieldInterface internalGetMapField(int arg0);
    org.apache.hadoop.thirdparty.protobuf.Message.Builder getRepeatedFieldBuilder(FieldDescriptorInterface arg0, int arg1);
//    BuilderInterface clear();
//    BuilderType setUnknownFields(UnknownFieldSetInterface arg0);
//    BuilderInterface setUnknownFields(UnknownFieldSetInterface arg0);
    boolean extensionsAreInitialized();
//    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder mergeFrom(byte[] arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
//    <Type> BuilderType clearExtension(ExtensionInterface<MessageType, ?> arg0);
    void ensureExtensionsIsMutable();
//    <Type> BuilderType setExtension(ExtensionInterface<MessageType, Type> arg0, Type arg1);
//    BuilderType addRepeatedField(FieldDescriptorInterface arg0, java.lang.Object arg1);
    FieldDescriptorInterface getOneofFieldDescriptor(OneofDescriptorInterface arg0);
    BuilderInterface addUninterpretedOptionBuilder(int arg0);
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOptionOrBuilder getUninterpretedOptionOrBuilder(int arg0);
    java.util.List<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOption> getUninterpretedOptionList();
//    <Type> int getExtensionCount(ExtensionInterface<MessageType, java.util.List<Type>> arg0);
//    void verifyExtensionContainingType(ExtensionInterface<MessageType, ?> arg0);
    void markClean();
//    BuilderInterface clone();
//    BuilderType mergeFrom(org.apache.hadoop.thirdparty.protobuf.Message arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder mergeFrom(CodedInputStreamInterface arg0) throws java.io.IOException;
//    BuilderType clone();
    java.util.List<java.lang.String> findInitializationErrors();
    boolean hasDeprecated();
    boolean mergeDelimitedFrom(java.io.InputStream arg0) throws java.io.IOException;
    boolean getDeprecated();
    void internalSetExtensionSet(FieldSetInterface<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor> arg0);
    BuilderInterface clearIdempotencyLevel();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder mergeFrom(org.apache.hadoop.thirdparty.protobuf.Message arg0);
//    <Type> int getExtensionCount(GeneratedExtensionInterface<MessageType, java.util.List<Type>> arg0);
    boolean isClean();
    DescriptorInterface getDescriptorForType();
    BuilderInterface setIdempotencyLevel(org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.MethodOptions.IdempotencyLevel arg0);
//    BuilderType setUnknownFieldsInternal(UnknownFieldSetInterface arg0);
    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForField(FieldDescriptorInterface arg0);
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder clone();
    boolean isInitialized();
    void verifyContainingType(FieldDescriptorInterface arg0);
    FieldSetInterface<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor> buildExtensions();
}