package org.apache.hadoop.hdfs.remoteProxies;

public interface CodedOutputStreamInterface {
    void writeRawByte(byte arg0) throws java.io.IOException;
    int computeByteBufferSizeNoTag(java.nio.ByteBuffer arg0);
    void writeSInt64(int arg0, long arg1) throws java.io.IOException;
    void writeSFixed32NoTag(int arg0) throws java.io.IOException;
    int computeBoolSize(int arg0, boolean arg1);
    CodedOutputStreamInterface newUnsafeInstance(java.nio.ByteBuffer arg0);
    int computeMessageSetExtensionSize(int arg0, org.apache.hadoop.thirdparty.protobuf.MessageLite arg1);
    int spaceLeft();
    boolean isSerializationDeterministic();
    void writeUInt64NoTag(long arg0) throws java.io.IOException;
    void writeInt32(int arg0, int arg1) throws java.io.IOException;
    int computeFixed32SizeNoTag(int arg0);
    int computeBoolSizeNoTag(boolean arg0);
    int computeBytesSize(int arg0, ByteStringInterface arg1);
    void writeMessageSetExtension(int arg0, org.apache.hadoop.thirdparty.protobuf.MessageLite arg1) throws java.io.IOException;
    int computeTagSize(int arg0);
    int computeMessageSize(int arg0, org.apache.hadoop.thirdparty.protobuf.MessageLite arg1);
    int computeGroupSizeNoTag(org.apache.hadoop.thirdparty.protobuf.MessageLite arg0);
    void writeByteArrayNoTag(byte[] arg0) throws java.io.IOException;
    int computeStringSizeNoTag(java.lang.String arg0);
    void writeUInt64(int arg0, long arg1) throws java.io.IOException;
    void writeSFixed32(int arg0, int arg1) throws java.io.IOException;
    void inefficientWriteStringNoTag(java.lang.String arg0, UnpairedSurrogateExceptionInterface arg1) throws java.io.IOException;
    int computeSFixed32Size(int arg0, int arg1);
    void writeFixed64NoTag(long arg0) throws java.io.IOException;
    int computeLengthDelimitedFieldSize(int arg0);
    int computeByteArraySizeNoTag(byte[] arg0);
    int computeInt32SizeNoTag(int arg0);
    int computeBytesSizeNoTag(ByteStringInterface arg0);
    void writeFixed32(int arg0, int arg1) throws java.io.IOException;
    void write(byte[] arg0, int arg1, int arg2) throws java.io.IOException;
    void writeLazy(byte[] arg0, int arg1, int arg2) throws java.io.IOException;
    void writeInt64(int arg0, long arg1) throws java.io.IOException;
    void writeRawBytes(java.nio.ByteBuffer arg0) throws java.io.IOException;
    CodedOutputStreamInterface newInstance(java.nio.ByteBuffer arg0, int arg1);
    CodedOutputStreamInterface newInstance(java.nio.ByteBuffer arg0);
    int computeSFixed32SizeNoTag(int arg0);
    int computeEnumSizeNoTag(int arg0);
    void writeSInt32(int arg0, int arg1) throws java.io.IOException;
    void writeRawBytes(ByteStringInterface arg0) throws java.io.IOException;
    CodedOutputStreamInterface newSafeInstance(java.nio.ByteBuffer arg0);
    void writeEnum(int arg0, int arg1) throws java.io.IOException;
    void writeFixed32NoTag(int arg0) throws java.io.IOException;
    int computeByteBufferSize(int arg0, java.nio.ByteBuffer arg1);
    void writeFixed64(int arg0, long arg1) throws java.io.IOException;
    void writeByteBuffer(int arg0, java.nio.ByteBuffer arg1) throws java.io.IOException;
    int computeDoubleSize(int arg0, double arg1);
    int computeLazyFieldSize(int arg0, LazyFieldLiteInterface arg1);
    void writeSInt32NoTag(int arg0) throws java.io.IOException;
    int computeFixed64Size(int arg0, long arg1);
    int computeStringSize(int arg0, java.lang.String arg1);
    int computeInt32Size(int arg0, int arg1);
    void writeDoubleNoTag(double arg0) throws java.io.IOException;
    void checkNoSpaceLeft();
    int computeFixed64SizeNoTag(long arg0);
    int computeInt64Size(int arg0, long arg1);
    void writeByteArrayNoTag(byte[] arg0, int arg1, int arg2) throws java.io.IOException;
    void write(byte arg0) throws java.io.IOException;
    int computeUInt32Size(int arg0, int arg1);
    void writeRawByte(int arg0) throws java.io.IOException;
    void write(java.nio.ByteBuffer arg0) throws java.io.IOException;
    CodedOutputStreamInterface newInstance(java.io.OutputStream arg0, int arg1);
    void writeRawBytes(byte[] arg0, int arg1, int arg2) throws java.io.IOException;
    int computeMessageSizeNoTag(org.apache.hadoop.thirdparty.protobuf.MessageLite arg0);
    void writeGroupNoTag(org.apache.hadoop.thirdparty.protobuf.MessageLite arg0) throws java.io.IOException;
    int computePreferredBufferSize(int arg0);
    int computeDoubleSizeNoTag(double arg0);
    long encodeZigZag64(long arg0);
    void writeFloatNoTag(float arg0) throws java.io.IOException;
    void writeSFixed64(int arg0, long arg1) throws java.io.IOException;
    CodedOutputStreamInterface newInstance(byte[] arg0, int arg1, int arg2);
    void writeRawBytes(byte[] arg0) throws java.io.IOException;
    int computeFloatSizeNoTag(float arg0);
    void writeEnumNoTag(int arg0) throws java.io.IOException;
    void writeString(int arg0, java.lang.String arg1) throws java.io.IOException;
    void writeBoolNoTag(boolean arg0) throws java.io.IOException;
    int computeByteArraySize(int arg0, byte[] arg1);
    int computeRawVarint64Size(long arg0);
    void writeDouble(int arg0, double arg1) throws java.io.IOException;
    void writeRawVarint64(long arg0) throws java.io.IOException;
    int computeSFixed64Size(int arg0, long arg1);
    void writeRawMessageSetExtension(int arg0, ByteStringInterface arg1) throws java.io.IOException;
    int computeInt64SizeNoTag(long arg0);
    void writeLazy(java.nio.ByteBuffer arg0) throws java.io.IOException;
    void writeSFixed64NoTag(long arg0) throws java.io.IOException;
    void writeRawLittleEndian32(int arg0) throws java.io.IOException;
    int computeSFixed64SizeNoTag(long arg0);
    int encodeZigZag32(int arg0);
    void writeBytes(int arg0, ByteStringInterface arg1) throws java.io.IOException;
    void writeByteArray(int arg0, byte[] arg1, int arg2, int arg3) throws java.io.IOException;
    void writeRawVarint32(int arg0) throws java.io.IOException;
    void writeUInt32(int arg0, int arg1) throws java.io.IOException;
    int computeUInt64SizeNoTag(long arg0);
    int computeLazyFieldMessageSetExtensionSize(int arg0, LazyFieldLiteInterface arg1);
    int computeUInt64Size(int arg0, long arg1);
    int computeRawVarint32Size(int arg0);
    int computeSInt64SizeNoTag(long arg0);
    CodedOutputStreamInterface newInstance(java.io.OutputStream arg0);
    void writeBytesNoTag(ByteStringInterface arg0) throws java.io.IOException;
    int computeUInt32SizeNoTag(int arg0);
    int computeLazyFieldSizeNoTag(LazyFieldLiteInterface arg0);
    void writeByteArray(int arg0, byte[] arg1) throws java.io.IOException;
    void writeBool(int arg0, boolean arg1) throws java.io.IOException;
    int computeFloatSize(int arg0, float arg1);
    void writeInt64NoTag(long arg0) throws java.io.IOException;
    int computeSInt32Size(int arg0, int arg1);
    void writeGroup(int arg0, org.apache.hadoop.thirdparty.protobuf.MessageLite arg1) throws java.io.IOException;
    CodedOutputStreamInterface newInstance(ByteOutputInterface arg0, int arg1);
    void writeRawLittleEndian64(long arg0) throws java.io.IOException;
    void writeFloat(int arg0, float arg1) throws java.io.IOException;
    void useDeterministicSerialization();
    void writeMessage(int arg0, org.apache.hadoop.thirdparty.protobuf.MessageLite arg1) throws java.io.IOException;
    int computeEnumSize(int arg0, int arg1);
    int computeGroupSize(int arg0, org.apache.hadoop.thirdparty.protobuf.MessageLite arg1);
    void writeSInt64NoTag(long arg0) throws java.io.IOException;
    void writeMessageNoTag(org.apache.hadoop.thirdparty.protobuf.MessageLite arg0) throws java.io.IOException;
    void flush() throws java.io.IOException;
    CodedOutputStreamInterface newInstance(byte[] arg0);
    int computeFixed32Size(int arg0, int arg1);
    int computeSInt32SizeNoTag(int arg0);
    int getTotalBytesWritten();
    int computeSInt64Size(int arg0, long arg1);
    int computeRawMessageSetExtensionSize(int arg0, ByteStringInterface arg1);
    void writeInt32NoTag(int arg0) throws java.io.IOException;
    void writeTag(int arg0, int arg1) throws java.io.IOException;
    void writeStringNoTag(java.lang.String arg0) throws java.io.IOException;
    void writeUInt32NoTag(int arg0) throws java.io.IOException;
}