package org.apache.hadoop.hdfs.remoteProxies;

public interface ConnectionInterface {
    void processOneRpc(java.nio.ByteBuffer arg0) throws java.io.IOException, java.lang.InterruptedException;
    void setupHttpRequestOnIpcPortResponse() throws java.io.IOException;
    org.apache.hadoop.ipc.Server.AuthProtocol initializeAuthContext(int arg0) throws java.io.IOException;
    java.lang.String getHostAddress();
    void unwrapPacketAndProcessRpcs(byte[] arg0) throws java.io.IOException, java.lang.InterruptedException;
    void close();
    java.lang.String toString();
    void checkDataLength(int arg0) throws java.io.IOException;
    void sendResponse(RpcCallInterface arg0) throws java.io.IOException;
    java.net.InetAddress getHostInetAddress();
    void saslReadAndProcess(BufferInterface arg0) throws org.apache.hadoop.ipc.RpcServerException, java.io.IOException, java.lang.InterruptedException;
    RpcSaslProtoInterface processSaslToken(RpcSaslProtoInterface arg0) throws javax.security.sasl.SaslException;
    void processRpcOutOfBandRequest(RpcRequestHeaderProtoInterface arg0, BufferInterface arg1) throws org.apache.hadoop.ipc.RpcServerException, java.io.IOException, java.lang.InterruptedException;
    void doSaslReply(java.lang.Exception arg0) throws java.io.IOException;
    void doSaslReply(org.apache.hadoop.thirdparty.protobuf.Message arg0) throws java.io.IOException;
    void switchToSimple();
    boolean isIdle();
    void incRpcCount();
    boolean setShouldClose();
    javax.security.sasl.SaslServer createSaslServer(org.apache.hadoop.security.SaslRpcServer.AuthMethod arg0) throws java.io.IOException, java.lang.InterruptedException;
    void setupBadVersionResponse(int arg0) throws java.io.IOException;
    long getLastContact();
    int getServiceClass();
    void setServiceClass(int arg0);
    void disposeSasl();
    void processRpcRequest(RpcRequestHeaderProtoInterface arg0, BufferInterface arg1) throws org.apache.hadoop.ipc.RpcServerException, java.lang.InterruptedException;
    UserGroupInformationInterface getAuthorizedUgi(java.lang.String arg0) throws org.apache.hadoop.security.token.SecretManager.InvalidToken, org.apache.hadoop.security.AccessControlException;
    void saslProcess(RpcSaslProtoInterface arg0) throws org.apache.hadoop.ipc.RpcServerException, java.io.IOException, java.lang.InterruptedException;
    <T> T getMessage(org.apache.hadoop.thirdparty.protobuf.Message arg0, BufferInterface arg1) throws org.apache.hadoop.ipc.RpcServerException;
    void authorizeConnection() throws org.apache.hadoop.ipc.RpcServerException;
    boolean isOnAuxiliaryPort();
    void processConnectionContext(BufferInterface arg0) throws org.apache.hadoop.ipc.RpcServerException;
    ServerInterface getServer();
    void decRpcCount();
    int readAndProcess() throws java.io.IOException, java.lang.InterruptedException;
    java.lang.Throwable getTrueCause(java.io.IOException arg0);
    RpcSaslProtoInterface buildSaslNegotiateResponse() throws java.lang.InterruptedException, javax.security.sasl.SaslException, java.io.IOException;
    void checkRpcHeaders(RpcRequestHeaderProtoInterface arg0) throws org.apache.hadoop.ipc.RpcServerException;
    RpcSaslProtoInterface processSaslMessage(RpcSaslProtoInterface arg0) throws javax.security.sasl.SaslException, java.io.IOException, org.apache.hadoop.security.AccessControlException, java.lang.InterruptedException;
    boolean shouldClose();
    int getIngressPort();
    java.lang.String getEstablishedQOP();
    void setLastContact(long arg0);
    int getRemotePort();
    RpcSaslProtoInterface buildSaslResponse(org.apache.hadoop.ipc.protobuf.RpcHeaderProtos.RpcSaslProto.SaslState arg0, byte[] arg1);
}