package org.apache.hadoop.hdfs.remoteProxies;

public interface DaemonInterface {
    java.lang.Thread.UncaughtExceptionHandler getDefaultUncaughtExceptionHandler();
    void registerNatives();
    java.lang.ThreadGroup getThreadGroup();
    java.lang.Thread[] getThreads();
    void checkAccess();
    java.lang.ClassLoader getContextClassLoader();
    void stop0(java.lang.Object arg0);
    void setDefaultUncaughtExceptionHandler(java.lang.Thread.UncaughtExceptionHandler arg0);
    void setDaemon(boolean arg0);
    void sleep(long arg0, int arg1) throws java.lang.InterruptedException;
    void sleep(long arg0) throws java.lang.InterruptedException;
    void setPriority(int arg0);
    java.lang.Runnable getRunnable();
    java.lang.StackTraceElement[][] dumpThreads(java.lang.Thread[] arg0);
    boolean isCCLOverridden(java.lang.Class<?> arg0);
    java.lang.Thread.UncaughtExceptionHandler getUncaughtExceptionHandler();
    void start0();
    java.lang.Thread currentThread();
    java.lang.Object clone() throws java.lang.CloneNotSupportedException;
    void suspend0();
    boolean isInterrupted(boolean arg0);
    void interrupt0();
    int enumerate(java.lang.Thread[] arg0);
    boolean auditSubclass(java.lang.Class<?> arg0);
    void onSpinWait();
    void setNativeName(java.lang.String arg0);
    java.lang.String getName();
    void run();
    boolean isAlive();
    void interrupt();
    boolean isDaemon();
    void setName(java.lang.String arg0);
    boolean interrupted();
    int nextThreadNum();
    void processQueue(java.lang.ref.ReferenceQueue<java.lang.Class<?>> arg0, java.util.concurrent.ConcurrentMap<? extends java.lang.ref.WeakReference<java.lang.Class<?>>, ?> arg1);
    void setContextClassLoader(java.lang.ClassLoader arg0);
    int countStackFrames();
    int activeCount();
    void setPriority0(int arg0);
    void suspend();
    void stop();
    java.lang.StackTraceElement[] getStackTrace();
    void yield();
    java.lang.String toString();
    java.lang.Thread.State getState();
    void resume();
    long nextThreadID();
    void join() throws java.lang.InterruptedException;
    java.util.Map<java.lang.Thread, java.lang.StackTraceElement[]> getAllStackTraces();
    void dispatchUncaughtException(java.lang.Throwable arg0);
    void blockedOn(sun.nio.ch.Interruptible arg0);
    long getId();
    void dumpStack();
    boolean isInterrupted();
    void start();
    void join(long arg0, int arg1) throws java.lang.InterruptedException;
    int getPriority();
    void exit();
    void resume0();
    void join(long arg0) throws java.lang.InterruptedException;
    boolean holdsLock(java.lang.Object arg0);
    void setUncaughtExceptionHandler(java.lang.Thread.UncaughtExceptionHandler arg0);
}