package org.apache.hadoop.hdfs.remoteProxies;

public interface DataXceiverInterface {
    void blockChecksum(ExtendedBlockInterface arg0, TokenInterface<org.apache.hadoop.hdfs.security.token.block.BlockTokenIdentifier> arg1, BlockChecksumOptionsInterface arg2) throws java.io.IOException;
    void checkAccess(java.io.OutputStream arg0, boolean arg1, ExtendedBlockInterface arg2, TokenInterface<org.apache.hadoop.hdfs.security.token.block.BlockTokenIdentifier> arg3, org.apache.hadoop.hdfs.protocol.datatransfer.Op arg4, org.apache.hadoop.hdfs.security.token.block.BlockTokenIdentifier.AccessMode arg5, org.apache.hadoop.fs.StorageType[] arg6, java.lang.String[] arg7) throws java.io.IOException;
    DataNodeInterface getDataNode();
    BlockReceiverInterface getBlockReceiver(ExtendedBlockInterface arg0, org.apache.hadoop.fs.StorageType arg1, java.io.DataInputStream arg2, java.lang.String arg3, java.lang.String arg4, org.apache.hadoop.hdfs.protocol.datatransfer.BlockConstructionStage arg5, long arg6, long arg7, long arg8, java.lang.String arg9, DatanodeInfoInterface arg10, DataNodeInterface arg11, DataChecksumInterface arg12, CachingStrategyInterface arg13, boolean arg14, boolean arg15, java.lang.String arg16) throws java.io.IOException;
    void opWriteBlock(java.io.DataInputStream arg0) throws java.io.IOException;
    TraceScopeInterface continueTraceSpan(ClientOperationHeaderProtoInterface arg0, java.lang.String arg1);
    void sendShmErrorResponse(org.apache.hadoop.hdfs.protocol.proto.DataTransferProtos.Status arg0, java.lang.String arg1) throws java.io.IOException;
    void opCopyBlock(java.io.DataInputStream arg0) throws java.io.IOException;
    void opRequestShortCircuitFds(java.io.DataInputStream arg0) throws java.io.IOException;
    void releaseShortCircuitFds(SlotIdInterface arg0) throws java.io.IOException;
    void writeBlock(ExtendedBlockInterface arg0, org.apache.hadoop.fs.StorageType arg1, TokenInterface<org.apache.hadoop.hdfs.security.token.block.BlockTokenIdentifier> arg2, java.lang.String arg3, DatanodeInfoInterface[] arg4, org.apache.hadoop.fs.StorageType[] arg5, DatanodeInfoInterface arg6, org.apache.hadoop.hdfs.protocol.datatransfer.BlockConstructionStage arg7, int arg8, long arg9, long arg10, long arg11, DataChecksumInterface arg12, CachingStrategyInterface arg13, boolean arg14, boolean arg15, boolean[] arg16, java.lang.String arg17, java.lang.String[] arg18) throws java.io.IOException;
    void initialize(java.io.DataInputStream arg0);
    void run();
    void opRequestShortCircuitShm(java.io.DataInputStream arg0) throws java.io.IOException;
    void checkAndWaitForBP(ExtendedBlockInterface arg0) throws java.io.IOException;
    void writeSuccessWithChecksumInfo(BlockSenderInterface arg0, java.io.DataOutputStream arg1) throws java.io.IOException;
    BlockReceiverInterface getCurrentBlockReceiver();
    org.apache.hadoop.hdfs.protocol.datatransfer.Op readOp() throws java.io.IOException;
    CachingStrategyInterface getCachingStrategy(CachingStrategyProtoInterface arg0);
    void setCurrentBlockReceiver(BlockReceiverInterface arg0);
    void replaceBlock(ExtendedBlockInterface arg0, org.apache.hadoop.fs.StorageType arg1, TokenInterface<org.apache.hadoop.hdfs.security.token.block.BlockTokenIdentifier> arg2, java.lang.String arg3, DatanodeInfoInterface arg4, java.lang.String arg5) throws java.io.IOException;
    void blockGroupChecksum(StripedBlockInfoInterface arg0, TokenInterface<org.apache.hadoop.hdfs.security.token.block.BlockTokenIdentifier> arg1, long arg2, BlockChecksumOptionsInterface arg3) throws java.io.IOException;
    void sendOOB() throws java.io.IOException, java.lang.InterruptedException;
    void opReadBlock() throws java.io.IOException;
    void incrDatanodeNetworkErrors();
    TraceScopeInterface continueTraceSpan(ByteStringInterface arg0, java.lang.String arg1);
    void transferBlock(ExtendedBlockInterface arg0, TokenInterface<org.apache.hadoop.hdfs.security.token.block.BlockTokenIdentifier> arg1, java.lang.String arg2, DatanodeInfoInterface[] arg3, org.apache.hadoop.fs.StorageType[] arg4, java.lang.String[] arg5) throws java.io.IOException;
    void opTransferBlock(java.io.DataInputStream arg0) throws java.io.IOException;
    void opBlockChecksum(java.io.DataInputStream arg0) throws java.io.IOException;
    void copyBlock(ExtendedBlockInterface arg0, TokenInterface<org.apache.hadoop.hdfs.security.token.block.BlockTokenIdentifier> arg1) throws java.io.IOException;
    void sendResponse(org.apache.hadoop.hdfs.protocol.proto.DataTransferProtos.Status arg0, java.lang.String arg1) throws java.io.IOException;
    DataXceiverInterface create(org.apache.hadoop.hdfs.net.Peer arg0, DataNodeInterface arg1, DataXceiverServerInterface arg2) throws java.io.IOException;
    void requestShortCircuitFds(ExtendedBlockInterface arg0, TokenInterface<org.apache.hadoop.hdfs.security.token.block.BlockTokenIdentifier> arg1, SlotIdInterface arg2, int arg3, boolean arg4) throws java.io.IOException;
    void checkAccess(java.io.OutputStream arg0, boolean arg1, ExtendedBlockInterface arg2, TokenInterface<org.apache.hadoop.hdfs.security.token.block.BlockTokenIdentifier> arg3, org.apache.hadoop.hdfs.protocol.datatransfer.Op arg4, org.apache.hadoop.hdfs.security.token.block.BlockTokenIdentifier.AccessMode arg5) throws java.io.IOException;
    void requestShortCircuitShm(java.lang.String arg0) throws java.io.IOException;
    void sendShmSuccessResponse(DomainSocketInterface arg0, NewShmInfoInterface arg1) throws java.io.IOException;
    void collectThreadLocalStates();
    void updateCurrentThreadName(java.lang.String arg0);
    void opStripedBlockChecksum(java.io.DataInputStream arg0) throws java.io.IOException;
    long elapsed();
    void opReleaseShortCircuitFds(java.io.DataInputStream arg0) throws java.io.IOException;
    TraceScopeInterface continueTraceSpan(BaseHeaderProtoInterface arg0, java.lang.String arg1);
    void processOp(org.apache.hadoop.hdfs.protocol.datatransfer.Op arg0) throws java.io.IOException;
    java.io.OutputStream getOutputStream();
    void writeResponse(org.apache.hadoop.hdfs.protocol.proto.DataTransferProtos.Status arg0, java.lang.String arg1, java.io.OutputStream arg2) throws java.io.IOException;
    void stopWriter();
    void releaseSocket();
    void opReplaceBlock(java.io.DataInputStream arg0) throws java.io.IOException;
    java.io.DataOutputStream getBufferedOutputStream();
    void readBlock(ExtendedBlockInterface arg0, TokenInterface<org.apache.hadoop.hdfs.security.token.block.BlockTokenIdentifier> arg1, java.lang.String arg2, long arg3, long arg4, boolean arg5, CachingStrategyInterface arg6) throws java.io.IOException;
}