package org.apache.hadoop.hdfs.remoteProxies;

public interface EnumValueDescriptorProtoInterface {
    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder toBuilder();
    boolean compareMapField(java.lang.Object arg0, java.lang.Object arg1);
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList emptyBooleanList();
    void writeTo(java.io.OutputStream arg0) throws java.io.IOException;
    EnumValueDescriptorProtoInterface parseFrom(java.nio.ByteBuffer arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    void writeTo(CodedOutputStreamInterface arg0) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList newLongList();
    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3> getParserForType();
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList newDoubleList();
    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder newBuilderForType();
    FieldAccessorTableInterface internalGetFieldAccessorTable();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1) throws java.io.IOException;
    byte[] toByteArray();
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsRaw();
    EnumValueDescriptorProtoInterface parseFrom(byte[] arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    java.lang.Object getRepeatedField(FieldDescriptorInterface arg0, int arg1);
    boolean parseUnknownField(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    int hashBoolean(boolean arg0);
    void setMemoizedSerializedSize(int arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList emptyIntList();
    FieldDescriptorInterface getOneofFieldDescriptor(OneofDescriptorInterface arg0);
    int hashFields(int arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    EnumValueDescriptorProtoInterface parseFrom(ByteStringInterface arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    EnumValueDescriptorProtoInterface parseFrom(byte[] arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    DescriptorInterface getDescriptorForType();
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList emptyFloatList();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
    boolean hasOneof(OneofDescriptorInterface arg0);
    <K, V> void serializeMapTo(CodedOutputStreamInterface arg0, java.util.Map<K, V> arg1, MapEntryInterface<K, V> arg2, int arg3) throws java.io.IOException;
    <V> void serializeStringMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.String, V> arg1, MapEntryInterface<java.lang.String, V> arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList arg0);
    BuilderInterface newBuilder();
    EnumValueDescriptorProtoInterface parseFrom(CodedInputStreamInterface arg0) throws java.io.IOException;
    void writeString(CodedOutputStreamInterface arg0, int arg1, java.lang.Object arg2) throws java.io.IOException;
    int getNumber();
    java.lang.reflect.Method getMethodOrDie(java.lang.Class arg0, java.lang.String arg1, java.lang.Class... arg2);
    int hashLong(long arg0);
    boolean hasNumber();
    boolean hasField(FieldDescriptorInterface arg0);
    void makeExtensionsImmutable();
    UnknownFieldSetInterface getUnknownFields();
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList emptyDoubleList();
    java.lang.Object invokeOrDie(java.lang.reflect.Method arg0, java.lang.Object arg1, java.lang.Object... arg2);
    ByteStringInterface toByteString(java.lang.Object arg0);
    MapFieldInterface internalGetMapField(int arg0);
    int getMemoizedSerializedSize();
    <V> void maybeSerializeBooleanEntryTo(CodedOutputStreamInterface arg0, java.util.Map<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3, boolean arg4) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.AbstractMessage.BuilderParent arg0);
    <V> void serializeLongMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Long, V> arg1, MapEntryInterface<java.lang.Long, V> arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.MessageLite getDefaultInstanceForType();
    java.lang.Object getField(FieldDescriptorInterface arg0);
    int getSerializedSize();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.EnumValueOptionsOrBuilder getOptionsOrBuilder();
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsMutable(boolean arg0);
//    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.EnumValueDescriptorProto> getParserForType();
    EnumValueDescriptorProtoInterface parseFrom(java.nio.ByteBuffer arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    ByteStringInterface getNameBytes();
    EnumValueDescriptorProtoInterface parseDelimitedFrom(java.io.InputStream arg0) throws java.io.IOException;
    java.lang.String getName();
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList newBooleanList();
//    BuilderInterface newBuilderForType();
    int hashCode();
    int hashMapField(java.lang.Object arg0);
    EnumValueDescriptorProtoInterface parseDelimitedFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    java.util.List<java.lang.String> findInitializationErrors();
    EnumValueOptionsInterface getOptions();
    boolean equals(java.lang.Object arg0);
    UninitializedMessageExceptionInterface newUninitializedMessageException();
    EnumValueDescriptorProtoInterface parseFrom(ByteStringInterface arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    boolean compareFields(java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.FloatList arg0);
//    BuilderInterface toBuilder();
    boolean compareBytes(java.lang.Object arg0, java.lang.Object arg1);
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFields();
    EnumValueDescriptorProtoInterface parseFrom(java.io.InputStream arg0) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.Message getDefaultInstanceForType();
    ByteStringInterface toByteString();
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList emptyLongList();
    void enableAlwaysUseFieldBuildersForTesting();
    int computeStringSizeNoTag(java.lang.Object arg0);
    <MessageType, T> ExtensionInterface<MessageType, T> checkNotLite(ExtensionLiteInterface<MessageType, T> arg0);
//    EnumValueDescriptorProtoInterface getDefaultInstanceForType();
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.Collection<? super T> arg1);
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    java.lang.String getInitializationErrorString();
    void writeStringNoTag(CodedOutputStreamInterface arg0, java.lang.Object arg1) throws java.io.IOException;
    boolean hasOptions();
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList newFloatList();
    java.lang.String toString();
    boolean parseUnknownFieldProto3(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    void checkByteStringIsUtf8(ByteStringInterface arg0) throws java.lang.IllegalArgumentException;
    EnumValueDescriptorProtoInterface parseFrom(CodedInputStreamInterface arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    <V> void serializeBooleanMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3) throws java.io.IOException;
//    BuilderInterface newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    boolean canUseUnsafe();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder toBuilder();
    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.EnumValueDescriptorProto> parser();
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.LongList arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList newIntList();
    int getRepeatedFieldCount(FieldDescriptorInterface arg0);
    int hashEnum(org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite arg0);
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.MessageLite> getParserForType();
    BuilderInterface newBuilder(EnumValueDescriptorProtoInterface arg0);
    EnumValueDescriptorProtoInterface parseFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    DescriptorInterface getDescriptor();
    java.lang.Object getFieldRaw(FieldDescriptorInterface arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList arg0);
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.List<? super T> arg1);
    <V> void serializeIntegerMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Integer, V> arg1, MapEntryInterface<java.lang.Integer, V> arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.IntList arg0);
    int computeStringSize(int arg0, java.lang.Object arg1);
    boolean hasName();
    int hashEnumList(java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite> arg0);
    java.util.Map convertMapEntryListToMap(java.util.List arg0);
    boolean isInitialized();
    java.lang.String getSerializingExceptionMessage(java.lang.String arg0);
    java.lang.Object writeReplace() throws java.io.ObjectStreamException;
    EnumValueDescriptorProtoInterface getDefaultInstance();
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.Message> getParserForType();
    void writeDelimitedTo(java.io.OutputStream arg0) throws java.io.IOException;
}