package org.apache.hadoop.hdfs.remoteProxies;

public interface EnumDescriptorProtoInterface {
    BuilderInterface toBuilder();
    <MessageType, T> ExtensionInterface<MessageType, T> checkNotLite(ExtensionLiteInterface<MessageType, T> arg0);
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    int getValueCount();
    java.lang.String toString();
    org.apache.hadoop.thirdparty.protobuf.ProtocolStringList getReservedNameList();
    void writeString(CodedOutputStreamInterface arg0, int arg1, java.lang.Object arg2) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.Message> getParserForType();
    boolean equals(java.lang.Object arg0);
    EnumDescriptorProtoInterface parseFrom(ByteStringInterface arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    MapFieldInterface internalGetMapField(int arg0);
    java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRangeOrBuilder> getReservedRangeOrBuilderList();
    void writeDelimitedTo(java.io.OutputStream arg0) throws java.io.IOException;
    FieldAccessorTableInterface internalGetFieldAccessorTable();
    int hashBoolean(boolean arg0);
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    EnumDescriptorProtoInterface parseFrom(ByteStringInterface arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    int getSerializedSize();
    EnumDescriptorProtoInterface parseDelimitedFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    boolean compareBytes(java.lang.Object arg0, java.lang.Object arg1);
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList newIntList();
    boolean compareMapField(java.lang.Object arg0, java.lang.Object arg1);
    org.apache.hadoop.thirdparty.protobuf.MessageLite getDefaultInstanceForType();
//    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.EnumDescriptorProto> getParserForType();
    BuilderInterface newBuilder();
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsMutable(boolean arg0);
    void makeExtensionsImmutable();
    int getMemoizedSerializedSize();
    java.lang.Object writeReplace() throws java.io.ObjectStreamException;
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.MessageLite> getParserForType();
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList emptyDoubleList();
    EnumValueDescriptorProtoInterface getValue(int arg0);
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFields();
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList emptyBooleanList();
    <V> void serializeBooleanMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3) throws java.io.IOException;
    <V> void serializeLongMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Long, V> arg1, MapEntryInterface<java.lang.Long, V> arg2, int arg3) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3> getParserForType();
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.EnumOptionsOrBuilder getOptionsOrBuilder();
    boolean parseUnknownFieldProto3(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.AbstractMessage.BuilderParent arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList emptyIntList();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList arg0);
    int hashLong(long arg0);
    <V> void serializeStringMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.String, V> arg1, MapEntryInterface<java.lang.String, V> arg2, int arg3) throws java.io.IOException;
    DescriptorInterface getDescriptorForType();
    java.util.List<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange> getReservedRangeList();
    int getRepeatedFieldCount(FieldDescriptorInterface arg0);
    java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.EnumValueDescriptorProtoOrBuilder> getValueOrBuilderList();
    int hashCode();
    UninitializedMessageExceptionInterface newUninitializedMessageException();
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.FloatList arg0);
    <K, V> void serializeMapTo(CodedOutputStreamInterface arg0, java.util.Map<K, V> arg1, MapEntryInterface<K, V> arg2, int arg3) throws java.io.IOException;
    int getReservedNameCount();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder toBuilder();
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList arg0);
    void writeTo(java.io.OutputStream arg0) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType();
    boolean hasOneof(OneofDescriptorInterface arg0);
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
    int hashEnum(org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite arg0);
    int getReservedRangeCount();
    EnumDescriptorProtoInterface parseFrom(CodedInputStreamInterface arg0) throws java.io.IOException;
    EnumDescriptorProtoInterface parseDelimitedFrom(java.io.InputStream arg0) throws java.io.IOException;
    ByteStringInterface toByteString();
    java.lang.String getName();
//    org.apache.hadoop.thirdparty.protobuf.Message getDefaultInstanceForType();
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.Collection<? super T> arg1);
//    BuilderInterface newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    EnumOptionsInterface getOptions();
    void setMemoizedSerializedSize(int arg0);
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRangeOrBuilder getReservedRangeOrBuilder(int arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList newFloatList();
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.EnumValueDescriptorProtoOrBuilder getValueOrBuilder(int arg0);
    boolean canUseUnsafe();
    java.lang.String getReservedName(int arg0);
    void enableAlwaysUseFieldBuildersForTesting();
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    FieldDescriptorInterface getOneofFieldDescriptor(OneofDescriptorInterface arg0);
    <V> void serializeIntegerMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Integer, V> arg1, MapEntryInterface<java.lang.Integer, V> arg2, int arg3) throws java.io.IOException;
    boolean hasOptions();
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList newBooleanList();
    int hashEnumList(java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite> arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList emptyLongList();
    java.lang.Object invokeOrDie(java.lang.reflect.Method arg0, java.lang.Object arg1, java.lang.Object... arg2);
    void writeStringNoTag(CodedOutputStreamInterface arg0, java.lang.Object arg1) throws java.io.IOException;
    EnumDescriptorProtoInterface parseFrom(java.nio.ByteBuffer arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    EnumDescriptorProtoInterface parseFrom(byte[] arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    void checkByteStringIsUtf8(ByteStringInterface arg0) throws java.lang.IllegalArgumentException;
    boolean compareFields(java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
//    EnumDescriptorProtoInterface getDefaultInstanceForType();
    <V> void maybeSerializeBooleanEntryTo(CodedOutputStreamInterface arg0, java.util.Map<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3, boolean arg4) throws java.io.IOException;
    java.lang.String getInitializationErrorString();
    BuilderInterface newBuilder(EnumDescriptorProtoInterface arg0);
    ByteStringInterface getReservedNameBytes(int arg0);
    boolean isInitialized();
    java.util.Map convertMapEntryListToMap(java.util.List arg0);
    boolean parseUnknownField(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    EnumDescriptorProtoInterface parseFrom(CodedInputStreamInterface arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList newLongList();
    UnknownFieldSetInterface getUnknownFields();
    java.lang.Object getRepeatedField(FieldDescriptorInterface arg0, int arg1);
    EnumDescriptorProtoInterface parseFrom(java.nio.ByteBuffer arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList emptyFloatList();
    int computeStringSizeNoTag(java.lang.Object arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList newDoubleList();
//    java.util.List<java.lang.String> getReservedNameList();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1) throws java.io.IOException;
    boolean hasName();
    ByteStringInterface getNameBytes();
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.LongList arg0);
//    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder newBuilderForType();
    java.lang.Object getFieldRaw(FieldDescriptorInterface arg0);
//    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder toBuilder();
    ByteStringInterface toByteString(java.lang.Object arg0);
    int hashFields(int arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    EnumDescriptorProtoInterface getDefaultInstance();
    EnumDescriptorProtoInterface parseFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    java.util.List<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.EnumValueDescriptorProto> getValueList();
//    BuilderInterface newBuilderForType();
    EnumDescriptorProtoInterface parseFrom(byte[] arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    java.lang.Object getField(FieldDescriptorInterface arg0);
    int computeStringSize(int arg0, java.lang.Object arg1);
    java.lang.reflect.Method getMethodOrDie(java.lang.Class arg0, java.lang.String arg1, java.lang.Class... arg2);
    void writeTo(CodedOutputStreamInterface arg0) throws java.io.IOException;
    java.lang.String getSerializingExceptionMessage(java.lang.String arg0);
    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.EnumDescriptorProto> parser();
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.List<? super T> arg1);
    int hashMapField(java.lang.Object arg0);
    DescriptorInterface getDescriptor();
    EnumDescriptorProtoInterface parseFrom(java.io.InputStream arg0) throws java.io.IOException;
    boolean hasField(FieldDescriptorInterface arg0);
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsRaw();
    java.util.List<java.lang.String> findInitializationErrors();
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.IntList arg0);
    EnumReservedRangeInterface getReservedRange(int arg0);
    byte[] toByteArray();
}