package org.apache.hadoop.hdfs.remoteProxies;

public interface ExtensionRangeOptionsInterface {
    <V> void serializeLongMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Long, V> arg1, MapEntryInterface<java.lang.Long, V> arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList emptyFloatList();
    void enableAlwaysUseFieldBuildersForTesting();
    void verifyContainingType(FieldDescriptorInterface arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList newDoubleList();
//    <Type> int getExtensionCount(ExtensionLiteInterface<MessageType, java.util.List<Type>> arg0);
    byte[] toByteArray();
//    <Type> Type getExtension(ExtensionLiteInterface<MessageType, Type> arg0);
    java.util.List<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOption> getUninterpretedOptionList();
    java.lang.Object getRepeatedField(FieldDescriptorInterface arg0, int arg1);
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    ExtensionRangeOptionsInterface parseFrom(ByteStringInterface arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    int hashBoolean(boolean arg0);
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    <V> void serializeStringMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.String, V> arg1, MapEntryInterface<java.lang.String, V> arg2, int arg3) throws java.io.IOException;
    FieldAccessorTableInterface internalGetFieldAccessorTable();
    ExtensionRangeOptionsInterface getDefaultInstance();
    ByteStringInterface toByteString(java.lang.Object arg0);
    void checkByteStringIsUtf8(ByteStringInterface arg0) throws java.lang.IllegalArgumentException;
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    ExtensionRangeOptionsInterface parseFrom(byte[] arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    java.util.Map convertMapEntryListToMap(java.util.List arg0);
    java.lang.Object writeReplace() throws java.io.ObjectStreamException;
    org.apache.hadoop.thirdparty.protobuf.Message.Builder toBuilder();
    UnknownFieldSetInterface getUnknownFields();
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getExtensionFields();
    ExtensionRangeOptionsInterface parseFrom(ByteStringInterface arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    ExtensionRangeOptionsInterface parseFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.List<? super T> arg1);
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFields();
    ExtensionRangeOptionsInterface parseFrom(CodedInputStreamInterface arg0) throws java.io.IOException;
    boolean parseUnknownField(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.ExtensionRangeOptions> getParserForType();
//    <Type> Type getExtension(ExtensionInterface<MessageType, Type> arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList newFloatList();
    ExtensionWriterInterface newExtensionWriter();
    boolean hasOneof(OneofDescriptorInterface arg0);
    java.lang.Object invokeOrDie(java.lang.reflect.Method arg0, java.lang.Object arg1, java.lang.Object... arg2);
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList newIntList();
    java.lang.Object getFieldRaw(FieldDescriptorInterface arg0);
    UninterpretedOptionInterface getUninterpretedOption(int arg0);
    java.lang.String getInitializationErrorString();
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList emptyBooleanList();
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.IntList arg0);
    java.lang.reflect.Method getMethodOrDie(java.lang.Class arg0, java.lang.String arg1, java.lang.Class... arg2);
    boolean compareFields(java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    void writeTo(java.io.OutputStream arg0) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.MessageLite> getParserForType();
    int computeStringSize(int arg0, java.lang.Object arg1);
    ExtensionRangeOptionsInterface parseFrom(java.nio.ByteBuffer arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList arg0);
//    <Type> Type getExtension(GeneratedExtensionInterface<MessageType, Type> arg0);
    ExtensionWriterInterface newMessageSetExtensionWriter();
    ExtensionRangeOptionsInterface parseFrom(java.io.InputStream arg0) throws java.io.IOException;
//    <Type> boolean hasExtension(GeneratedExtensionInterface<MessageType, Type> arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.FloatList arg0);
    java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOptionOrBuilder> getUninterpretedOptionOrBuilderList();
    void setMemoizedSerializedSize(int arg0);
    UninitializedMessageExceptionInterface newUninitializedMessageException();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
    <V> void maybeSerializeBooleanEntryTo(CodedOutputStreamInterface arg0, java.util.Map<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3, boolean arg4) throws java.io.IOException;
//    <Type> Type getExtension(ExtensionInterface<MessageType, java.util.List<Type>> arg0, int arg1);
    org.apache.hadoop.thirdparty.protobuf.MessageLite getDefaultInstanceForType();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1) throws java.io.IOException;
    <V> void serializeIntegerMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Integer, V> arg1, MapEntryInterface<java.lang.Integer, V> arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList newLongList();
    ExtensionRangeOptionsInterface parseFrom(java.nio.ByteBuffer arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    ExtensionRangeOptionsInterface parseFrom(byte[] arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    ExtensionRangeOptionsInterface parseDelimitedFrom(java.io.InputStream arg0) throws java.io.IOException;
    java.lang.Object getField(FieldDescriptorInterface arg0);
    boolean compareBytes(java.lang.Object arg0, java.lang.Object arg1);
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList emptyDoubleList();
//    void verifyExtensionContainingType(ExtensionInterface<MessageType, ?> arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList newBooleanList();
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.Collection<? super T> arg1);
    boolean isInitialized();
    boolean equals(java.lang.Object arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList emptyLongList();
    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.ExtensionRangeOptions> parser();
//    BuilderInterface newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    java.lang.String getSerializingExceptionMessage(java.lang.String arg0);
    int computeStringSizeNoTag(java.lang.Object arg0);
//    BuilderInterface toBuilder();
    int extensionsSerializedSize();
    BuilderInterface newBuilder(ExtensionRangeOptionsInterface arg0);
//    <Type> int getExtensionCount(GeneratedExtensionInterface<MessageType, java.util.List<Type>> arg0);
    BuilderInterface newBuilder();
    MapFieldInterface internalGetMapField(int arg0);
    boolean canUseUnsafe();
//    <Type> boolean hasExtension(ExtensionLiteInterface<MessageType, Type> arg0);
    boolean hasField(FieldDescriptorInterface arg0);
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.Message> getParserForType();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.AbstractMessage.BuilderParent arg0);
    int hashCode();
    int getSerializedSize();
    int hashEnumList(java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite> arg0);
    int hashMapField(java.lang.Object arg0);
    FieldDescriptorInterface getOneofFieldDescriptor(OneofDescriptorInterface arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList arg0);
    <K, V> void serializeMapTo(CodedOutputStreamInterface arg0, java.util.Map<K, V> arg1, MapEntryInterface<K, V> arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.LongList arg0);
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsRaw();
    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType();
//    <Type> Type getExtension(ExtensionLiteInterface<MessageType, java.util.List<Type>> arg0, int arg1);
//    <Type> int getExtensionCount(ExtensionInterface<MessageType, java.util.List<Type>> arg0);
    int getMemoizedSerializedSize();
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsMutable(boolean arg0);
    java.lang.String toString();
    ExtensionRangeOptionsInterface parseDelimitedFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
//    <Type> Type getExtension(GeneratedExtensionInterface<MessageType, java.util.List<Type>> arg0, int arg1);
    void writeStringNoTag(CodedOutputStreamInterface arg0, java.lang.Object arg1) throws java.io.IOException;
    java.util.List<java.lang.String> findInitializationErrors();
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList emptyIntList();
    int hashFields(int arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOptionOrBuilder getUninterpretedOptionOrBuilder(int arg0);
    int hashLong(long arg0);
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3> getParserForType();
//    <Type> boolean hasExtension(ExtensionInterface<MessageType, Type> arg0);
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    void writeString(CodedOutputStreamInterface arg0, int arg1, java.lang.Object arg2) throws java.io.IOException;
    DescriptorInterface getDescriptorForType();
//    BuilderInterface newBuilderForType();
    <V> void serializeBooleanMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder newBuilderForType();
    boolean parseUnknownFieldProto3(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    DescriptorInterface getDescriptor();
    int extensionsSerializedSizeAsMessageSet();
    int getRepeatedFieldCount(FieldDescriptorInterface arg0);
    int getUninterpretedOptionCount();
    int hashEnum(org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite arg0);
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
    void writeTo(CodedOutputStreamInterface arg0) throws java.io.IOException;
    ExtensionRangeOptionsInterface parseFrom(CodedInputStreamInterface arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.Message getDefaultInstanceForType();
    void makeExtensionsImmutable();
    void writeDelimitedTo(java.io.OutputStream arg0) throws java.io.IOException;
    boolean compareMapField(java.lang.Object arg0, java.lang.Object arg1);
//    ExtensionRangeOptionsInterface getDefaultInstanceForType();
    boolean extensionsAreInitialized();
    <MessageType, T> ExtensionInterface<MessageType, T> checkNotLite(ExtensionLiteInterface<MessageType, T> arg0);
    ByteStringInterface toByteString();
//    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder toBuilder();
}