package org.apache.hadoop.hdfs.remoteProxies;

public interface FieldDescriptorProtoInterface {
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFields();
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsRaw();
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList newBooleanList();
    boolean compareFields(java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
    BuilderInterface newBuilder(FieldDescriptorProtoInterface arg0);
    boolean compareMapField(java.lang.Object arg0, java.lang.Object arg1);
    int getOneofIndex();
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList newFloatList();
    int getSerializedSize();
    void makeExtensionsImmutable();
    ByteStringInterface toByteString();
    <V> void maybeSerializeBooleanEntryTo(CodedOutputStreamInterface arg0, java.util.Map<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3, boolean arg4) throws java.io.IOException;
    FieldDescriptorProtoInterface parseFrom(CodedInputStreamInterface arg0) throws java.io.IOException;
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    void enableAlwaysUseFieldBuildersForTesting();
    java.lang.String getDefaultValue();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsMutable(boolean arg0);
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.AbstractMessage.BuilderParent arg0);
    BuilderInterface newBuilder();
    ByteStringInterface getNameBytes();
    java.lang.reflect.Method getMethodOrDie(java.lang.Class arg0, java.lang.String arg1, java.lang.Class... arg2);
    FieldDescriptorProtoInterface parseFrom(java.io.InputStream arg0) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.FloatList arg0);
    ByteStringInterface getDefaultValueBytes();
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.List<? super T> arg1);
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList emptyFloatList();
    void setMemoizedSerializedSize(int arg0);
    FieldDescriptorProtoInterface parseFrom(byte[] arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    BuilderInterface toBuilder();
    <V> void serializeStringMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.String, V> arg1, MapEntryInterface<java.lang.String, V> arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType();
    void writeStringNoTag(CodedOutputStreamInterface arg0, java.lang.Object arg1) throws java.io.IOException;
    int computeStringSizeNoTag(java.lang.Object arg0);
    DescriptorInterface getDescriptorForType();
    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3> getParserForType();
    FieldDescriptorProtoInterface parseFrom(CodedInputStreamInterface arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    void writeString(CodedOutputStreamInterface arg0, int arg1, java.lang.Object arg2) throws java.io.IOException;
    ByteStringInterface toByteString(java.lang.Object arg0);
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.FieldDescriptorProto.Label getLabel();
    void checkByteStringIsUtf8(ByteStringInterface arg0) throws java.lang.IllegalArgumentException;
    boolean hasField(FieldDescriptorInterface arg0);
    byte[] toByteArray();
    boolean isInitialized();
    int hashEnumList(java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite> arg0);
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.Message> getParserForType();
    FieldDescriptorProtoInterface parseDelimitedFrom(java.io.InputStream arg0) throws java.io.IOException;
    FieldDescriptorProtoInterface parseDelimitedFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    int getNumber();
//    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder toBuilder();
    FieldDescriptorProtoInterface parseFrom(java.nio.ByteBuffer arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
//    BuilderInterface newBuilderForType();
//    BuilderInterface newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    boolean hasLabel();
    boolean hasTypeName();
    UninitializedMessageExceptionInterface newUninitializedMessageException();
    ByteStringInterface getExtendeeBytes();
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList arg0);
    FieldDescriptorProtoInterface parseFrom(ByteStringInterface arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    java.util.Map convertMapEntryListToMap(java.util.List arg0);
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.MessageLite> getParserForType();
    boolean parseUnknownField(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    int hashFields(int arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    int hashCode();
    <V> void serializeLongMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Long, V> arg1, MapEntryInterface<java.lang.Long, V> arg2, int arg3) throws java.io.IOException;
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    int hashBoolean(boolean arg0);
    int getMemoizedSerializedSize();
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1) throws java.io.IOException;
    void writeDelimitedTo(java.io.OutputStream arg0) throws java.io.IOException;
    FieldDescriptorProtoInterface parseFrom(byte[] arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList newLongList();
    FieldDescriptorProtoInterface parseFrom(ByteStringInterface arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    boolean hasOneof(OneofDescriptorInterface arg0);
    int computeStringSize(int arg0, java.lang.Object arg1);
    int hashEnum(org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite arg0);
    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.FieldDescriptorProto> parser();
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList newIntList();
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.Collection<? super T> arg1);
    java.lang.Object writeReplace() throws java.io.ObjectStreamException;
//    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder newBuilderForType();
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList emptyBooleanList();
    java.lang.Object getRepeatedField(FieldDescriptorInterface arg0, int arg1);
    boolean hasName();
    boolean compareBytes(java.lang.Object arg0, java.lang.Object arg1);
//    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.FieldDescriptorProto> getParserForType();
    boolean canUseUnsafe();
    FieldOptionsInterface getOptions();
    java.lang.String getName();
    boolean parseUnknownFieldProto3(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    java.lang.String getInitializationErrorString();
    org.apache.hadoop.thirdparty.protobuf.MessageLite getDefaultInstanceForType();
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList emptyIntList();
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList arg0);
    java.lang.String toString();
    java.lang.Object getFieldRaw(FieldDescriptorInterface arg0);
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.FieldOptionsOrBuilder getOptionsOrBuilder();
    boolean hasNumber();
    void writeTo(CodedOutputStreamInterface arg0) throws java.io.IOException;
    boolean hasOneofIndex();
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
    FieldAccessorTableInterface internalGetFieldAccessorTable();
    <V> void serializeBooleanMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder toBuilder();
    DescriptorInterface getDescriptor();
    <MessageType, T> ExtensionInterface<MessageType, T> checkNotLite(ExtensionLiteInterface<MessageType, T> arg0);
    boolean hasOptions();
    boolean hasType();
    ByteStringInterface getTypeNameBytes();
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.LongList arg0);
    java.lang.Object getField(FieldDescriptorInterface arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList emptyLongList();
    ByteStringInterface getJsonNameBytes();
    <V> void serializeIntegerMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Integer, V> arg1, MapEntryInterface<java.lang.Integer, V> arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.FieldDescriptorProto.Type getType();
    FieldDescriptorProtoInterface getDefaultInstance();
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.IntList arg0);
    java.lang.String getExtendee();
//    FieldDescriptorProtoInterface getDefaultInstanceForType();
    boolean hasDefaultValue();
    UnknownFieldSetInterface getUnknownFields();
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList emptyDoubleList();
    java.util.List<java.lang.String> findInitializationErrors();
//    org.apache.hadoop.thirdparty.protobuf.Message getDefaultInstanceForType();
    boolean hasJsonName();
    int hashLong(long arg0);
    FieldDescriptorProtoInterface parseFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList newDoubleList();
    <K, V> void serializeMapTo(CodedOutputStreamInterface arg0, java.util.Map<K, V> arg1, MapEntryInterface<K, V> arg2, int arg3) throws java.io.IOException;
    java.lang.String getSerializingExceptionMessage(java.lang.String arg0);
    java.lang.String getJsonName();
    MapFieldInterface internalGetMapField(int arg0);
    java.lang.Object invokeOrDie(java.lang.reflect.Method arg0, java.lang.Object arg1, java.lang.Object... arg2);
    boolean hasExtendee();
    int hashMapField(java.lang.Object arg0);
    int getRepeatedFieldCount(FieldDescriptorInterface arg0);
    FieldDescriptorProtoInterface parseFrom(java.nio.ByteBuffer arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    FieldDescriptorInterface getOneofFieldDescriptor(OneofDescriptorInterface arg0);
    void writeTo(java.io.OutputStream arg0) throws java.io.IOException;
    boolean equals(java.lang.Object arg0);
    java.lang.String getTypeName();
}