package org.apache.hadoop.hdfs.remoteProxies;

public interface FileOptionsInterface {
    boolean hasCcEnableArenas();
    java.lang.String getJavaOuterClassname();
    FileOptionsInterface parseFrom(byte[] arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.FileOptions.OptimizeMode getOptimizeFor();
    java.lang.String getPhpClassPrefix();
    java.lang.String toString();
    int hashBoolean(boolean arg0);
    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.MessageLite> getParserForType();
//    <Type> int getExtensionCount(GeneratedExtensionInterface<MessageType, java.util.List<Type>> arg0);
    boolean parseUnknownFieldProto3(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    boolean equals(java.lang.Object arg0);
    int getMemoizedSerializedSize();
    FileOptionsInterface parseFrom(java.io.InputStream arg0) throws java.io.IOException;
    FileOptionsInterface getDefaultInstance();
    boolean extensionsAreInitialized();
    boolean hasOneof(OneofDescriptorInterface arg0);
    boolean hasJavaMultipleFiles();
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList newBooleanList();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder toBuilder();
    <V> void serializeBooleanMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3) throws java.io.IOException;
    java.lang.String getPhpMetadataNamespace();
    ByteStringInterface getPhpNamespaceBytes();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    BuilderInterface newBuilder();
    java.lang.String getInitializationErrorString();
    java.lang.Object getFieldRaw(FieldDescriptorInterface arg0);
    boolean getCcGenericServices();
    java.lang.Object writeReplace() throws java.io.ObjectStreamException;
    boolean hasJavaPackage();
    boolean hasCsharpNamespace();
    DescriptorInterface getDescriptor();
    <V> void serializeIntegerMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Integer, V> arg1, MapEntryInterface<java.lang.Integer, V> arg2, int arg3) throws java.io.IOException;
    FileOptionsInterface getDefaultInstanceForType();
    boolean getPyGenericServices();
    void checkByteStringIsUtf8(ByteStringInterface arg0) throws java.lang.IllegalArgumentException;
    ExtensionWriterInterface newExtensionWriter();
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.IntList arg0);
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.Message> getParserForType();
    boolean hasPhpNamespace();
    java.util.List<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOption> getUninterpretedOptionList();
    void setMemoizedSerializedSize(int arg0);
    boolean getJavaGenerateEqualsAndHash();
    boolean isInitialized();
    int getRepeatedFieldCount(FieldDescriptorInterface arg0);
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder newBuilderForType();
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList newFloatList();
    boolean compareMapField(java.lang.Object arg0, java.lang.Object arg1);
    boolean hasJavaGenerateEqualsAndHash();
    void writeString(CodedOutputStreamInterface arg0, int arg1, java.lang.Object arg2) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList emptyDoubleList();
    boolean hasPhpClassPrefix();
    boolean hasPhpGenericServices();
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList arg0);
    DescriptorInterface getDescriptorForType();
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList emptyBooleanList();
    int getUninterpretedOptionCount();
    FileOptionsInterface parseFrom(java.nio.ByteBuffer arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    boolean hasOptimizeFor();
    ByteStringInterface getPhpClassPrefixBytes();
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.List<? super T> arg1);
    java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOptionOrBuilder> getUninterpretedOptionOrBuilderList();
    java.util.Map convertMapEntryListToMap(java.util.List arg0);
    boolean hasGoPackage();
    boolean hasRubyPackage();
    <MessageType, T> ExtensionInterface<MessageType, T> checkNotLite(ExtensionLiteInterface<MessageType, T> arg0);
    java.lang.Object invokeOrDie(java.lang.reflect.Method arg0, java.lang.Object arg1, java.lang.Object... arg2);
    int hashCode();
    FileOptionsInterface parseFrom(CodedInputStreamInterface arg0) throws java.io.IOException;
    void enableAlwaysUseFieldBuildersForTesting();
    java.lang.reflect.Method getMethodOrDie(java.lang.Class arg0, java.lang.String arg1, java.lang.Class... arg2);
    MapFieldInterface internalGetMapField(int arg0);
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
//    BuilderInterface toBuilder();
    UninterpretedOptionInterface getUninterpretedOption(int arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.LongList arg0);
    void writeStringNoTag(CodedOutputStreamInterface arg0, java.lang.Object arg1) throws java.io.IOException;
    FieldAccessorTableInterface internalGetFieldAccessorTable();
//    <Type> Type getExtension(ExtensionInterface<MessageType, Type> arg0);
    boolean hasSwiftPrefix();
//    BuilderInterface newBuilderForType();
    FieldDescriptorInterface getOneofFieldDescriptor(OneofDescriptorInterface arg0);
    ExtensionWriterInterface newMessageSetExtensionWriter();
    FileOptionsInterface parseDelimitedFrom(java.io.InputStream arg0) throws java.io.IOException;
    boolean canUseUnsafe();
    void writeTo(java.io.OutputStream arg0) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
//    org.apache.hadoop.thirdparty.protobuf.MessageLite getDefaultInstanceForType();
    int getSerializedSize();
    <K, V> void serializeMapTo(CodedOutputStreamInterface arg0, java.util.Map<K, V> arg1, MapEntryInterface<K, V> arg2, int arg3) throws java.io.IOException;
//    <Type> boolean hasExtension(ExtensionInterface<MessageType, Type> arg0);
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.AbstractMessage.BuilderParent arg0);
    boolean hasDeprecated();
    java.lang.String getGoPackage();
    boolean hasJavaGenericServices();
    UnknownFieldSetInterface getUnknownFields();
    int extensionsSerializedSizeAsMessageSet();
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsRaw();
    java.lang.String getCsharpNamespace();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder toBuilder();
    boolean getJavaGenericServices();
    boolean compareBytes(java.lang.Object arg0, java.lang.Object arg1);
    boolean getPhpGenericServices();
    ByteStringInterface getRubyPackageBytes();
    boolean compareFields(java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    FileOptionsInterface parseFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    ByteStringInterface getSwiftPrefixBytes();
    boolean getDeprecated();
    ByteStringInterface getObjcClassPrefixBytes();
    boolean hasPyGenericServices();
    BuilderInterface newBuilder(FileOptionsInterface arg0);
//    org.apache.hadoop.thirdparty.protobuf.Message getDefaultInstanceForType();
    boolean hasObjcClassPrefix();
    boolean hasPhpMetadataNamespace();
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList emptyIntList();
    void makeExtensionsImmutable();
    java.lang.Object getRepeatedField(FieldDescriptorInterface arg0, int arg1);
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.FloatList arg0);
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
//    <Type> Type getExtension(GeneratedExtensionInterface<MessageType, Type> arg0);
    UninitializedMessageExceptionInterface newUninitializedMessageException();
    <V> void serializeLongMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Long, V> arg1, MapEntryInterface<java.lang.Long, V> arg2, int arg3) throws java.io.IOException;
    boolean getJavaMultipleFiles();
//    <Type> int getExtensionCount(ExtensionLiteInterface<MessageType, java.util.List<Type>> arg0);
    void writeDelimitedTo(java.io.OutputStream arg0) throws java.io.IOException;
    ByteStringInterface getJavaOuterClassnameBytes();
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList emptyLongList();
    java.lang.String getObjcClassPrefix();
    FileOptionsInterface parseDelimitedFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    boolean getCcEnableArenas();
    <V> void serializeStringMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.String, V> arg1, MapEntryInterface<java.lang.String, V> arg2, int arg3) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3> getParserForType();
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
//    <Type> boolean hasExtension(GeneratedExtensionInterface<MessageType, Type> arg0);
    int hashMapField(java.lang.Object arg0);
    void verifyContainingType(FieldDescriptorInterface arg0);
    boolean parseUnknownField(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType();
//    <Type> Type getExtension(ExtensionInterface<MessageType, java.util.List<Type>> arg0, int arg1);
//    void verifyExtensionContainingType(ExtensionInterface<MessageType, ?> arg0);
    ByteStringInterface getGoPackageBytes();
    byte[] toByteArray();
    int hashEnumList(java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite> arg0);
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsMutable(boolean arg0);
    java.lang.Object getField(FieldDescriptorInterface arg0);
    int hashEnum(org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite arg0);
    FileOptionsInterface parseFrom(ByteStringInterface arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
//    <Type> boolean hasExtension(ExtensionLiteInterface<MessageType, Type> arg0);
//    BuilderInterface newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    int hashLong(long arg0);
    ByteStringInterface getPhpMetadataNamespaceBytes();
    boolean hasCcGenericServices();
//    <Type> Type getExtension(GeneratedExtensionInterface<MessageType, java.util.List<Type>> arg0, int arg1);
    void writeTo(CodedOutputStreamInterface arg0) throws java.io.IOException;
    boolean getJavaStringCheckUtf8();
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList newDoubleList();
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList arg0);
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.Collection<? super T> arg1);
    boolean hasJavaOuterClassname();
    boolean hasField(FieldDescriptorInterface arg0);
    java.lang.String getRubyPackage();
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOptionOrBuilder getUninterpretedOptionOrBuilder(int arg0);
    ByteStringInterface getCsharpNamespaceBytes();
    int extensionsSerializedSize();
    java.lang.String getPhpNamespace();
//    <Type> Type getExtension(ExtensionLiteInterface<MessageType, java.util.List<Type>> arg0, int arg1);
    java.lang.String getJavaPackage();
    FileOptionsInterface parseFrom(java.nio.ByteBuffer arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    FileOptionsInterface parseFrom(byte[] arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    java.lang.String getSerializingExceptionMessage(java.lang.String arg0);
    boolean hasJavaStringCheckUtf8();
    int hashFields(int arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    FileOptionsInterface parseFrom(CodedInputStreamInterface arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFields();
    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.FileOptions> parser();
    FileOptionsInterface parseFrom(ByteStringInterface arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
//    <Type> Type getExtension(ExtensionLiteInterface<MessageType, Type> arg0);
//    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.FileOptions> getParserForType();
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList newLongList();
    int computeStringSize(int arg0, java.lang.Object arg1);
    java.lang.String getSwiftPrefix();
    <V> void maybeSerializeBooleanEntryTo(CodedOutputStreamInterface arg0, java.util.Map<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3, boolean arg4) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList newIntList();
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList emptyFloatList();
    int computeStringSizeNoTag(java.lang.Object arg0);
    ByteStringInterface toByteString();
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getExtensionFields();
    ByteStringInterface toByteString(java.lang.Object arg0);
    ByteStringInterface getJavaPackageBytes();
//    <Type> int getExtensionCount(ExtensionInterface<MessageType, java.util.List<Type>> arg0);
    java.util.List<java.lang.String> findInitializationErrors();
}