package org.apache.hadoop.hdfs.remoteProxies;

public interface FileDescriptorProtoInterface {
    ByteStringInterface getPackageBytes();
    FileDescriptorProtoInterface parseFrom(CodedInputStreamInterface arg0) throws java.io.IOException;
    int getEnumTypeCount();
    int getExtensionCount();
    BuilderInterface newBuilder();
    ServiceDescriptorProtoInterface getService(int arg0);
    FileDescriptorProtoInterface parseFrom(ByteStringInterface arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    <V> void serializeStringMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.String, V> arg1, MapEntryInterface<java.lang.String, V> arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Message getDefaultInstanceForType();
    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.Message> getParserForType();
    java.lang.String toString();
    java.util.List<java.lang.Integer> getWeakDependencyList();
    boolean compareMapField(java.lang.Object arg0, java.lang.Object arg1);
    FileDescriptorProtoInterface parseFrom(java.io.InputStream arg0) throws java.io.IOException;
    FileDescriptorProtoInterface parseDelimitedFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    FileDescriptorProtoInterface parseFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    FieldDescriptorProtoInterface getExtension(int arg0);
    int hashLong(long arg0);
    java.lang.String getPackage();
    <V> void serializeBooleanMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3) throws java.io.IOException;
    int hashMapField(java.lang.Object arg0);
    ByteStringInterface getNameBytes();
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList emptyLongList();
    org.apache.hadoop.thirdparty.protobuf.Message.Builder toBuilder();
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.MessageLite> getParserForType();
    int getMessageTypeCount();
    void writeStringNoTag(CodedOutputStreamInterface arg0, java.lang.Object arg1) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder newBuilderForType();
    <V> void serializeLongMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Long, V> arg1, MapEntryInterface<java.lang.Long, V> arg2, int arg3) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3> getParserForType();
    void enableAlwaysUseFieldBuildersForTesting();
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList arg0);
    byte[] toByteArray();
    boolean equals(java.lang.Object arg0);
    FileDescriptorProtoInterface parseFrom(java.nio.ByteBuffer arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList newIntList();
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList arg0);
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.EnumDescriptorProtoOrBuilder getEnumTypeOrBuilder(int arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList newFloatList();
    <MessageType, T> ExtensionInterface<MessageType, T> checkNotLite(ExtensionLiteInterface<MessageType, T> arg0);
    boolean isInitialized();
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList emptyBooleanList();
    java.util.List<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.FieldDescriptorProto> getExtensionList();
    boolean hasSyntax();
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList newDoubleList();
    ByteStringInterface getDependencyBytes(int arg0);
    void makeExtensionsImmutable();
    DescriptorInterface getDescriptor();
    java.util.List<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.EnumDescriptorProto> getEnumTypeList();
    void writeDelimitedTo(java.io.OutputStream arg0) throws java.io.IOException;
//    BuilderInterface newBuilderForType();
    ByteStringInterface toByteString();
    int computeStringSizeNoTag(java.lang.Object arg0);
    int hashEnum(org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite arg0);
    FileOptionsInterface getOptions();
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.SourceCodeInfoOrBuilder getSourceCodeInfoOrBuilder();
    java.lang.String getInitializationErrorString();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList emptyIntList();
    java.lang.Object getFieldRaw(FieldDescriptorInterface arg0);
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.FloatList arg0);
    java.util.List<java.lang.Integer> getPublicDependencyList();
//    BuilderInterface toBuilder();
    void setMemoizedSerializedSize(int arg0);
    int getSerializedSize();
    FileDescriptorProtoInterface parseFrom(java.nio.ByteBuffer arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList newBooleanList();
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsMutable(boolean arg0);
    int getPublicDependency(int arg0);
//    BuilderInterface newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    java.util.List<java.lang.String> findInitializationErrors();
    java.lang.reflect.Method getMethodOrDie(java.lang.Class arg0, java.lang.String arg1, java.lang.Class... arg2);
    java.util.List<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.ServiceDescriptorProto> getServiceList();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType();
    java.lang.String getName();
    <K, V> void serializeMapTo(CodedOutputStreamInterface arg0, java.util.Map<K, V> arg1, MapEntryInterface<K, V> arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.ServiceDescriptorProtoOrBuilder getServiceOrBuilder(int arg0);
    int hashFields(int arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    java.lang.Object getRepeatedField(FieldDescriptorInterface arg0, int arg1);
    MapFieldInterface internalGetMapField(int arg0);
    int hashBoolean(boolean arg0);
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsRaw();
    int computeStringSize(int arg0, java.lang.Object arg1);
    boolean compareBytes(java.lang.Object arg0, java.lang.Object arg1);
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.List<? super T> arg1);
    java.util.Map convertMapEntryListToMap(java.util.List arg0);
    boolean hasSourceCodeInfo();
    ByteStringInterface getSyntaxBytes();
    boolean canUseUnsafe();
    DescriptorInterface getDescriptorForType();
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList newLongList();
    int hashCode();
    java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.EnumDescriptorProtoOrBuilder> getEnumTypeOrBuilderList();
    java.lang.Object getField(FieldDescriptorInterface arg0);
    BuilderInterface newBuilder(FileDescriptorProtoInterface arg0);
    EnumDescriptorProtoInterface getEnumType(int arg0);
//    FileDescriptorProtoInterface getDefaultInstanceForType();
    int hashEnumList(java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite> arg0);
//    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder toBuilder();
//    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.FileDescriptorProto> getParserForType();
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.LongList arg0);
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.AbstractMessage.BuilderParent arg0);
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.FileOptionsOrBuilder getOptionsOrBuilder();
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.DescriptorProtoOrBuilder getMessageTypeOrBuilder(int arg0);
    UninitializedMessageExceptionInterface newUninitializedMessageException();
    FileDescriptorProtoInterface getDefaultInstance();
    FileDescriptorProtoInterface parseFrom(byte[] arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    SourceCodeInfoInterface getSourceCodeInfo();
    boolean hasPackage();
    FieldDescriptorInterface getOneofFieldDescriptor(OneofDescriptorInterface arg0);
    FieldAccessorTableInterface internalGetFieldAccessorTable();
    UnknownFieldSetInterface getUnknownFields();
    boolean hasOneof(OneofDescriptorInterface arg0);
    boolean compareFields(java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    FileDescriptorProtoInterface parseFrom(ByteStringInterface arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    int getPublicDependencyCount();
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.FieldDescriptorProtoOrBuilder getExtensionOrBuilder(int arg0);
    int getWeakDependency(int arg0);
    java.lang.Object invokeOrDie(java.lang.reflect.Method arg0, java.lang.Object arg1, java.lang.Object... arg2);
    java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.ServiceDescriptorProtoOrBuilder> getServiceOrBuilderList();
    boolean hasOptions();
    java.lang.String getDependency(int arg0);
    boolean hasField(FieldDescriptorInterface arg0);
    org.apache.hadoop.thirdparty.protobuf.ProtocolStringList getDependencyList();
    ByteStringInterface toByteString(java.lang.Object arg0);
    void writeTo(java.io.OutputStream arg0) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.IntList arg0);
    java.util.List<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.DescriptorProto> getMessageTypeList();
    java.lang.String getSerializingExceptionMessage(java.lang.String arg0);
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
    boolean hasName();
    java.lang.Object writeReplace() throws java.io.ObjectStreamException;
    java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.DescriptorProtoOrBuilder> getMessageTypeOrBuilderList();
    int getDependencyCount();
    FileDescriptorProtoInterface parseFrom(byte[] arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    void writeString(CodedOutputStreamInterface arg0, int arg1, java.lang.Object arg2) throws java.io.IOException;
    int getRepeatedFieldCount(FieldDescriptorInterface arg0);
    DescriptorProtoInterface getMessageType(int arg0);
    java.lang.String getSyntax();
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList emptyDoubleList();
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.Collection<? super T> arg1);
//    org.apache.hadoop.thirdparty.protobuf.MessageLite getDefaultInstanceForType();
    int getServiceCount();
    boolean parseUnknownField(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList emptyFloatList();
//    java.util.List<java.lang.String> getDependencyList();
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFields();
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    void checkByteStringIsUtf8(ByteStringInterface arg0) throws java.lang.IllegalArgumentException;
    int getWeakDependencyCount();
    java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.FieldDescriptorProtoOrBuilder> getExtensionOrBuilderList();
    <V> void serializeIntegerMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Integer, V> arg1, MapEntryInterface<java.lang.Integer, V> arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.FileDescriptorProto> parser();
    FileDescriptorProtoInterface parseDelimitedFrom(java.io.InputStream arg0) throws java.io.IOException;
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    boolean parseUnknownFieldProto3(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    void writeTo(CodedOutputStreamInterface arg0) throws java.io.IOException;
    int getMemoizedSerializedSize();
    FileDescriptorProtoInterface parseFrom(CodedInputStreamInterface arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    <V> void maybeSerializeBooleanEntryTo(CodedOutputStreamInterface arg0, java.util.Map<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3, boolean arg4) throws java.io.IOException;
}