package org.apache.hadoop.hdfs.remoteProxies;

public interface FileSystemInterface {
    org.apache.hadoop.fs.PathHandle getPathHandle(FileStatusInterface arg0, org.apache.hadoop.fs.Options.HandleOpt... arg1);
    PathInterface createSnapshot(PathInterface arg0, java.lang.String arg1) throws java.io.IOException;
    FSDataInputStreamInterface open(PathInterface arg0, int arg1) throws java.io.IOException;
    short getDefaultReplication(PathInterface arg0);
    void processDeleteOnExit();
    FSDataOutputStreamInterface create(PathInterface arg0) throws java.io.IOException;
    int cacheSize();
    void setQuota(PathInterface arg0, long arg1, long arg2) throws java.io.IOException;
    long getUsed(PathInterface arg0) throws java.io.IOException;
    void addFileSystemForTesting(java.net.URI arg0, ConfigurationInterface arg1, FileSystemInterface arg2) throws java.io.IOException;
    org.apache.hadoop.fs.FutureDataInputStreamBuilder openFile(org.apache.hadoop.fs.PathHandle arg0) throws java.io.IOException, java.lang.UnsupportedOperationException;
    void completeLocalOutput(PathInterface arg0, PathInterface arg1) throws java.io.IOException;
    FSDataOutputStreamInterface create(FileSystemInterface arg0, PathInterface arg1, FsPermissionInterface arg2) throws java.io.IOException;
    FsServerDefaultsInterface getServerDefaults(PathInterface arg0) throws java.io.IOException;
    boolean deleteOnExit(PathInterface arg0) throws java.io.IOException;
    ContentSummaryInterface getContentSummary(PathInterface arg0) throws java.io.IOException;
    FSDataOutputStreamInterface primitiveCreate(PathInterface arg0, FsPermissionInterface arg1, java.util.EnumSet<org.apache.hadoop.fs.CreateFlag> arg2, int arg3, short arg4, long arg5, org.apache.hadoop.util.Progressable arg6, ChecksumOptInterface arg7) throws java.io.IOException;
    void closeAllForUGI(UserGroupInformationInterface arg0) throws java.io.IOException;
    FSDataOutputStreamInterface create(PathInterface arg0, org.apache.hadoop.util.Progressable arg1) throws java.io.IOException;
    FsStatusInterface getStatus() throws java.io.IOException;
    void checkAccessPermissions(FileStatusInterface arg0, org.apache.hadoop.fs.permission.FsAction arg1) throws org.apache.hadoop.security.AccessControlException, java.io.IOException;
    void copyFromLocalFile(boolean arg0, PathInterface arg1, PathInterface arg2) throws java.io.IOException;
    long getDefaultBlockSize();
    void access(PathInterface arg0, org.apache.hadoop.fs.permission.FsAction arg1) throws org.apache.hadoop.security.AccessControlException, java.io.FileNotFoundException, java.io.IOException;
    java.lang.String getCanonicalServiceName();
    boolean mkdirs(PathInterface arg0) throws java.io.IOException;
    void rename(PathInterface arg0, PathInterface arg1, org.apache.hadoop.fs.Options.Rename... arg2) throws java.io.IOException;
    FSDataOutputStreamBuilderInterface appendFile(PathInterface arg0);
    void msync() throws java.io.IOException, java.lang.UnsupportedOperationException;
    FileSystemInterface getFSofPath(PathInterface arg0, ConfigurationInterface arg1) throws org.apache.hadoop.fs.UnsupportedFileSystemException, java.io.IOException;
    boolean createNewFile(PathInterface arg0) throws java.io.IOException;
    java.util.Collection<? extends org.apache.hadoop.fs.BlockStoragePolicySpi> getAllStoragePolicies() throws java.io.IOException;
    void moveToLocalFile(PathInterface arg0, PathInterface arg1) throws java.io.IOException;
    FileSystemInterface[] getChildFileSystems();
    FSDataOutputStreamInterface create(PathInterface arg0, short arg1) throws java.io.IOException;
    org.apache.hadoop.fs.PathHandle createPathHandle(FileStatusInterface arg0, org.apache.hadoop.fs.Options.HandleOpt... arg1);
    void removeXAttr(PathInterface arg0, java.lang.String arg1) throws java.io.IOException;
    void setQuotaByStorageType(PathInterface arg0, org.apache.hadoop.fs.StorageType arg1, long arg2) throws java.io.IOException;
    void renameSnapshot(PathInterface arg0, java.lang.String arg1, java.lang.String arg2) throws java.io.IOException;
    void setTimes(PathInterface arg0, long arg1, long arg2) throws java.io.IOException;
    LocalFileSystemInterface getLocal(ConfigurationInterface arg0) throws java.io.IOException;
    FSDataOutputStreamBuilderInterface createDataOutputStreamBuilder(FileSystemInterface arg0, PathInterface arg1);
    void debugLogFileSystemClose(java.lang.String arg0, java.lang.String arg1);
    FileSystemInterface get(java.net.URI arg0, ConfigurationInterface arg1, java.lang.String arg2) throws java.io.IOException, java.lang.InterruptedException;
    FSDataOutputStreamInterface append(PathInterface arg0) throws java.io.IOException;
    byte[] getXAttr(PathInterface arg0, java.lang.String arg1) throws java.io.IOException;
    long getBlockSize(PathInterface arg0) throws java.io.IOException;
    void removeFileSystemForTesting(java.net.URI arg0, ConfigurationInterface arg1, FileSystemInterface arg2) throws java.io.IOException;
    org.apache.hadoop.fs.RemoteIterator<org.apache.hadoop.fs.FileStatus> listStatusIterator(PathInterface arg0) throws java.io.FileNotFoundException, java.io.IOException;
    org.apache.hadoop.fs.RemoteIterator<org.apache.hadoop.fs.LocatedFileStatus> listFiles(PathInterface arg0, boolean arg1) throws java.io.FileNotFoundException, java.io.IOException;
    boolean mkdirs(PathInterface arg0, FsPermissionInterface arg1) throws java.io.IOException;
    void setXAttr(PathInterface arg0, java.lang.String arg1, byte[] arg2, java.util.EnumSet<org.apache.hadoop.fs.XAttrSetFlag> arg3) throws java.io.IOException;
    java.util.List<java.lang.String> listXAttrs(PathInterface arg0) throws java.io.IOException;
    TokenInterface<?> getDelegationToken(java.lang.String arg0) throws java.io.IOException;
    void copyToLocalFile(boolean arg0, PathInterface arg1, PathInterface arg2, boolean arg3) throws java.io.IOException;
    long getLength(PathInterface arg0) throws java.io.IOException;
    void deleteSnapshot(PathInterface arg0, java.lang.String arg1) throws java.io.IOException;
    void copyFromLocalFile(boolean arg0, boolean arg1, PathInterface arg2, PathInterface arg3) throws java.io.IOException;
    FsStatusInterface getStatus(PathInterface arg0) throws java.io.IOException;
    boolean exists(PathInterface arg0) throws java.io.IOException;
    FileStatusInterface[] listStatus(PathInterface arg0, org.apache.hadoop.fs.PathFilter arg1) throws java.io.FileNotFoundException, java.io.IOException;
    int getDefaultPort();
    void copyFromLocalFile(boolean arg0, boolean arg1, PathInterface[] arg2, PathInterface arg3) throws java.io.IOException;
    boolean mkdirs(FileSystemInterface arg0, PathInterface arg1, FsPermissionInterface arg2) throws java.io.IOException;
    boolean primitiveMkdir(PathInterface arg0, FsPermissionInterface arg1) throws java.io.IOException;
    FSDataInputStreamInterface open(PathInterface arg0) throws java.io.IOException;
    FSDataOutputStreamInterface createNonRecursive(PathInterface arg0, FsPermissionInterface arg1, boolean arg2, int arg3, short arg4, long arg5, org.apache.hadoop.util.Progressable arg6) throws java.io.IOException;
    void checkPath(PathInterface arg0);
    BlockLocationInterface[] getFileBlockLocations(PathInterface arg0, long arg1, long arg2) throws java.io.IOException;
    org.apache.hadoop.fs.BlockStoragePolicySpi getStoragePolicy(PathInterface arg0) throws java.io.IOException;
    LocalFileSystemInterface newInstanceLocal(ConfigurationInterface arg0) throws java.io.IOException;
    void modifyAclEntries(PathInterface arg0, java.util.List<org.apache.hadoop.fs.permission.AclEntry> arg1) throws java.io.IOException;
    FSDataOutputStreamInterface create(PathInterface arg0, boolean arg1, int arg2, short arg3, long arg4) throws java.io.IOException;
    PathInterface getHomeDirectory();
    FileStatusInterface[] listStatus(PathInterface[] arg0, org.apache.hadoop.fs.PathFilter arg1) throws java.io.FileNotFoundException, java.io.IOException;
    org.apache.hadoop.fs.RemoteIterator<org.apache.hadoop.fs.Path> listCorruptFileBlocks(PathInterface arg0) throws java.io.IOException;
    FileStatusInterface getFileStatus(PathInterface arg0) throws java.io.IOException;
    FileSystemInterface get(java.net.URI arg0, ConfigurationInterface arg1) throws java.io.IOException;
    void setDefaultUri(ConfigurationInterface arg0, java.lang.String arg1);
    void removeAclEntries(PathInterface arg0, java.util.List<org.apache.hadoop.fs.permission.AclEntry> arg1) throws java.io.IOException;
    void loadFileSystems();
    void removeDefaultAcl(PathInterface arg0) throws java.io.IOException;
    void close() throws java.io.IOException;
    void enableSymlinks();
    FileStatusInterface[] listStatus(PathInterface arg0) throws java.io.FileNotFoundException, java.io.IOException;
    PathInterface makeQualified(PathInterface arg0);
    FileSystemInterface newInstance(java.net.URI arg0, ConfigurationInterface arg1, java.lang.String arg2) throws java.io.IOException, java.lang.InterruptedException;
    FSDataOutputStreamInterface create(PathInterface arg0, boolean arg1, int arg2, short arg3, long arg4, org.apache.hadoop.util.Progressable arg5) throws java.io.IOException;
    void collectDelegationTokens(org.apache.hadoop.security.token.DelegationTokenIssuer arg0, java.lang.String arg1, CredentialsInterface arg2, java.util.List<org.apache.hadoop.security.token.Token<?>> arg3) throws java.io.IOException;
    FSDataOutputStreamBuilderInterface createFile(PathInterface arg0);
    DirectoryEntriesInterface listStatusBatch(PathInterface arg0, byte[] arg1) throws java.io.FileNotFoundException, java.io.IOException;
    FileSystemInterface get(ConfigurationInterface arg0) throws java.io.IOException;
    FileSystemInterface getNamed(java.lang.String arg0, ConfigurationInterface arg1) throws java.io.IOException;
    java.util.Map<java.lang.String, byte[]> getXAttrs(PathInterface arg0) throws java.io.IOException;
    FSDataInputStreamBuilderInterface createDataInputStreamBuilder(FileSystemInterface arg0, org.apache.hadoop.fs.PathHandle arg1);
    void unsetStoragePolicy(PathInterface arg0) throws java.io.IOException;
    void concat(PathInterface arg0, PathInterface[] arg1) throws java.io.IOException;
    void satisfyStoragePolicy(PathInterface arg0) throws java.io.IOException;
    long getUsed() throws java.io.IOException;
    org.apache.hadoop.fs.GlobalStorageStatistics getGlobalStorageStatistics();
    BlockLocationInterface[] getFileBlockLocations(FileStatusInterface arg0, long arg1, long arg2) throws java.io.IOException;
    java.net.URI getUri();
    void moveFromLocalFile(PathInterface[] arg0, PathInterface arg1) throws java.io.IOException;
    FileStatusInterface[] globStatus(PathInterface arg0, org.apache.hadoop.fs.PathFilter arg1) throws java.io.IOException;
    java.lang.Class<? extends org.apache.hadoop.fs.FileSystem> getFileSystemClass(java.lang.String arg0, ConfigurationInterface arg1) throws java.io.IOException;
    boolean supportsSymlinks();
    void setOwner(PathInterface arg0, java.lang.String arg1, java.lang.String arg2) throws java.io.IOException;
    boolean cancelDeleteOnExit(PathInterface arg0);
    PathInterface getWorkingDirectory();
    void removeAcl(PathInterface arg0) throws java.io.IOException;
    PathInterface createSnapshot(PathInterface arg0) throws java.io.IOException;
    FileStatusInterface[] globStatus(PathInterface arg0) throws java.io.IOException;
    FSDataOutputStreamInterface create(PathInterface arg0, short arg1, org.apache.hadoop.util.Progressable arg2) throws java.io.IOException;
    PathInterface getLinkTarget(PathInterface arg0) throws java.io.IOException;
    boolean isFile(PathInterface arg0) throws java.io.IOException;
    FSDataInputStreamBuilderInterface createDataInputStreamBuilder(FileSystemInterface arg0, PathInterface arg1);
    java.lang.String fixName(java.lang.String arg0);
    FSDataInputStreamInterface open(org.apache.hadoop.fs.PathHandle arg0) throws java.io.IOException;
    FSDataInputStreamInterface open(org.apache.hadoop.fs.PathHandle arg0, int arg1) throws java.io.IOException;
    boolean truncate(PathInterface arg0, long arg1) throws java.io.IOException;
    boolean delete(PathInterface arg0) throws java.io.IOException;
    FileSystemInterface newInstance(java.net.URI arg0, ConfigurationInterface arg1) throws java.io.IOException;
    TokenInterface<?>[] addDelegationTokens(java.lang.String arg0, CredentialsInterface arg1) throws java.io.IOException;
    FileChecksumInterface getFileChecksum(PathInterface arg0) throws java.io.IOException;
    long getDefaultBlockSize(PathInterface arg0);
    void setWriteChecksum(boolean arg0);
    ConfigurationInterface getConf();
    PathInterface resolveLink(PathInterface arg0) throws java.io.IOException;
    boolean areSymlinksEnabled();
    short getReplication(PathInterface arg0) throws java.io.IOException;
    void setXAttr(PathInterface arg0, java.lang.String arg1, byte[] arg2) throws java.io.IOException;
    void printStatistics() throws java.io.IOException;
    PathInterface startLocalOutput(PathInterface arg0, PathInterface arg1) throws java.io.IOException;
    void setAcl(PathInterface arg0, java.util.List<org.apache.hadoop.fs.permission.AclEntry> arg1) throws java.io.IOException;
    FileSystemInterface newInstance(ConfigurationInterface arg0) throws java.io.IOException;
    java.net.URI canonicalizeUri(java.net.URI arg0);
    boolean setReplication(PathInterface arg0, short arg1) throws java.io.IOException;
    java.util.Map<java.lang.String, byte[]> getXAttrs(PathInterface arg0, java.util.List<java.lang.String> arg1) throws java.io.IOException;
    QuotaUsageInterface getQuotaUsage(PathInterface arg0) throws java.io.IOException;
    FileChecksumInterface getFileChecksum(PathInterface arg0, long arg1) throws java.io.IOException;
    java.net.URI getDefaultUri(ConfigurationInterface arg0);
    void primitiveMkdir(PathInterface arg0, FsPermissionInterface arg1, boolean arg2) throws java.io.IOException;
    void initialize(java.net.URI arg0, ConfigurationInterface arg1) throws java.io.IOException;
    FSDataOutputStreamInterface create(PathInterface arg0, boolean arg1) throws java.io.IOException;
    FSDataOutputStreamInterface create(PathInterface arg0, boolean arg1, int arg2) throws java.io.IOException;
    void setPermission(PathInterface arg0, FsPermissionInterface arg1) throws java.io.IOException;
    void setWorkingDirectory(PathInterface arg0);
    boolean hasPathCapability(PathInterface arg0, java.lang.String arg1) throws java.io.IOException;
    org.apache.hadoop.fs.MultipartUploaderBuilder createMultipartUploader(PathInterface arg0) throws java.io.IOException;
    org.apache.hadoop.fs.RemoteIterator<org.apache.hadoop.fs.LocatedFileStatus> listLocatedStatus(PathInterface arg0) throws java.io.FileNotFoundException, java.io.IOException;
    FileStatusInterface getFileLinkStatus(PathInterface arg0) throws org.apache.hadoop.security.AccessControlException, java.io.FileNotFoundException, org.apache.hadoop.fs.UnsupportedFileSystemException, java.io.IOException;
    FSDataOutputStreamInterface append(PathInterface arg0, int arg1) throws java.io.IOException;
    void setVerifyChecksum(boolean arg0);
    void copyToLocalFile(boolean arg0, PathInterface arg1, PathInterface arg2) throws java.io.IOException;
    FSDataOutputStreamInterface create(PathInterface arg0, FsPermissionInterface arg1, java.util.EnumSet<org.apache.hadoop.fs.CreateFlag> arg2, int arg3, short arg4, long arg5, org.apache.hadoop.util.Progressable arg6) throws java.io.IOException;
    void setConf(ConfigurationInterface arg0);
    void moveFromLocalFile(PathInterface arg0, PathInterface arg1) throws java.io.IOException;
    PathInterface getTrashRoot(PathInterface arg0);
    FSDataOutputStreamInterface create(PathInterface arg0, FsPermissionInterface arg1, boolean arg2, int arg3, short arg4, long arg5, org.apache.hadoop.util.Progressable arg6) throws java.io.IOException;
    StatisticsInterface getStatistics(java.lang.String arg0, java.lang.Class<? extends org.apache.hadoop.fs.FileSystem> arg1);
    void closeAll() throws java.io.IOException;
    void copyFromLocalFile(PathInterface arg0, PathInterface arg1) throws java.io.IOException;
    short getDefaultReplication();
    java.net.URI getCanonicalUri();
    PathInterface getInitialWorkingDirectory();
    FileSystemInterface createFileSystem(java.net.URI arg0, ConfigurationInterface arg1) throws java.io.IOException;
    void setStoragePolicy(PathInterface arg0, java.lang.String arg1) throws java.io.IOException;
    java.util.List<org.apache.hadoop.fs.FileSystem.Statistics> getAllStatistics();
    FileStatusInterface[] listStatus(PathInterface[] arg0) throws java.io.FileNotFoundException, java.io.IOException;
    FSDataOutputStreamInterface createNonRecursive(PathInterface arg0, FsPermissionInterface arg1, java.util.EnumSet<org.apache.hadoop.fs.CreateFlag> arg2, int arg3, short arg4, long arg5, org.apache.hadoop.util.Progressable arg6) throws java.io.IOException;
    FSDataOutputStreamInterface createNonRecursive(PathInterface arg0, boolean arg1, int arg2, short arg3, long arg4, org.apache.hadoop.util.Progressable arg5) throws java.io.IOException;
    FSDataOutputStreamInterface create(PathInterface arg0, boolean arg1, int arg2, org.apache.hadoop.util.Progressable arg3) throws java.io.IOException;
    boolean delete(PathInterface arg0, boolean arg1) throws java.io.IOException;
    java.util.Collection<org.apache.hadoop.fs.FileStatus> getTrashRoots(boolean arg0);
    java.lang.String getName();
    boolean isDirectory(PathInterface arg0) throws java.io.IOException;
    FSDataOutputStreamInterface create(PathInterface arg0, FsPermissionInterface arg1, java.util.EnumSet<org.apache.hadoop.fs.CreateFlag> arg2, int arg3, short arg4, long arg5, org.apache.hadoop.util.Progressable arg6, ChecksumOptInterface arg7) throws java.io.IOException;
    void clearStatistics();
    StorageStatisticsInterface getStorageStatistics();
    java.util.concurrent.CompletableFuture<org.apache.hadoop.fs.FSDataInputStream> openFileWithOptions(org.apache.hadoop.fs.PathHandle arg0, OpenFileParametersInterface arg1) throws java.io.IOException;
    void createSymlink(PathInterface arg0, PathInterface arg1, boolean arg2) throws org.apache.hadoop.security.AccessControlException, org.apache.hadoop.fs.FileAlreadyExistsException, java.io.FileNotFoundException, org.apache.hadoop.fs.ParentNotDirectoryException, org.apache.hadoop.fs.UnsupportedFileSystemException, java.io.IOException;
    boolean rename(PathInterface arg0, PathInterface arg1) throws java.io.IOException;
    void methodNotSupported();
    AclStatusInterface getAclStatus(PathInterface arg0) throws java.io.IOException;
    java.lang.String getScheme();
    java.util.concurrent.CompletableFuture<org.apache.hadoop.fs.FSDataInputStream> openFileWithOptions(PathInterface arg0, OpenFileParametersInterface arg1) throws java.io.IOException;
    PathInterface fixRelativePart(PathInterface arg0);
    FsServerDefaultsInterface getServerDefaults() throws java.io.IOException;
    void copyToLocalFile(PathInterface arg0, PathInterface arg1) throws java.io.IOException;
    FSDataOutputStreamInterface append(PathInterface arg0, int arg1, org.apache.hadoop.util.Progressable arg2) throws java.io.IOException;
    org.apache.hadoop.security.token.DelegationTokenIssuer[] getAdditionalTokenIssuers() throws java.io.IOException;
    PathInterface resolvePath(PathInterface arg0) throws java.io.IOException;
    org.apache.hadoop.fs.FutureDataInputStreamBuilder openFile(PathInterface arg0) throws java.io.IOException, java.lang.UnsupportedOperationException;
    java.util.Map<java.lang.String, org.apache.hadoop.fs.FileSystem.Statistics> getStatistics();
    org.apache.hadoop.fs.RemoteIterator<org.apache.hadoop.fs.LocatedFileStatus> listLocatedStatus(PathInterface arg0, org.apache.hadoop.fs.PathFilter arg1) throws java.io.FileNotFoundException, java.io.IOException;
    void listStatus(java.util.ArrayList<org.apache.hadoop.fs.FileStatus> arg0, PathInterface arg1, org.apache.hadoop.fs.PathFilter arg2) throws java.io.FileNotFoundException, java.io.IOException;
    void setDefaultUri(ConfigurationInterface arg0, java.net.URI arg1);
}