package org.apache.hadoop.hdfs.remoteProxies;

public interface FilterHolderInterface {
    boolean isRunning();
    java.lang.String getDisplayName();
    void setStarting();
    void setName(java.lang.String arg0);
    void setFailed(java.lang.Throwable arg0);
//    T getInstance();
    void setStopping();
    void dumpIterable(java.lang.Appendable arg0, java.lang.String arg1, java.lang.Iterable<?> arg2, boolean arg3) throws java.io.IOException;
//    void setInstance(T arg0);
    void setInitParameters(java.util.Map<java.lang.String, java.lang.String> arg0);
    java.util.Map<java.lang.String, java.lang.String> getInitParameters();
    java.lang.String getState();
    void setStarted();
    void setStopped();
    SourceInterface getSource();
    void removeLifeCycleListener(org.eclipse.jetty.util.component.LifeCycle.Listener arg0);
    ServletHandlerInterface getServletHandler();
    void setClassName(java.lang.String arg0);
    void stop() throws java.lang.Exception;
    org.eclipse.jetty.util.component.Dumpable named(java.lang.String arg0, java.lang.Object arg1);
    javax.servlet.Filter getFilter();
    void setInitParameter(java.lang.String arg0, java.lang.String arg1);
    void setServletHandler(ServletHandlerInterface arg0);
    void lambda$named$0(java.lang.String arg0, java.lang.Object arg1, java.lang.Appendable arg2, java.lang.String arg3) throws java.io.IOException;
    void setAsyncSupported(boolean arg0);
    void start() throws java.lang.Exception;
    boolean isAsyncSupported();
    java.lang.String dumpSelf();
    void dumpMapEntries(java.lang.Appendable arg0, java.lang.String arg1, java.util.Map<?, ?> arg2, boolean arg3) throws java.io.IOException;
    java.lang.String getInitParameter(java.lang.String arg0);
    void dumpContainer(java.lang.Appendable arg0, java.lang.String arg1, org.eclipse.jetty.util.component.Container arg2, boolean arg3) throws java.io.IOException;
    void initialize() throws java.lang.Exception;
    void stop(java.lang.Object arg0);
    java.lang.String dump(org.eclipse.jetty.util.component.Dumpable arg0);
    boolean isFailed();
    void setFilter(javax.servlet.Filter arg0);
//    <W> T wrap(T arg0, java.lang.Class<W> arg1, java.util.function.BiFunction<W, T, T> arg2);
    void doStart() throws java.lang.Exception;
    void dumpObject(java.lang.Appendable arg0, java.lang.Object arg1) throws java.io.IOException;
    void doFilter(javax.servlet.ServletRequest arg0, javax.servlet.ServletResponse arg1, javax.servlet.FilterChain arg2) throws java.io.IOException, javax.servlet.ServletException;
    void setDisplayName(java.lang.String arg0);
    java.lang.String getName();
//    void setHeldClass(java.lang.Class<? extends T> arg0);
    java.lang.String toString();
    void doStop() throws java.lang.Exception;
    boolean isStopping();
    javax.servlet.FilterRegistration.Dynamic getRegistration();
    java.lang.String dump();
//    java.lang.Class<? extends T> getHeldClass();
    void start(java.lang.Object arg0);
    boolean isStarted();
    boolean isStarting();
    void dumpObjects(java.lang.Appendable arg0, java.lang.String arg1, java.lang.Object arg2, java.lang.Object... arg3) throws java.io.IOException;
//    T unwrap(T arg0);
    long getStopTimeout();
    void illegalStateIfContextStarted();
    boolean isInstance();
    void destroyInstance(java.lang.Object arg0);
    void addLifeCycleListener(org.eclipse.jetty.util.component.LifeCycle.Listener arg0);
    java.lang.String getState(org.eclipse.jetty.util.component.LifeCycle arg0);
    boolean isStopped();
    java.util.Enumeration<java.lang.String> getInitParameterNames();
    java.lang.String getClassName();
    void dump(java.lang.Appendable arg0, java.lang.String arg1) throws java.io.IOException;
    void setStopTimeout(long arg0);
}