package org.apache.hadoop.hdfs.remoteProxies;

public interface HttpURIInterface {
    java.lang.String getHost();
//    void parse(org.eclipse.jetty.http.HttpURI.State arg0, java.lang.String arg1, int arg2, int arg3);
    boolean isAbsolute();
    java.lang.String getDecodedPath();
    boolean hasAuthority();
    void setPath(java.lang.String arg0);
    void setAuthority(java.lang.String arg0, int arg1);
    java.lang.String getUser();
    boolean hasAmbiguousSeparator();
    java.lang.String getAuthority();
    void setParam(java.lang.String arg0);
    java.lang.String getQuery();
    boolean hasViolations();
    java.lang.String getPath();
    void parseConnect(java.lang.String arg0);
    boolean hasQuery();
    boolean hasAmbiguousEmptySegment();
    boolean equals(java.lang.Object arg0);
    void clear();
    int hashCode();
    void parse(java.lang.String arg0, int arg1, int arg2);
    boolean hasAmbiguousEncoding();
    boolean isAmbiguous();
    java.lang.String getFragment();
    void setPathQuery(java.lang.String arg0);
    void decodeQueryTo(MultiMapInterface<java.lang.String> arg0);
    HttpURIInterface createHttpURI(java.lang.String arg0, java.lang.String arg1, int arg2, java.lang.String arg3, java.lang.String arg4, java.lang.String arg5, java.lang.String arg6);
//    boolean hasViolation(org.eclipse.jetty.http.HttpURI.Violation arg0);
    boolean hasAmbiguousParameter();
    void setQuery(java.lang.String arg0);
    java.lang.String getPathQuery();
    java.lang.String toString();
    boolean hasUtf16Encoding();
    boolean hasAmbiguousSegment();
    boolean isPathValidForAuthority(java.lang.String arg0);
    int getPort();
    void decodeQueryTo(MultiMapInterface<java.lang.String> arg0, java.lang.String arg1) throws java.io.UnsupportedEncodingException;
    void parseRequestTarget(java.lang.String arg0, java.lang.String arg1);
    void parse(java.lang.String arg0);
    void checkSegment(java.lang.String arg0, int arg1, int arg2, boolean arg3);
    java.lang.String getParam();
    java.lang.String getScheme();
    void setScheme(java.lang.String arg0);
    void decodeQueryTo(MultiMapInterface<java.lang.String> arg0, java.nio.charset.Charset arg1) throws java.io.UnsupportedEncodingException;
    java.net.URI toURI() throws java.net.URISyntaxException;
}