package org.apache.hadoop.hdfs.remoteProxies;

public interface ImmutableSetInterface<E> {
    <E> ImmutableSetInterface<E> constructUnknownDuplication(int arg0, java.lang.Object... arg1);
    <E> java.util.Set<E> of(E arg0, E arg1, E arg2, E arg3, E arg4);
    ImmutableListInterface<E> createAsList();
    boolean add(E arg0);
    <E> java.util.Set<E> of(E arg0, E arg1, E arg2, E arg3);
    <E> java.util.Set<E> copyOf(java.util.Collection<? extends E> arg0);
//    void forEach(java.util.function.Consumer<? super T> arg0);
//    UnmodifiableIteratorInterface<E> iterator();
    int chooseTableSize(int arg0);
    boolean contains(java.lang.Object arg0);
    <T> T[] toArray(java.util.function.IntFunction<T[]> arg0);
    int internalArrayStart();
    <E> java.util.Set<E> of(E... arg0);
    <E> ImmutableSetInterface<E> of(E arg0, E arg1, E arg2);
    <E> java.util.Set<E> of(E arg0, E arg1);
    <E> java.util.Set<E> of(E arg0, E arg1, E arg2, E arg3, E arg4, E arg5);
    <T> T[] finishToArray(T[] arg0, java.util.Iterator<?> arg1);
    java.lang.String toString();
    java.lang.Object[] toArray();
    <E> java.util.Set<E> of();
    java.util.Spliterator<E> spliterator();
//    <E> ImmutableSetInterface<E> of(E arg0, E arg1, E arg2, E arg3, E arg4);
    ImmutableSetInterface copyOfEnumSet(java.util.EnumSet arg0);
//    <E> BuilderInterface<E> builderWithExpectedSize(int arg0);
    java.util.stream.Stream<E> parallelStream();
    java.util.stream.Stream<E> stream();
    boolean removeAll(java.util.Collection<?> arg0);
    <E> java.util.Set<E> of(E arg0);
    boolean equals(java.lang.Object arg0);
//    <E> ImmutableSetInterface<E> of(E arg0, E arg1, E arg2, E arg3);
    <E> ImmutableSetInterface<E> copyOf(java.util.Iterator<? extends E> arg0);
    int hugeCapacity(int arg0);
//    java.util.Spliterator<T> spliterator();
    boolean isPartialView();
    java.lang.Object[] internalArray();
    boolean containsAll(java.util.Collection<?> arg0);
    int hashCode();
    boolean remove(java.lang.Object arg0);
    boolean hashFloodingDetected(java.lang.Object[] arg0);
    boolean addAll(java.util.Collection<? extends E> arg0);
    <E> ImmutableSetInterface<E> of(E arg0, E arg1, E arg2, E arg3, E arg4, E arg5, E... arg6);
    <E> java.util.Set<E> of(E arg0, E arg1, E arg2, E arg3, E arg4, E arg5, E arg6, E arg7);
//    <E> ImmutableSetInterface<E> of(E arg0);
    boolean isEmpty();
    <E> java.util.stream.Collector<E, ?, org.apache.hadoop.thirdparty.com.google.common.collect.ImmutableSet<E>> toImmutableSet();
    boolean removeIf(java.util.function.Predicate<? super E> arg0);
    java.lang.Object writeReplace();
    int maxRunBeforeFallback(int arg0);
//    java.util.Iterator<T> iterator();
    <E> java.util.Set<E> of(E arg0, E arg1, E arg2, E arg3, E arg4, E arg5, E arg6, E arg7, E arg8);
    <E> ImmutableSetInterface<E> copyOf(java.lang.Iterable<? extends E> arg0);
    int size();
//    <E> ImmutableSetInterface<E> copyOf(java.util.Collection<? extends E> arg0);
    ImmutableListInterface<E> asList();
    boolean isHashCodeFast();
    boolean retainAll(java.util.Collection<?> arg0);
    <E> java.util.Set<E> of(E arg0, E arg1, E arg2, E arg3, E arg4, E arg5, E arg6);
//    <E> java.util.Set<E> of(E arg0, E arg1, E arg2);
    java.lang.Object[] rebuildHashTable(int arg0, java.lang.Object[] arg1, int arg2);
    int copyIntoArray(java.lang.Object[] arg0, int arg1);
//    <E> ImmutableSetInterface<E> of(E arg0, E arg1);
    <E> java.util.Set<E> of(E arg0, E arg1, E arg2, E arg3, E arg4, E arg5, E arg6, E arg7, E arg8, E arg9);
//    <E> ImmutableSetInterface<E> of();
    <E> ImmutableSetInterface<E> copyOf(E[] arg0);
    int internalArrayEnd();
    void clear();
//    <E> BuilderInterface<E> builder();
    java.util.Iterator<E> iterator();
    <E> ImmutableSetInterface<E> construct(int arg0, int arg1, java.lang.Object... arg2);
    <T> T[] toArray(T[] arg0);
}