package org.apache.hadoop.hdfs.remoteProxies;

public interface INodeWithAdditionalFieldsInterface {
    java.lang.String toDetailString();
    INodeReferenceInterface asReference();
    boolean isDirectory();
    boolean equals(java.lang.Object arg0);
    void cleanSubtree(ReclaimContextInterface arg0, int arg1, int arg2);
    boolean isAncestorDirectory(INodeDirectoryInterface arg0);
    void setAccessTime(long arg0);
    java.lang.String getUserName(int arg0);
    QuotaCountsInterface computeQuotaUsage(BlockStoragePolicySuiteInterface arg0);
    void setLocalName(byte[] arg0);
    long getId();
    void throwFeatureNotFoundException(org.apache.hadoop.hdfs.server.namenode.INode.Feature arg0);
    AclFeatureInterface getAclFeature();
    java.lang.String getParentString();
    PermissionStatusInterface getPermissionStatus();
    boolean isSetStoragePolicy();
    void setNext(org.apache.hadoop.util.LightWeightGSet.LinkedElement arg0);
    void addFeature(org.apache.hadoop.hdfs.server.namenode.INode.Feature arg0);
    long getPermissionLong();
    void clear();
    void addSpaceConsumed(QuotaCountsInterface arg0);
    java.lang.StringBuffer dumpTreeRecursively();
    void dumpTreeRecursively(java.io.PrintStream arg0);
    void setParentReference(INodeReferenceInterface arg0);
    java.lang.String getGroupName();
    ContentSummaryInterface computeContentSummary(BlockStoragePolicySuiteInterface arg0) throws org.apache.hadoop.security.AccessControlException;
    byte[][] getPathComponents();
    boolean isDeleted();
    void cloneModificationTime(INodeWithAdditionalFieldsInterface arg0);
    boolean isValidAbsolutePath(java.lang.String arg0);
    INodeInterface setModificationTime(long arg0, int arg1);
    INodeInterface setAccessTime(long arg0, int arg1, boolean arg2);
    org.apache.hadoop.hdfs.server.namenode.INodeAttributes getSnapshotINode(int arg0);
    byte[] getKey();
    void setPermission(FsPermissionInterface arg0);
    java.lang.String getObjectString();
    void clonePermissionStatus(INodeWithAdditionalFieldsInterface arg0);
    void addXAttrFeature(XAttrFeatureInterface arg0);
    void removeXAttrFeature();
    void checkAbsolutePath(java.lang.String arg0);
    INodeInterface removeAclFeature(int arg0);
    void setModificationTime(long arg0);
    java.lang.String[] getPathNames(java.lang.String arg0);
    INodeFileInterface asFile();
    <T> T getFeature(java.lang.Class<? extends org.apache.hadoop.hdfs.server.namenode.INode.Feature> arg0);
    boolean isReference();
    INodeInterface setGroup(java.lang.String arg0, int arg1);
    java.lang.String getLocalName();
    long getModificationTime();
    QuotaCountsInterface computeQuotaUsage(BlockStoragePolicySuiteInterface arg0, byte arg1, boolean arg2, int arg3);
    byte[] getLocalNameBytes();
    int compareTo(byte[] arg0);
    byte[][] getPathComponents(java.lang.String arg0);
    AclFeatureInterface getAclFeature(int arg0);
    boolean shouldRecordInSrcSnapshot(int arg0);
    void setParent(INodeDirectoryInterface arg0);
    PermissionStatusInterface getPermissionStatus(int arg0);
//    K getKey();
    INodeReferenceInterface getParentReference();
    int hashCode();
    short getFsPermissionShort();
    FsPermissionInterface getFsPermission(int arg0);
    boolean isLastReference();
    boolean isFile();
    INodeInterface removeXAttrFeature(int arg0);
    long getModificationTime(int arg0);
    void dumpTreeRecursively(java.io.PrintWriter arg0, java.lang.StringBuilder arg1, int arg2);
    org.apache.hadoop.util.LightWeightGSet.LinkedElement getNext();
    byte getLocalStoragePolicyID();
    void removeAclFeature();
    boolean isInCurrentState();
    ContentSummaryComputationContextInterface computeContentSummary(int arg0, ContentSummaryComputationContextInterface arg1) throws org.apache.hadoop.security.AccessControlException;
    void removeFeature(org.apache.hadoop.hdfs.server.namenode.INode.Feature arg0);
    void destroyAndCollectBlocks(ReclaimContextInterface arg0);
    QuotaCountsInterface computeQuotaUsage(BlockStoragePolicySuiteInterface arg0, boolean arg1);
    FsPermissionInterface getFsPermission();
    INodeDirectoryInterface getParent();
    boolean isRoot();
    void setUser(java.lang.String arg0);
    long getAccessTime(int arg0);
    byte getStoragePolicyIDForQuota(byte arg0);
    INodeInterface updateModificationTime(long arg0, int arg1);
    void setGroup(java.lang.String arg0);
    XAttrFeatureInterface getXAttrFeature(int arg0);
    INodeInterface addXAttrFeature(XAttrFeatureInterface arg0, int arg1);
    void recordModification(int arg0);
    void addAclFeature(AclFeatureInterface arg0);
    INodeSymlinkInterface asSymlink();
    ContentSummaryInterface computeAndConvertContentSummary(int arg0, ContentSummaryComputationContextInterface arg1) throws org.apache.hadoop.security.AccessControlException;
    XAttrFeatureInterface getXAttrFeature();
    java.lang.String getFullPathName();
    INodeInterface addAclFeature(AclFeatureInterface arg0, int arg1);
//    void updatePermissionStatus(org.apache.hadoop.hdfs.server.namenode.INodeWithAdditionalFields.PermissionStatusFormat arg0, long arg1);
    byte getStoragePolicyID();
    java.lang.String toString();
    boolean isQuotaSet();
    long getAccessTime();
    java.lang.String getGroupName(int arg0);
    INodeInterface setUser(java.lang.String arg0, int arg1);
    INodeDirectoryInterface asDirectory();
    INodeInterface setPermission(FsPermissionInterface arg0, int arg1);
    boolean isInLatestSnapshot(int arg0);
    QuotaCountsInterface getQuotaCounts();
    java.lang.String getUserName();
    org.apache.hadoop.hdfs.server.namenode.INode.Feature[] getFeatures();
    boolean isSymlink();
}