package org.apache.hadoop.hdfs.remoteProxies;

public interface INodeReferenceInterface {
    AclFeatureInterface getAclFeature();
    boolean isInCurrentState();
    QuotaCountsInterface computeQuotaUsage(BlockStoragePolicySuiteInterface arg0, byte arg1, boolean arg2, int arg3);
    void addSpaceConsumed(QuotaCountsInterface arg0);
    void removeXAttrFeature();
    java.lang.String getLocalName();
    INodeReferenceInterface asReference();
    void setUser(java.lang.String arg0);
    INodeDirectoryInterface asDirectory();
    XAttrFeatureInterface getXAttrFeature(int arg0);
    void clear();
    boolean isQuotaSet();
    java.lang.String getUserName();
    byte[] getKey();
    PermissionStatusInterface getPermissionStatus(int arg0);
    void dumpTreeRecursively(java.io.PrintStream arg0);
    INodeFileInterface asFile();
    INodeInterface setGroup(java.lang.String arg0, int arg1);
    void cleanSubtree(ReclaimContextInterface arg0, int arg1, int arg2);
    void addAclFeature(AclFeatureInterface arg0);
    byte getLocalStoragePolicyID();
    PermissionStatusInterface getPermissionStatus();
    void removeAclFeature();
    long getId();
    QuotaCountsInterface computeQuotaUsage(BlockStoragePolicySuiteInterface arg0);
    java.lang.String getGroupName(int arg0);
    long getModificationTime();
    long getPermissionLong();
    QuotaCountsInterface computeQuotaUsage(BlockStoragePolicySuiteInterface arg0, boolean arg1);
    void setParent(INodeDirectoryInterface arg0);
    INodeInterface removeXAttrFeature(int arg0);
    INodeInterface addAclFeature(AclFeatureInterface arg0, int arg1);
    long getAccessTime();
    byte[] getLocalNameBytes();
    ContentSummaryInterface computeAndConvertContentSummary(int arg0, ContentSummaryComputationContextInterface arg1) throws org.apache.hadoop.security.AccessControlException;
    void setGroup(java.lang.String arg0);
    AclFeatureInterface getAclFeature(int arg0);
    void destroyAndCollectBlocks(ReclaimContextInterface arg0);
    java.lang.String[] getPathNames(java.lang.String arg0);
    INodeReferenceInterface getParentReference();
    java.lang.StringBuffer dumpTreeRecursively();
    void setLocalName(byte[] arg0);
    INodeInterface addXAttrFeature(XAttrFeatureInterface arg0, int arg1);
    java.lang.String toString();
    boolean isSymlink();
    boolean isDeleted();
    INodeInterface setModificationTime(long arg0, int arg1);
    boolean isInLatestSnapshot(int arg0);
    byte getStoragePolicyIDForQuota(byte arg0);
    void recordModification(int arg0);
    void dumpTreeRecursively(java.io.PrintWriter arg0, java.lang.StringBuilder arg1, int arg2);
    byte getStoragePolicyID();
    int compareTo(byte[] arg0);
    INodeInterface removeAclFeature(int arg0);
    QuotaCountsInterface getQuotaCounts();
    int removeReference(INodeReferenceInterface arg0);
    boolean isRoot();
    int tryRemoveReference(INodeInterface arg0);
    boolean isSetStoragePolicy();
    INodeInterface setAccessTime(long arg0, int arg1, boolean arg2);
    FsPermissionInterface getFsPermission(int arg0);
    int getDstSnapshotId();
    void setPermission(FsPermissionInterface arg0);
    boolean isAncestorDirectory(INodeDirectoryInterface arg0);
    long getModificationTime(int arg0);
    boolean isLastReference();
    boolean shouldRecordInSrcSnapshot(int arg0);
    short getFsPermissionShort();
    INodeInterface getReferredINode();
    byte[][] getPathComponents(java.lang.String arg0);
    ContentSummaryInterface computeContentSummary(BlockStoragePolicySuiteInterface arg0) throws org.apache.hadoop.security.AccessControlException;
    int getPriorSnapshot(INodeReferenceInterface arg0);
    INodeDirectoryInterface getParent();
    boolean isReference();
    java.lang.String getUserName(int arg0);
    boolean equals(java.lang.Object arg0);
    java.lang.String getParentString();
    XAttrFeatureInterface getXAttrFeature();
    void setModificationTime(long arg0);
    java.lang.String toDetailString();
//    K getKey();
    FsPermissionInterface getFsPermission();
    void addXAttrFeature(XAttrFeatureInterface arg0);
    INodeInterface setPermission(FsPermissionInterface arg0, int arg1);
    long getAccessTime(int arg0);
    ContentSummaryComputationContextInterface computeContentSummary(int arg0, ContentSummaryComputationContextInterface arg1) throws org.apache.hadoop.security.AccessControlException;
    java.lang.String getGroupName();
    void checkAbsolutePath(java.lang.String arg0);
    void setParentReference(INodeReferenceInterface arg0);
    INodeInterface setUser(java.lang.String arg0, int arg1);
    boolean isDirectory();
    org.apache.hadoop.hdfs.server.namenode.INodeAttributes getSnapshotINode(int arg0);
    int hashCode();
    boolean isValidAbsolutePath(java.lang.String arg0);
    java.lang.String getObjectString();
    INodeSymlinkInterface asSymlink();
    java.lang.String getFullPathName();
    INodeInterface updateModificationTime(long arg0, int arg1);
    byte[][] getPathComponents();
    boolean isFile();
    void setAccessTime(long arg0);
}