package org.apache.hadoop.hdfs.remoteProxies;

public interface JsonParserInterface {
    int getCurrentTokenId();
    JsonParserInterface enable(com.fasterxml.jackson.core.JsonParser.Feature arg0);
    java.lang.String nextTextValue() throws java.io.IOException;
    com.fasterxml.jackson.core.async.NonBlockingInputFeeder getNonBlockingInputFeeder();
    int currentTokenId();
    java.lang.String getValueAsString() throws java.io.IOException;
    void setSchema(com.fasterxml.jackson.core.FormatSchema arg0);
    int getIntValue() throws java.io.IOException;
    JsonParseExceptionInterface _constructReadException(java.lang.String arg0, java.lang.Object arg1);
    void clearCurrentToken();
    int getText(java.io.Writer arg0) throws java.io.IOException, java.lang.UnsupportedOperationException;
    JsonStreamContextInterface getParsingContext();
    java.lang.Object getTypeId() throws java.io.IOException;
    double getValueAsDouble() throws java.io.IOException;
    boolean getValueAsBoolean() throws java.io.IOException;
    int getFormatFeatures();
    void close() throws java.io.IOException;
    boolean hasToken(com.fasterxml.jackson.core.JsonToken arg0);
    void setRequestPayloadOnError(byte[] arg0, java.lang.String arg1);
    long getLongValue() throws java.io.IOException;
    boolean hasTokenId(int arg0);
    boolean isExpectedStartObjectToken();
    ObjectCodecInterface _codec();
    long getValueAsLong(long arg0) throws java.io.IOException;
    com.fasterxml.jackson.core.JsonToken getLastClearedToken();
    JsonParserInterface overrideFormatFeatures(int arg0, int arg1);
    com.fasterxml.jackson.core.JsonToken nextValue() throws java.io.IOException;
    <T> java.util.Iterator<T> readValuesAs(TypeReferenceInterface<T> arg0) throws java.io.IOException;
    java.math.BigInteger getBigIntegerValue() throws java.io.IOException;
    byte[] getBinaryValue() throws java.io.IOException;
    VersionInterface version();
    void setRequestPayloadOnError(java.lang.String arg0);
    boolean isExpectedNumberIntToken();
    boolean getBooleanValue() throws java.io.IOException;
    int getFeatureMask();
    java.lang.String nextFieldName() throws java.io.IOException;
    double getValueAsDouble(double arg0) throws java.io.IOException;
    com.fasterxml.jackson.core.JsonToken currentToken();
    boolean requiresCustomCodec();
    int getTextLength() throws java.io.IOException;
    void assignCurrentValue(java.lang.Object arg0);
    java.lang.Number getNumberValue() throws java.io.IOException;
    <T> java.util.Iterator<T> readValuesAs(java.lang.Class<T> arg0) throws java.io.IOException;
    JsonParserInterface setFeatureMask(int arg0);
    JacksonFeatureSetInterface<com.fasterxml.jackson.core.StreamReadCapability> getReadCapabilities();
    boolean nextFieldName(com.fasterxml.jackson.core.SerializableString arg0) throws java.io.IOException;
    double getDoubleValue() throws java.io.IOException;
    boolean isExpectedStartArrayToken();
    float getFloatValue() throws java.io.IOException;
    JsonParseExceptionInterface _constructReadException(java.lang.String arg0, java.lang.Object arg1, java.lang.Object arg2);
    void setCodec(ObjectCodecInterface arg0);
    JsonParserInterface skipChildren() throws java.io.IOException;
    int getValueAsInt(int arg0) throws java.io.IOException;
    JsonParserInterface configure(com.fasterxml.jackson.core.JsonParser.Feature arg0, boolean arg1);
    long getValueAsLong() throws java.io.IOException;
    java.lang.Boolean nextBooleanValue() throws java.io.IOException;
    short getShortValue() throws java.io.IOException;
    java.lang.Number getNumberValueExact() throws java.io.IOException;
    int releaseBuffered(java.io.OutputStream arg0) throws java.io.IOException;
    char[] getTextCharacters() throws java.io.IOException;
    <T> T readValueAs(java.lang.Class<T> arg0) throws java.io.IOException;
    int readBinaryValue(java.io.OutputStream arg0) throws java.io.IOException;
    int readBinaryValue(Base64VariantInterface arg0, java.io.OutputStream arg1) throws java.io.IOException;
    java.lang.Object getInputSource();
    java.lang.String getCurrentName() throws java.io.IOException;
    JsonLocationInterface getTokenLocation();
    java.lang.Object currentValue();
    java.lang.String getText() throws java.io.IOException;
    int nextIntValue(int arg0) throws java.io.IOException;
    JsonParseExceptionInterface _constructError(java.lang.String arg0);
    byte[] getBinaryValue(Base64VariantInterface arg0) throws java.io.IOException;
    com.fasterxml.jackson.core.JsonToken nextToken() throws java.io.IOException;
    void overrideCurrentName(java.lang.String arg0);
    boolean canUseSchema(com.fasterxml.jackson.core.FormatSchema arg0);
    ObjectCodecInterface getCodec();
    long nextLongValue(long arg0) throws java.io.IOException;
    com.fasterxml.jackson.core.FormatSchema getSchema();
    void _reportUnsupportedOperation();
    com.fasterxml.jackson.core.JsonParser.NumberType getNumberType() throws java.io.IOException;
    void setCurrentValue(java.lang.Object arg0);
    boolean getValueAsBoolean(boolean arg0) throws java.io.IOException;
    void finishToken() throws java.io.IOException;
    JsonLocationInterface getCurrentLocation();
    void setRequestPayloadOnError(RequestPayloadInterface arg0);
    int releaseBuffered(java.io.Writer arg0) throws java.io.IOException;
    JsonParseExceptionInterface _constructReadException(java.lang.String arg0, java.lang.Throwable arg1);
    java.lang.String currentName() throws java.io.IOException;
    int getTextOffset() throws java.io.IOException;
    java.math.BigDecimal getDecimalValue() throws java.io.IOException;
    java.lang.Object getCurrentValue();
    boolean isNaN() throws java.io.IOException;
    JsonLocationInterface currentLocation();
    boolean isEnabled(com.fasterxml.jackson.core.JsonParser.Feature arg0);
    boolean hasCurrentToken();
    int getValueAsInt() throws java.io.IOException;
    boolean isEnabled(com.fasterxml.jackson.core.StreamReadFeature arg0);
    java.lang.Object getObjectId() throws java.io.IOException;
    boolean canReadObjectId();
    java.lang.String getValueAsString(java.lang.String arg0) throws java.io.IOException;
    java.lang.Object getEmbeddedObject() throws java.io.IOException;
    boolean isClosed();
    boolean hasTextCharacters();
    boolean canParseAsync();
    <T> T readValueAsTree() throws java.io.IOException;
    boolean canReadTypeId();
    JsonParseExceptionInterface _constructReadException(java.lang.String arg0, java.lang.Object arg1, java.lang.Object arg2, java.lang.Object arg3);
    <T> T readValueAs(TypeReferenceInterface<?> arg0) throws java.io.IOException;
    JsonParseExceptionInterface _constructReadException(java.lang.String arg0);
    JsonParserInterface disable(com.fasterxml.jackson.core.JsonParser.Feature arg0);
    JsonParserInterface overrideStdFeatures(int arg0, int arg1);
    byte getByteValue() throws java.io.IOException;
    JsonLocationInterface currentTokenLocation();
    com.fasterxml.jackson.core.JsonToken getCurrentToken();
}