package org.apache.hadoop.hdfs.remoteProxies;

public interface JsonGeneratorInterface {
    void writeObjectFieldStart(java.lang.String arg0) throws java.io.IOException;
    JsonGeneratorInterface setRootValueSeparator(com.fasterxml.jackson.core.SerializableString arg0);
    void writeString(java.io.Reader arg0, int arg1) throws java.io.IOException;
    void writeNumberField(java.lang.String arg0, double arg1) throws java.io.IOException;
    void writeRaw(char[] arg0, int arg1, int arg2) throws java.io.IOException;
    void _writeSimpleObject(java.lang.Object arg0) throws java.io.IOException;
    JsonGeneratorInterface setCodec(ObjectCodecInterface arg0);
    void writeString(java.lang.String arg0) throws java.io.IOException;
    JsonGeneratorInterface disable(com.fasterxml.jackson.core.JsonGenerator.Feature arg0);
    VersionInterface version();
    void writeRaw(java.lang.String arg0) throws java.io.IOException;
    void writeString(char[] arg0, int arg1, int arg2) throws java.io.IOException;
    void writeStartObject(java.lang.Object arg0, int arg1) throws java.io.IOException;
    void writeEndArray() throws java.io.IOException;
    void writeNumber(java.math.BigDecimal arg0) throws java.io.IOException;
    void _reportUnsupportedOperation();
    void writeArray(long[] arg0, int arg1, int arg2) throws java.io.IOException;
    void writeStartArray(java.lang.Object arg0, int arg1) throws java.io.IOException;
    void writeEndObject() throws java.io.IOException;
    void writeOmittedField(java.lang.String arg0) throws java.io.IOException;
    boolean canWriteObjectId();
    JsonGeneratorInterface overrideFormatFeatures(int arg0, int arg1);
    void writeEmbeddedObject(java.lang.Object arg0) throws java.io.IOException;
    void writeBinaryField(java.lang.String arg0, byte[] arg1) throws java.io.IOException;
    void writeNumber(java.math.BigInteger arg0) throws java.io.IOException;
    void writeBoolean(boolean arg0) throws java.io.IOException;
    void writeUTF8String(byte[] arg0, int arg1, int arg2) throws java.io.IOException;
    void close() throws java.io.IOException;
    int getHighestEscapedChar();
    void assignCurrentValue(java.lang.Object arg0);
    void writeTree(com.fasterxml.jackson.core.TreeNode arg0) throws java.io.IOException;
    int writeBinary(java.io.InputStream arg0, int arg1) throws java.io.IOException;
    void _verifyOffsets(int arg0, int arg1, int arg2);
    java.lang.Object currentValue();
    void writeRawValue(com.fasterxml.jackson.core.SerializableString arg0) throws java.io.IOException;
    void _reportError(java.lang.String arg0) throws com.fasterxml.jackson.core.JsonGenerationException;
    JsonGeneratorInterface setFeatureMask(int arg0);
    JacksonFeatureSetInterface<com.fasterxml.jackson.core.StreamWriteCapability> getWriteCapabilities();
    void writeArrayFieldStart(java.lang.String arg0) throws java.io.IOException;
    boolean canWriteFormattedNumbers();
    void writeStartObject() throws java.io.IOException;
    int writeBinary(Base64VariantInterface arg0, java.io.InputStream arg1, int arg2) throws java.io.IOException;
    void writeBooleanField(java.lang.String arg0, boolean arg1) throws java.io.IOException;
    void writeRaw(com.fasterxml.jackson.core.SerializableString arg0) throws java.io.IOException;
    void writeArray(int[] arg0, int arg1, int arg2) throws java.io.IOException;
    int getFeatureMask();
    boolean canUseSchema(com.fasterxml.jackson.core.FormatSchema arg0);
    ObjectCodecInterface getCodec();
    JsonGeneratorInterface useDefaultPrettyPrinter();
    void writeNumberField(java.lang.String arg0, short arg1) throws java.io.IOException;
    void writeRaw(java.lang.String arg0, int arg1, int arg2) throws java.io.IOException;
    java.lang.Object getOutputTarget();
    void writeFieldId(long arg0) throws java.io.IOException;
    void setCurrentValue(java.lang.Object arg0);
    void writePOJOField(java.lang.String arg0, java.lang.Object arg1) throws java.io.IOException;
    int getFormatFeatures();
    void writeStartArray(java.lang.Object arg0) throws java.io.IOException;
    void writeBinary(byte[] arg0) throws java.io.IOException;
    void writeNumberField(java.lang.String arg0, java.math.BigDecimal arg1) throws java.io.IOException;
    void writePOJO(java.lang.Object arg0) throws java.io.IOException;
    JsonStreamContextInterface getOutputContext();
    void writeNumber(short arg0) throws java.io.IOException;
    CharacterEscapesInterface getCharacterEscapes();
    void writeNumberField(java.lang.String arg0, long arg1) throws java.io.IOException;
    boolean canWriteBinaryNatively();
    boolean isEnabled(com.fasterxml.jackson.core.StreamWriteFeature arg0);
    JsonGeneratorInterface overrideStdFeatures(int arg0, int arg1);
    void writeRawValue(java.lang.String arg0) throws java.io.IOException;
    JsonGeneratorInterface setHighestNonEscapedChar(int arg0);
    int getOutputBuffered();
    void writeNumber(java.lang.String arg0) throws java.io.IOException;
    void writeStartArray(int arg0) throws java.io.IOException;
    void writeObject(java.lang.Object arg0) throws java.io.IOException;
    void writeRawValue(java.lang.String arg0, int arg1, int arg2) throws java.io.IOException;
    void writeNumber(long arg0) throws java.io.IOException;
    void writeNumber(double arg0) throws java.io.IOException;
    JsonGeneratorInterface setCharacterEscapes(CharacterEscapesInterface arg0);
    void writeNumberField(java.lang.String arg0, int arg1) throws java.io.IOException;
    void writeBinary(Base64VariantInterface arg0, byte[] arg1, int arg2, int arg3) throws java.io.IOException;
    void setSchema(com.fasterxml.jackson.core.FormatSchema arg0);
    void writeRawUTF8String(byte[] arg0, int arg1, int arg2) throws java.io.IOException;
    void writeFieldName(java.lang.String arg0) throws java.io.IOException;
    void writeStartObject(java.lang.Object arg0) throws java.io.IOException;
    void writeStartArray() throws java.io.IOException;
    void writeBinary(byte[] arg0, int arg1, int arg2) throws java.io.IOException;
    void writeRawValue(char[] arg0, int arg1, int arg2) throws java.io.IOException;
    void writeObjectRef(java.lang.Object arg0) throws java.io.IOException;
    void writeRaw(char arg0) throws java.io.IOException;
    void flush() throws java.io.IOException;
    java.lang.Object getCurrentValue();
    JsonGeneratorInterface enable(com.fasterxml.jackson.core.JsonGenerator.Feature arg0);
    WritableTypeIdInterface writeTypePrefix(WritableTypeIdInterface arg0) throws java.io.IOException;
    boolean canWriteTypeId();
    void _throwInternal();
    boolean canOmitFields();
    com.fasterxml.jackson.core.PrettyPrinter getPrettyPrinter();
    void writeNumber(int arg0) throws java.io.IOException;
    void writeStringField(java.lang.String arg0, java.lang.String arg1) throws java.io.IOException;
    boolean isEnabled(com.fasterxml.jackson.core.JsonGenerator.Feature arg0);
    JsonGeneratorInterface setPrettyPrinter(com.fasterxml.jackson.core.PrettyPrinter arg0);
    void writeNumber(float arg0) throws java.io.IOException;
    void writeArray(java.lang.String[] arg0, int arg1, int arg2) throws java.io.IOException;
    JsonGeneratorInterface configure(com.fasterxml.jackson.core.JsonGenerator.Feature arg0, boolean arg1);
    void writeObjectId(java.lang.Object arg0) throws java.io.IOException;
    void writeString(com.fasterxml.jackson.core.SerializableString arg0) throws java.io.IOException;
    void writeNull() throws java.io.IOException;
    WritableTypeIdInterface writeTypeSuffix(WritableTypeIdInterface arg0) throws java.io.IOException;
    com.fasterxml.jackson.core.FormatSchema getSchema();
    void writeNumber(char[] arg0, int arg1, int arg2) throws java.io.IOException;
    void _copyCurrentContents(JsonParserInterface arg0) throws java.io.IOException;
    void writeFieldName(com.fasterxml.jackson.core.SerializableString arg0) throws java.io.IOException;
    void writeNumberField(java.lang.String arg0, float arg1) throws java.io.IOException;
    void writeNumberField(java.lang.String arg0, java.math.BigInteger arg1) throws java.io.IOException;
    void copyCurrentEvent(JsonParserInterface arg0) throws java.io.IOException;
    void writeArray(double[] arg0, int arg1, int arg2) throws java.io.IOException;
    void writeNullField(java.lang.String arg0) throws java.io.IOException;
    boolean isClosed();
    void copyCurrentStructure(JsonParserInterface arg0) throws java.io.IOException;
    void writeTypeId(java.lang.Object arg0) throws java.io.IOException;
    void writeObjectField(java.lang.String arg0, java.lang.Object arg1) throws java.io.IOException;
}