package org.apache.hadoop.hdfs.remoteProxies;

public interface MethodDescriptorProtoInterface {
    java.lang.String getName();
    boolean equals(java.lang.Object arg0);
    MethodDescriptorProtoInterface parseDelimitedFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    <K, V> void serializeMapTo(CodedOutputStreamInterface arg0, java.util.Map<K, V> arg1, MapEntryInterface<K, V> arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder toBuilder();
    BuilderInterface newBuilder(MethodDescriptorProtoInterface arg0);
    boolean hasOptions();
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList emptyBooleanList();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    <V> void serializeStringMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.String, V> arg1, MapEntryInterface<java.lang.String, V> arg2, int arg3) throws java.io.IOException;
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1) throws java.io.IOException;
    java.lang.reflect.Method getMethodOrDie(java.lang.Class arg0, java.lang.String arg1, java.lang.Class... arg2);
//    BuilderInterface toBuilder();
    MethodDescriptorProtoInterface parseFrom(java.nio.ByteBuffer arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    java.util.Map convertMapEntryListToMap(java.util.List arg0);
    boolean hasClientStreaming();
    void writeString(CodedOutputStreamInterface arg0, int arg1, java.lang.Object arg2) throws java.io.IOException;
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    ByteStringInterface toByteString();
    java.lang.Object getRepeatedField(FieldDescriptorInterface arg0, int arg1);
    void enableAlwaysUseFieldBuildersForTesting();
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    ByteStringInterface getOutputTypeBytes();
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.MethodOptionsOrBuilder getOptionsOrBuilder();
    ByteStringInterface toByteString(java.lang.Object arg0);
    void checkByteStringIsUtf8(ByteStringInterface arg0) throws java.lang.IllegalArgumentException;
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFields();
    java.util.List<java.lang.String> findInitializationErrors();
    MapFieldInterface internalGetMapField(int arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList newDoubleList();
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList emptyDoubleList();
    <V> void serializeIntegerMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Integer, V> arg1, MapEntryInterface<java.lang.Integer, V> arg2, int arg3) throws java.io.IOException;
    UnknownFieldSetInterface getUnknownFields();
    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder newBuilderForType();
    void makeExtensionsImmutable();
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList emptyLongList();
//    BuilderInterface newBuilderForType();
    java.lang.String getInitializationErrorString();
    int hashLong(long arg0);
    org.apache.hadoop.thirdparty.protobuf.Message getDefaultInstanceForType();
    <V> void serializeLongMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Long, V> arg1, MapEntryInterface<java.lang.Long, V> arg2, int arg3) throws java.io.IOException;
    boolean compareFields(java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.AbstractMessage.BuilderParent arg0);
    int computeStringSize(int arg0, java.lang.Object arg1);
    FieldAccessorTableInterface internalGetFieldAccessorTable();
    boolean getClientStreaming();
    MethodDescriptorProtoInterface parseFrom(java.nio.ByteBuffer arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    MethodOptionsInterface getOptions();
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList newBooleanList();
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.FloatList arg0);
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.List<? super T> arg1);
    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.Message> getParserForType();
    int getSerializedSize();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder toBuilder();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType();
    MethodDescriptorProtoInterface getDefaultInstance();
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.LongList arg0);
    void setMemoizedSerializedSize(int arg0);
    java.lang.String toString();
    boolean hasName();
    java.lang.String getOutputType();
    java.lang.String getSerializingExceptionMessage(java.lang.String arg0);
    MethodDescriptorProtoInterface parseFrom(CodedInputStreamInterface arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    byte[] toByteArray();
    java.lang.Object getFieldRaw(FieldDescriptorInterface arg0);
    int hashEnum(org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite arg0);
//    org.apache.hadoop.thirdparty.protobuf.MessageLite getDefaultInstanceForType();
    DescriptorInterface getDescriptor();
    MethodDescriptorProtoInterface parseFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    BuilderInterface newBuilder();
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3> getParserForType();
    int getMemoizedSerializedSize();
    boolean compareBytes(java.lang.Object arg0, java.lang.Object arg1);
    void writeTo(java.io.OutputStream arg0) throws java.io.IOException;
    <MessageType, T> ExtensionInterface<MessageType, T> checkNotLite(ExtensionLiteInterface<MessageType, T> arg0);
    MethodDescriptorProtoInterface parseFrom(byte[] arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    boolean parseUnknownFieldProto3(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    void writeStringNoTag(CodedOutputStreamInterface arg0, java.lang.Object arg1) throws java.io.IOException;
    MethodDescriptorProtoInterface parseFrom(ByteStringInterface arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    FieldDescriptorInterface getOneofFieldDescriptor(OneofDescriptorInterface arg0);
    MethodDescriptorProtoInterface parseFrom(java.io.InputStream arg0) throws java.io.IOException;
    void writeDelimitedTo(java.io.OutputStream arg0) throws java.io.IOException;
    <V> void maybeSerializeBooleanEntryTo(CodedOutputStreamInterface arg0, java.util.Map<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3, boolean arg4) throws java.io.IOException;
    UninitializedMessageExceptionInterface newUninitializedMessageException();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    java.lang.Object writeReplace() throws java.io.ObjectStreamException;
    <V> void serializeBooleanMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3) throws java.io.IOException;
    java.lang.Object getField(FieldDescriptorInterface arg0);
    boolean hasServerStreaming();
    boolean hasField(FieldDescriptorInterface arg0);
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsRaw();
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList newLongList();
    boolean hasOutputType();
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.IntList arg0);
    MethodDescriptorProtoInterface parseDelimitedFrom(java.io.InputStream arg0) throws java.io.IOException;
    int hashBoolean(boolean arg0);
    boolean compareMapField(java.lang.Object arg0, java.lang.Object arg1);
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
    int getRepeatedFieldCount(FieldDescriptorInterface arg0);
    ByteStringInterface getNameBytes();
    MethodDescriptorProtoInterface parseFrom(byte[] arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    int hashEnumList(java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite> arg0);
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.Collection<? super T> arg1);
    MethodDescriptorProtoInterface parseFrom(CodedInputStreamInterface arg0) throws java.io.IOException;
    int computeStringSizeNoTag(java.lang.Object arg0);
    boolean canUseUnsafe();
    MethodDescriptorProtoInterface parseFrom(ByteStringInterface arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    int hashMapField(java.lang.Object arg0);
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.MessageLite> getParserForType();
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList arg0);
//    MethodDescriptorProtoInterface getDefaultInstanceForType();
    void writeTo(CodedOutputStreamInterface arg0) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList newFloatList();
    DescriptorInterface getDescriptorForType();
    java.lang.String getInputType();
    boolean hasOneof(OneofDescriptorInterface arg0);
    java.lang.Object invokeOrDie(java.lang.reflect.Method arg0, java.lang.Object arg1, java.lang.Object... arg2);
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList newIntList();
    boolean isInitialized();
    boolean parseUnknownField(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    boolean getServerStreaming();
    ByteStringInterface getInputTypeBytes();
    int hashFields(int arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsMutable(boolean arg0);
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.MethodDescriptorProto> parser();
//    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.MethodDescriptorProto> getParserForType();
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList emptyFloatList();
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList emptyIntList();
    int hashCode();
    boolean hasInputType();
//    BuilderInterface newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
}