package org.apache.hadoop.hdfs.remoteProxies;

public interface RpcResponseHeaderProtoInterface {
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList newFloatList();
    int hashFields(int arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    void makeExtensionsImmutable();
    <V> void serializeBooleanMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3) throws java.io.IOException;
    <K, V> void serializeMapTo(CodedOutputStreamInterface arg0, java.util.Map<K, V> arg1, MapEntryInterface<K, V> arg2, int arg3) throws java.io.IOException;
    RpcResponseHeaderProtoInterface parseFrom(byte[] arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.Collection<? super T> arg1);
    <V> void serializeStringMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.String, V> arg1, MapEntryInterface<java.lang.String, V> arg2, int arg3) throws java.io.IOException;
    void writeTo(CodedOutputStreamInterface arg0) throws java.io.IOException;
//    BuilderInterface newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList emptyBooleanList();
    boolean parseUnknownField(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    java.lang.Object writeReplace() throws java.io.ObjectStreamException;
    boolean hasExceptionClassName();
    int hashBoolean(boolean arg0);
    void enableAlwaysUseFieldBuildersForTesting();
    void writeDelimitedTo(java.io.OutputStream arg0) throws java.io.IOException;
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    int getServerIpcVersionNum();
    java.lang.String getSerializingExceptionMessage(java.lang.String arg0);
    boolean hasErrorDetail();
    RpcResponseHeaderProtoInterface getDefaultInstanceForType();
    void writeTo(java.io.OutputStream arg0) throws java.io.IOException;
    int hashMapField(java.lang.Object arg0);
    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.Message> getParserForType();
    boolean hasServerIpcVersionNum();
    boolean compareMapField(java.lang.Object arg0, java.lang.Object arg1);
    ByteStringInterface getExceptionClassNameBytes();
    long getStateId();
    org.apache.hadoop.ipc.protobuf.RpcHeaderProtos.RpcResponseHeaderProto.RpcStatusProto getStatus();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.FloatList arg0);
    ByteStringInterface getClientId();
    int hashEnum(org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite arg0);
    int computeStringSizeNoTag(java.lang.Object arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList arg0);
    int getRepeatedFieldCount(FieldDescriptorInterface arg0);
    boolean hasOneof(OneofDescriptorInterface arg0);
    ByteStringInterface getRouterFederatedState();
    void writeStringNoTag(CodedOutputStreamInterface arg0, java.lang.Object arg1) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.MessageLite getDefaultInstanceForType();
    void writeString(CodedOutputStreamInterface arg0, int arg1, java.lang.Object arg2) throws java.io.IOException;
    boolean parseUnknownFieldProto3(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    boolean hasErrorMsg();
    java.lang.String toString();
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList emptyLongList();
    RpcResponseHeaderProtoInterface parseFrom(ByteStringInterface arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    int hashEnumList(java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite> arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.IntList arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList newBooleanList();
    java.lang.String getExceptionClassName();
    RpcResponseHeaderProtoInterface parseFrom(java.io.InputStream arg0) throws java.io.IOException;
    java.lang.String getErrorMsg();
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.List<? super T> arg1);
    int hashCode();
    RpcResponseHeaderProtoInterface parseFrom(java.nio.ByteBuffer arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList newLongList();
    int getSerializedSize();
    <MessageType, T> ExtensionInterface<MessageType, T> checkNotLite(ExtensionLiteInterface<MessageType, T> arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.LongList arg0);
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.ipc.protobuf.RpcHeaderProtos.RpcResponseHeaderProto> getParserForType();
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsMutable(boolean arg0);
    FieldAccessorTableInterface internalGetFieldAccessorTable();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    DescriptorInterface getDescriptorForType();
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsRaw();
    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.ipc.protobuf.RpcHeaderProtos.RpcResponseHeaderProto> parser();
    org.apache.hadoop.ipc.protobuf.RpcHeaderProtos.RpcResponseHeaderProto.RpcErrorCodeProto getErrorDetail();
    boolean hasStateId();
    java.lang.reflect.Method getMethodOrDie(java.lang.Class arg0, java.lang.String arg1, java.lang.Class... arg2);
    BuilderInterface newBuilder();
    UninitializedMessageExceptionInterface newUninitializedMessageException();
    boolean hasCallId();
    RpcResponseHeaderProtoInterface parseFrom(ByteStringInterface arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    boolean hasClientId();
    MapFieldInterface internalGetMapField(int arg0);
    RpcResponseHeaderProtoInterface parseFrom(java.nio.ByteBuffer arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    RpcResponseHeaderProtoInterface getDefaultInstance();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    ByteStringInterface getErrorMsgBytes();
    java.lang.Object getRepeatedField(FieldDescriptorInterface arg0, int arg1);
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList emptyDoubleList();
    UnknownFieldSetInterface getUnknownFields();
    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder toBuilder();
    int hashLong(long arg0);
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.MessageLite> getParserForType();
    FieldDescriptorInterface getOneofFieldDescriptor(OneofDescriptorInterface arg0);
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFields();
    boolean isInitialized();
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3> getParserForType();
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList emptyIntList();
    boolean compareBytes(java.lang.Object arg0, java.lang.Object arg1);
    boolean canUseUnsafe();
    java.lang.String getInitializationErrorString();
//    BuilderInterface toBuilder();
    java.lang.Object getField(FieldDescriptorInterface arg0);
    RpcResponseHeaderProtoInterface parseFrom(CodedInputStreamInterface arg0) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList newIntList();
    boolean hasRetryCount();
    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder newBuilderForType();
    RpcResponseHeaderProtoInterface parseFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    int computeStringSize(int arg0, java.lang.Object arg1);
    java.lang.Object invokeOrDie(java.lang.reflect.Method arg0, java.lang.Object arg1, java.lang.Object... arg2);
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder toBuilder();
    ByteStringInterface toByteString(java.lang.Object arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList emptyFloatList();
//    org.apache.hadoop.thirdparty.protobuf.Message getDefaultInstanceForType();
    int getRetryCount();
    RpcResponseHeaderProtoInterface parseFrom(CodedInputStreamInterface arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
    void setMemoizedSerializedSize(int arg0);
    byte[] toByteArray();
    java.lang.Object getFieldRaw(FieldDescriptorInterface arg0);
    <V> void maybeSerializeBooleanEntryTo(CodedOutputStreamInterface arg0, java.util.Map<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3, boolean arg4) throws java.io.IOException;
    <V> void serializeIntegerMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Integer, V> arg1, MapEntryInterface<java.lang.Integer, V> arg2, int arg3) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.AbstractMessage.BuilderParent arg0);
    RpcResponseHeaderProtoInterface parseDelimitedFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    boolean hasField(FieldDescriptorInterface arg0);
    DescriptorInterface getDescriptor();
    BuilderInterface newBuilder(RpcResponseHeaderProtoInterface arg0);
    int getCallId();
    ByteStringInterface toByteString();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
    int getMemoizedSerializedSize();
    boolean hasRouterFederatedState();
    RpcResponseHeaderProtoInterface parseDelimitedFrom(java.io.InputStream arg0) throws java.io.IOException;
    <V> void serializeLongMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Long, V> arg1, MapEntryInterface<java.lang.Long, V> arg2, int arg3) throws java.io.IOException;
    boolean compareFields(java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    boolean hasStatus();
    RpcResponseHeaderProtoInterface parseFrom(byte[] arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType();
    boolean equals(java.lang.Object arg0);
    java.util.Map convertMapEntryListToMap(java.util.List arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList newDoubleList();
    java.util.List<java.lang.String> findInitializationErrors();
//    BuilderInterface newBuilderForType();
    void checkByteStringIsUtf8(ByteStringInterface arg0) throws java.lang.IllegalArgumentException;
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList arg0);
}