package org.apache.hadoop.hdfs.remoteProxies;

public interface SaslAuthInterface {
    int computeStringSize(int arg0, java.lang.Object arg1);
    UnknownFieldSetInterface getUnknownFields();
    boolean hasMechanism();
    FieldAccessorTableInterface internalGetFieldAccessorTable();
    void writeTo(CodedOutputStreamInterface arg0) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Message.Builder toBuilder();
    boolean equals(java.lang.Object arg0);
    java.util.List<java.lang.String> findInitializationErrors();
//    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder toBuilder();
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList newFloatList();
    void writeTo(java.io.OutputStream arg0) throws java.io.IOException;
    SaslAuthInterface parseFrom(ByteStringInterface arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    SaslAuthInterface parseDelimitedFrom(java.io.InputStream arg0) throws java.io.IOException;
    int hashFields(int arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    void enableAlwaysUseFieldBuildersForTesting();
    ByteStringInterface getMechanismBytes();
    BuilderInterface newBuilderForType();
    void writeDelimitedTo(java.io.OutputStream arg0) throws java.io.IOException;
//    BuilderInterface newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    <V> void serializeStringMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.String, V> arg1, MapEntryInterface<java.lang.String, V> arg2, int arg3) throws java.io.IOException;
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    ByteStringInterface getMethodBytes();
    ByteStringInterface getServerIdBytes();
    int getSerializedSize();
    boolean parseUnknownFieldProto3(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.Message> getParserForType();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    java.lang.String getMechanism();
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList newBooleanList();
    boolean compareMapField(java.lang.Object arg0, java.lang.Object arg1);
    int hashEnumList(java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite> arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList emptyDoubleList();
    SaslAuthInterface parseFrom(byte[] arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    java.lang.String getMethod();
    SaslAuthInterface parseDelimitedFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    boolean hasChallenge();
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList arg0);
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3> getParserForType();
    java.lang.String getSerializingExceptionMessage(java.lang.String arg0);
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
//    BuilderInterface toBuilder();
    ByteStringInterface toByteString();
    boolean parseUnknownField(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    int hashEnum(org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite arg0);
//    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder newBuilderForType();
    java.lang.Object getFieldRaw(FieldDescriptorInterface arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.LongList arg0);
    boolean compareFields(java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    SaslAuthInterface parseFrom(java.nio.ByteBuffer arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    int hashLong(long arg0);
    FieldDescriptorInterface getOneofFieldDescriptor(OneofDescriptorInterface arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList newLongList();
    void writeStringNoTag(CodedOutputStreamInterface arg0, java.lang.Object arg1) throws java.io.IOException;
    boolean hasOneof(OneofDescriptorInterface arg0);
    int hashCode();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    <K, V> void serializeMapTo(CodedOutputStreamInterface arg0, java.util.Map<K, V> arg1, MapEntryInterface<K, V> arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList emptyFloatList();
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList emptyBooleanList();
    MapFieldInterface internalGetMapField(int arg0);
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.List<? super T> arg1);
    DescriptorInterface getDescriptorForType();
    boolean hasProtocol();
    ByteStringInterface toByteString(java.lang.Object arg0);
    SaslAuthInterface getDefaultInstance();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.AbstractMessage.BuilderParent arg0);
//    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.ipc.protobuf.RpcHeaderProtos.RpcSaslProto.SaslAuth> getParserForType();
    boolean hasServerId();
    byte[] toByteArray();
    boolean hasMethod();
    java.lang.String getProtocol();
    SaslAuthInterface parseFrom(java.io.InputStream arg0) throws java.io.IOException;
    SaslAuthInterface getDefaultInstanceForType();
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsMutable(boolean arg0);
    java.lang.Object writeReplace() throws java.io.ObjectStreamException;
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.MessageLite> getParserForType();
    DescriptorInterface getDescriptor();
    int getMemoizedSerializedSize();
    UninitializedMessageExceptionInterface newUninitializedMessageException();
    SaslAuthInterface parseFrom(CodedInputStreamInterface arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.Message getDefaultInstanceForType();
    <V> void maybeSerializeBooleanEntryTo(CodedOutputStreamInterface arg0, java.util.Map<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3, boolean arg4) throws java.io.IOException;
    void writeString(CodedOutputStreamInterface arg0, int arg1, java.lang.Object arg2) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.MessageLite getDefaultInstanceForType();
    void setMemoizedSerializedSize(int arg0);
    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.ipc.protobuf.RpcHeaderProtos.RpcSaslProto.SaslAuth> parser();
    boolean compareBytes(java.lang.Object arg0, java.lang.Object arg1);
    java.lang.String getInitializationErrorString();
    <V> void serializeBooleanMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3) throws java.io.IOException;
    SaslAuthInterface parseFrom(java.nio.ByteBuffer arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    int getRepeatedFieldCount(FieldDescriptorInterface arg0);
    <MessageType, T> ExtensionInterface<MessageType, T> checkNotLite(ExtensionLiteInterface<MessageType, T> arg0);
    BuilderInterface newBuilder(SaslAuthInterface arg0);
    void makeExtensionsImmutable();
    <V> void serializeIntegerMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Integer, V> arg1, MapEntryInterface<java.lang.Integer, V> arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList newDoubleList();
    boolean hasField(FieldDescriptorInterface arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList arg0);
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsRaw();
    <V> void serializeLongMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Long, V> arg1, MapEntryInterface<java.lang.Long, V> arg2, int arg3) throws java.io.IOException;
    boolean isInitialized();
    java.util.Map convertMapEntryListToMap(java.util.List arg0);
    java.lang.Object getField(FieldDescriptorInterface arg0);
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType();
    SaslAuthInterface parseFrom(ByteStringInterface arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.IntList arg0);
    void checkByteStringIsUtf8(ByteStringInterface arg0) throws java.lang.IllegalArgumentException;
    SaslAuthInterface parseFrom(byte[] arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList emptyIntList();
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFields();
    java.lang.Object invokeOrDie(java.lang.reflect.Method arg0, java.lang.Object arg1, java.lang.Object... arg2);
    java.lang.Object getRepeatedField(FieldDescriptorInterface arg0, int arg1);
    int hashMapField(java.lang.Object arg0);
    boolean canUseUnsafe();
    SaslAuthInterface parseFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    SaslAuthInterface parseFrom(CodedInputStreamInterface arg0) throws java.io.IOException;
    ByteStringInterface getChallenge();
    java.lang.String toString();
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.FloatList arg0);
    int hashBoolean(boolean arg0);
    ByteStringInterface getProtocolBytes();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1) throws java.io.IOException;
    java.lang.reflect.Method getMethodOrDie(java.lang.Class arg0, java.lang.String arg1, java.lang.Class... arg2);
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    int computeStringSizeNoTag(java.lang.Object arg0);
    java.lang.String getServerId();
    BuilderInterface newBuilder();
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList newIntList();
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList emptyLongList();
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.Collection<? super T> arg1);
}