package org.apache.hadoop.hdfs.remoteProxies;

public interface SecurityHandlerInterface {
    void setStopped();
    void manage(java.lang.Object arg0);
    void destroy();
    void insertHandler(HandlerWrapperInterface arg0);
    boolean checkWebResourcePermissions(java.lang.String arg0, RequestInterface arg1, ResponseInterface arg2, java.lang.Object arg3, org.eclipse.jetty.server.UserIdentity arg4) throws java.io.IOException;
    void setAuthenticatorFactory(org.eclipse.jetty.security.Authenticator.Factory arg0);
    void logout(org.eclipse.jetty.server.Authentication.User arg0);
    boolean addBean(java.lang.Object arg0);
    BeanInterface getBean(java.lang.Object arg0);
    void lambda$named$0(java.lang.String arg0, java.lang.Object arg1, java.lang.Appendable arg2, java.lang.String arg3) throws java.io.IOException;
    void setStopping();
    java.lang.String setInitParameter(java.lang.String arg0, java.lang.String arg1);
    void dump(java.lang.Appendable arg0, java.lang.String arg1, java.util.Collection<?>... arg2) throws java.io.IOException;
    org.eclipse.jetty.server.Handler[] getHandlers();
    void handle(java.lang.String arg0, RequestInterface arg1, javax.servlet.http.HttpServletRequest arg2, javax.servlet.http.HttpServletResponse arg3) throws java.io.IOException, javax.servlet.ServletException;
    org.eclipse.jetty.security.IdentityService getIdentityService();
    void start(java.lang.Object arg0);
    void start() throws java.lang.Exception;
    void removeEventListener(org.eclipse.jetty.util.component.Container.Listener arg0);
    void stop(java.lang.Object arg0);
    void doShutdown(java.util.List<java.util.concurrent.Future<java.lang.Void>> arg0) throws org.eclipse.jetty.util.MultiException;
    void dumpObjects(java.lang.Appendable arg0, java.lang.String arg1, java.lang.Object... arg2) throws java.io.IOException;
    <T> void getContainedBeans(java.lang.Class<T> arg0, java.util.Collection<T> arg1);
    void setStopTimeout(long arg0);
    ServerInterface getServer();
    void dumpContainer(java.lang.Appendable arg0, java.lang.String arg1, org.eclipse.jetty.util.component.Container arg2, boolean arg3) throws java.io.IOException;
    void setAuthMethod(java.lang.String arg0);
    void dump(java.lang.Appendable arg0) throws java.io.IOException;
    void updateBean(java.lang.Object arg0, java.lang.Object arg1, boolean arg2);
//    boolean addBean(java.lang.Object arg0, org.eclipse.jetty.util.component.ContainerLifeCycle.Managed arg1);
    void dumpThis(java.lang.Appendable arg0) throws java.io.IOException;
    RoleInfoInterface prepareConstraintInfo(java.lang.String arg0, RequestInterface arg1);
    void doStop() throws java.lang.Exception;
    java.lang.String getRealmName();
    org.eclipse.jetty.security.LoginService getLoginService();
    org.eclipse.jetty.server.Handler[] getChildHandlers();
    <T> java.util.Collection<T> getBeans(java.lang.Class<T> arg0);
    void setStarted();
    void expandHandler(org.eclipse.jetty.server.Handler arg0, java.util.List<org.eclipse.jetty.server.Handler> arg1, java.lang.Class<?> arg2);
    java.lang.String dump(org.eclipse.jetty.util.component.Dumpable arg0);
    boolean isAuthMandatory(RequestInterface arg0, ResponseInterface arg1, java.lang.Object arg2);
    boolean isUnmanaged(java.lang.Object arg0);
    void dump(java.lang.Appendable arg0, java.lang.String arg1) throws java.io.IOException;
    void manage(BeanInterface arg0);
    boolean isStopped();
    java.lang.String dumpSelf();
    void dumpMapEntries(java.lang.Appendable arg0, java.lang.String arg1, java.util.Map<?, ?> arg2, boolean arg3) throws java.io.IOException;
    void addEventListener(org.eclipse.jetty.util.component.Container.Listener arg0);
    long getStopTimeout();
    java.lang.String dump();
    void removeLifeCycleListener(org.eclipse.jetty.util.component.LifeCycle.Listener arg0);
    void setSessionRenewedOnAuthentication(boolean arg0);
    void unmanage(BeanInterface arg0);
    boolean isAuto(java.lang.Object arg0);
    void updateBeans(java.lang.Object[] arg0, java.lang.Object[] arg1);
    void setCheckWelcomeFiles(boolean arg0);
    SecurityHandlerInterface getCurrentSecurityHandler();
    boolean remove(BeanInterface arg0);
    void setLoginService(org.eclipse.jetty.security.LoginService arg0);
    void addLifeCycleListener(org.eclipse.jetty.util.component.LifeCycle.Listener arg0);
    org.eclipse.jetty.security.Authenticator getAuthenticator();
    void dumpIterable(java.lang.Appendable arg0, java.lang.String arg1, java.lang.Iterable<?> arg2, boolean arg3) throws java.io.IOException;
    void stop() throws java.lang.Exception;
    boolean addBean(java.lang.Object arg0, boolean arg1);
    java.util.Collection<java.lang.Object> getBeans();
    void dumpObjects(java.lang.Appendable arg0, java.lang.String arg1, java.lang.Object arg2, java.lang.Object... arg3) throws java.io.IOException;
    boolean isCheckWelcomeFiles();
    boolean isRunning();
    org.eclipse.jetty.security.LoginService findLoginService() throws java.lang.Exception;
    void dumpStdErr();
    boolean isManaged(java.lang.Object arg0);
    void setAuthenticator(org.eclipse.jetty.security.Authenticator arg0);
    <T> T findContainerOf(org.eclipse.jetty.server.HandlerContainer arg0, java.lang.Class<T> arg1, org.eclipse.jetty.server.Handler arg2);
    void addManaged(org.eclipse.jetty.util.component.LifeCycle arg0);
    boolean isStarted();
    void setServer(ServerInterface arg0);
    java.lang.String toString();
    java.util.List<org.eclipse.jetty.security.Authenticator.Factory> getKnownAuthenticatorFactories();
    java.lang.String getAuthMethod();
    void removeBeans();
    java.lang.String getState();
    void dumpBeans(java.lang.Appendable arg0, java.lang.String arg1, java.util.Collection<?>... arg2) throws java.io.IOException;
    boolean checkUserDataPermissions(java.lang.String arg0, RequestInterface arg1, ResponseInterface arg2, RoleInfoInterface arg3) throws java.io.IOException;
    boolean removeBean(java.lang.Object arg0);
    <T> T getChildHandlerByClass(java.lang.Class<T> arg0);
    boolean isFailed();
    java.lang.String getInitParameter(java.lang.String arg0);
    boolean checkSecurity(RequestInterface arg0);
    void setRealmName(java.lang.String arg0);
    java.util.Set<java.lang.String> getInitParameterNames();
    void setBeans(java.util.Collection<java.lang.Object> arg0);
    void setHandler(org.eclipse.jetty.server.Handler arg0);
    <T> java.util.Collection<T> getContainedBeans(java.lang.Class<T> arg0);
    boolean isStarting();
    boolean isDumpable(java.lang.Object arg0);
    void doError(java.lang.String arg0, RequestInterface arg1, javax.servlet.http.HttpServletRequest arg2, javax.servlet.http.HttpServletResponse arg3) throws java.io.IOException, javax.servlet.ServletException;
    org.eclipse.jetty.util.component.Dumpable named(java.lang.String arg0, java.lang.Object arg1);
    org.eclipse.jetty.server.Handler getHandler();
    boolean isStopping();
    void stop(org.eclipse.jetty.util.component.LifeCycle arg0) throws java.lang.Exception;
    org.eclipse.jetty.security.Authenticator.Factory getAuthenticatorFactory();
    boolean contains(java.lang.Object arg0);
    void setFailed(java.lang.Throwable arg0);
    void expandChildren(java.util.List<org.eclipse.jetty.server.Handler> arg0, java.lang.Class<?> arg1);
    java.lang.String getState(org.eclipse.jetty.util.component.LifeCycle arg0);
    org.eclipse.jetty.security.IdentityService findIdentityService();
    boolean isSessionRenewedOnAuthentication();
    org.eclipse.jetty.server.Handler[] getChildHandlersByClass(java.lang.Class<?> arg0);
    void unmanage(java.lang.Object arg0);
    void updateBean(java.lang.Object arg0, java.lang.Object arg1);
    void dumpObject(java.lang.Appendable arg0, java.lang.Object arg1) throws java.io.IOException;
    void setStarting();
    <T> T getBean(java.lang.Class<T> arg0);
    void start(org.eclipse.jetty.util.component.LifeCycle arg0) throws java.lang.Exception;
    void setIdentityService(org.eclipse.jetty.security.IdentityService arg0);
    void doStart() throws java.lang.Exception;
}