package org.apache.hadoop.hdfs.remoteProxies;

public interface ServletContextHandlerInterface {
    org.eclipse.jetty.util.log.Logger getLogger();
    void destroyFilter(javax.servlet.Filter arg0);
    MimeTypesInterface getMimeTypes();
    ServletHolderInterface addServlet(java.lang.Class<? extends javax.servlet.Servlet> arg0, java.lang.String arg1);
    boolean isDurableListener(java.util.EventListener arg0);
    void callContextInitialized(javax.servlet.ServletContextListener arg0, ServletContextEventInterface arg1);
    java.lang.String dump(org.eclipse.jetty.util.component.Dumpable arg0);
    void addProgrammaticListener(java.util.EventListener arg0);
    void setBaseResource(ResourceInterface arg0);
    void removeAttribute(java.lang.String arg0);
    SecurityHandlerInterface newSecurityHandler();
    org.eclipse.jetty.server.Handler[] getHandlers();
    void removeEventListener(org.eclipse.jetty.util.component.Container.Listener arg0);
    void setHandler(org.eclipse.jetty.server.Handler arg0);
    void replaceHandler(HandlerWrapperInterface arg0, HandlerWrapperInterface arg1);
    boolean isProtectedTarget(java.lang.String arg0);
    SessionHandlerInterface newSessionHandler();
    void handle(RequestInterface arg0, java.lang.Runnable arg1);
    boolean isStopped();
    void addEventListener(java.util.EventListener arg0);
    boolean addBean(java.lang.Object arg0, boolean arg1);
    java.lang.String getResourceBase();
    java.lang.String getRequestContextPath();
    org.eclipse.jetty.util.component.Dumpable named(java.lang.String arg0, java.lang.Object arg1);
    java.lang.Class<? extends org.eclipse.jetty.security.SecurityHandler> getDefaultSecurityHandlerClass();
    void dumpObject(java.lang.Appendable arg0, java.lang.Object arg1) throws java.io.IOException;
    boolean isProgrammaticListener(java.util.EventListener arg0);
    boolean removeBean(java.lang.Object arg0);
    void removeEventListener(java.util.EventListener arg0);
    void updateBeans(java.lang.Object[] arg0, java.lang.Object[] arg1);
    void setStopTimeout(long arg0);
    java.lang.String[] getWelcomeFiles();
    void setCompactPath(boolean arg0);
    java.lang.String getLogNameSuffix();
    boolean removeAliasCheck(org.eclipse.jetty.server.handler.ContextHandler.AliasCheck arg0);
    boolean isUnmanaged(java.lang.Object arg0);
    void setManagedAttribute(java.lang.String arg0, java.lang.Object arg1);
    ResourceInterface getBaseResource();
    void clearAttributes();
    java.lang.ClassLoader getClassLoader();
    int getMaxFormContentSize();
    void addEventListener(org.eclipse.jetty.util.component.Container.Listener arg0);
    java.util.Enumeration<java.lang.String> getInitParameterNames();
    void setStopped();
    boolean isStarting();
    boolean isAuto(java.lang.Object arg0);
    <T> T getChildHandlerByClass(java.lang.Class<T> arg0);
    void dumpBeans(java.lang.Appendable arg0, java.lang.String arg1, java.util.Collection<?>... arg2) throws java.io.IOException;
    void doHandle(java.lang.String arg0, RequestInterface arg1, javax.servlet.http.HttpServletRequest arg2, javax.servlet.http.HttpServletResponse arg3) throws java.io.IOException, javax.servlet.ServletException;
    java.lang.String getState();
    boolean checkContext(java.lang.String arg0, RequestInterface arg1, javax.servlet.http.HttpServletResponse arg2) throws java.io.IOException;
    void start(java.lang.Object arg0);
    ContextInterface getServletContext();
    java.lang.String getDisplayName();
    DecoratedObjectFactoryInterface getObjectFactory();
    boolean addBean(java.lang.Object arg0);
    org.eclipse.jetty.util.Attributes unwrap(org.eclipse.jetty.util.Attributes arg0);
    void setDisplayName(java.lang.String arg0);
    javax.servlet.ServletRegistration.Dynamic dynamicHolderAdded(ServletHolderInterface arg0);
    GzipHandlerInterface getGzipHandler();
    java.lang.String dumpSelf();
    void manage(java.lang.Object arg0);
    void setStarted();
    ServletHandlerInterface newServletHandler();
    void dump(java.lang.Appendable arg0, java.lang.String arg1, java.util.Collection<?>... arg2) throws java.io.IOException;
    boolean isCompactPath();
    boolean isDumpable(java.lang.Object arg0);
    void setEventListeners(java.util.EventListener[] arg0);
    void dumpThis(java.lang.Appendable arg0) throws java.io.IOException;
    java.util.List<org.eclipse.jetty.server.handler.ContextHandler.AliasCheck> getAliasChecks();
    boolean checkAlias(java.lang.String arg0, ResourceInterface arg1);
    boolean contains(java.lang.Object arg0);
    void addDecorator(org.eclipse.jetty.servlet.ServletContextHandler.Decorator arg0);
    java.util.Set<java.lang.String> setServletSecurity(javax.servlet.ServletRegistration.Dynamic arg0, ServletSecurityElementInterface arg1);
    void doSetHandler(HandlerWrapperInterface arg0, org.eclipse.jetty.server.Handler arg1);
    java.lang.String getServerInfo();
    java.util.concurrent.Future<java.lang.Void> shutdown();
    void nextHandle(java.lang.String arg0, RequestInterface arg1, javax.servlet.http.HttpServletRequest arg2, javax.servlet.http.HttpServletResponse arg3) throws java.io.IOException, javax.servlet.ServletException;
    org.eclipse.jetty.server.Handler getHandler();
    void destroyListener(java.util.EventListener arg0);
    void setAttribute(java.lang.String arg0, java.lang.Object arg1);
    java.lang.String[] getProtectedTargets();
    void setMimeTypes(MimeTypesInterface arg0);
    void handle(java.lang.String arg0, RequestInterface arg1, javax.servlet.http.HttpServletRequest arg2, javax.servlet.http.HttpServletResponse arg3) throws java.io.IOException, javax.servlet.ServletException;
    void addManaged(org.eclipse.jetty.util.component.LifeCycle arg0);
    void expandHandler(org.eclipse.jetty.server.Handler arg0, java.util.List<org.eclipse.jetty.server.Handler> arg1, java.lang.Class<?> arg2);
    void setStarting();
    void dumpObjects(java.lang.Appendable arg0, java.lang.String arg1, java.lang.Object arg2, java.lang.Object... arg3) throws java.io.IOException;
    java.lang.Class<?> loadClass(java.lang.String arg0) throws java.lang.ClassNotFoundException;
    java.util.List<org.eclipse.jetty.servlet.ServletContextHandler.Decorator> getDecorators();
    void setDefaultSecurityHandlerClass(java.lang.Class<? extends org.eclipse.jetty.security.SecurityHandler> arg0);
    void addFilter(FilterHolderInterface arg0, java.lang.String arg1, java.util.EnumSet<javax.servlet.DispatcherType> arg2);
    boolean isRunning();
    boolean remove(BeanInterface arg0);
    void setErrorHandler(ErrorHandlerInterface arg0);
    void dumpIterable(java.lang.Appendable arg0, java.lang.String arg1, java.lang.Iterable<?> arg2, boolean arg3) throws java.io.IOException;
    void relinkHandlers();
    void requestDestroyed(RequestInterface arg0, javax.servlet.http.HttpServletRequest arg1);
    boolean isManaged(java.lang.Object arg0);
    void enterScope(RequestInterface arg0, java.lang.Object arg1);
    boolean checkContextPath(java.lang.String arg0);
    java.util.Set<java.lang.String> getResourcePaths(java.lang.String arg0);
    void setAvailable(boolean arg0);
    java.lang.String getLocaleEncoding(java.lang.String arg0);
    java.util.Enumeration<java.lang.String> getAttributeNames();
    java.lang.Object getAttribute(java.lang.String arg0);
    void setFailed(java.lang.Throwable arg0);
    void setClassLoader(java.lang.ClassLoader arg0);
    void setGzipHandler(GzipHandlerInterface arg0);
    void requestInitialized(RequestInterface arg0, javax.servlet.http.HttpServletRequest arg1);
    void stopContext() throws java.lang.Exception;
    void setAllowNullPathInfo(boolean arg0);
    ContextInterface getCurrentContext();
    java.lang.String getContextPathEncoded();
    <T> java.util.Collection<T> getContainedBeans(java.lang.Class<T> arg0);
    void stop(org.eclipse.jetty.util.component.LifeCycle arg0) throws java.lang.Exception;
    void setVirtualHosts(java.lang.String[] arg0);
    java.lang.String normalizeHostname(java.lang.String arg0);
    SecurityHandlerInterface getSecurityHandler();
    void start() throws java.lang.Exception;
    void doStart() throws java.lang.Exception;
    void setServerInfo(java.lang.String arg0);
    void setSessionHandler(SessionHandlerInterface arg0);
    void doStop() throws java.lang.Exception;
    void setMaxFormContentSize(int arg0);
    java.lang.String getLocaleEncoding(java.util.Locale arg0);
    void removeBeans();
    void removeVirtualHosts(java.lang.String[] arg0);
    void doShutdown(java.util.List<java.util.concurrent.Future<java.lang.Void>> arg0) throws org.eclipse.jetty.util.MultiException;
    org.eclipse.jetty.server.Handler[] getChildHandlersByClass(java.lang.Class<?> arg0);
    boolean isShutdown();
    void addVirtualHosts(java.lang.String[] arg0);
    org.eclipse.jetty.util.Attributes getAttributes();
    void dump(java.lang.Appendable arg0, java.lang.String arg1) throws java.io.IOException;
    void stop(java.lang.Object arg0);
    void nextScope(java.lang.String arg0, RequestInterface arg1, javax.servlet.http.HttpServletRequest arg2, javax.servlet.http.HttpServletResponse arg3) throws java.io.IOException, javax.servlet.ServletException;
    java.lang.String getState(org.eclipse.jetty.util.component.LifeCycle arg0);
    void doError(java.lang.String arg0, RequestInterface arg1, javax.servlet.http.HttpServletRequest arg2, javax.servlet.http.HttpServletResponse arg3) throws java.io.IOException, javax.servlet.ServletException;
    int getMaxFormKeys();
    void clearAliasChecks();
    void callContextDestroyed(javax.servlet.ServletContextListener arg0, ServletContextEventInterface arg1);
    java.util.Map<java.lang.String, java.lang.String> getLocaleEncodings();
    void startContext() throws java.lang.Exception;
    ResourceInterface newResource(java.net.URL arg0) throws java.io.IOException;
    long getStopTimeout();
    ServletContextHandlerInterface getServletContextHandler(javax.servlet.ServletContext arg0);
    void expandChildren(java.util.List<org.eclipse.jetty.server.Handler> arg0, java.lang.Class<?> arg1);
    ResourceInterface getResource(java.lang.String arg0) throws java.net.MalformedURLException;
    void setServer(ServerInterface arg0);
    ContextHandlerInterface getContextHandler(javax.servlet.ServletContext arg0);
    boolean getAllowNullPathInfo();
    <T> T findContainerOf(org.eclipse.jetty.server.HandlerContainer arg0, java.lang.Class<T> arg1, org.eclipse.jetty.server.Handler arg2);
    void updateBean(java.lang.Object arg0, java.lang.Object arg1, boolean arg2);
    void dumpContainer(java.lang.Appendable arg0, java.lang.String arg1, org.eclipse.jetty.util.component.Container arg2, boolean arg3) throws java.io.IOException;
    boolean isAvailable();
    java.lang.String dump();
    ServerInterface getServer();
    void handle(java.lang.Runnable arg0);
    void insertHandler(HandlerWrapperInterface arg0);
    void addLifeCycleListener(org.eclipse.jetty.util.component.LifeCycle.Listener arg0);
    void dump(java.lang.Appendable arg0) throws java.io.IOException;
    void contextInitialized() throws java.lang.Exception;
    SessionHandlerInterface getSessionHandler();
    java.lang.String getClassPath();
    ServletHandlerInterface getServletHandler();
    void setLogger(org.eclipse.jetty.util.log.Logger arg0);
    java.util.Set<java.lang.String> getAttributeNameSet();
    void setMaxFormKeys(int arg0);
    java.lang.String[] getVirtualHosts();
    boolean isFailed();
    void setServletHandler(ServletHandlerInterface arg0);
    void setBeans(java.util.Collection<java.lang.Object> arg0);
    void setProtectedTargets(java.lang.String[] arg0);
    void dumpStdErr();
    void exitScope(RequestInterface arg0);
    void setDecorators(java.util.List<org.eclipse.jetty.servlet.ServletContextHandler.Decorator> arg0);
    java.util.EventListener[] getEventListeners();
    java.lang.String getContextPath();
//    boolean addBean(java.lang.Object arg0, org.eclipse.jetty.util.component.ContainerLifeCycle.Managed arg1);
    void manage(BeanInterface arg0);
    java.util.Collection<java.lang.Object> getBeans();
    void doScope(java.lang.String arg0, RequestInterface arg1, javax.servlet.http.HttpServletRequest arg2, javax.servlet.http.HttpServletResponse arg3) throws java.io.IOException, javax.servlet.ServletException;
    java.lang.String toString();
    void dumpMapEntries(java.lang.Appendable arg0, java.lang.String arg1, java.util.Map<?, ?> arg2, boolean arg3) throws java.io.IOException;
    <T> java.util.Collection<T> getBeans(java.lang.Class<T> arg0);
    ServletHolderInterface addServlet(java.lang.String arg0, java.lang.String arg1);
    void destroy();
    void unmanage(BeanInterface arg0);
    ResourceInterface newResource(java.lang.String arg0) throws java.io.IOException;
    void addLocaleEncoding(java.lang.String arg0, java.lang.String arg1);
    void start(org.eclipse.jetty.util.component.LifeCycle arg0) throws java.lang.Exception;
    ResourceInterface newResource(java.net.URI arg0) throws java.io.IOException;
    boolean checkVirtualHost(RequestInterface arg0);
    java.lang.String setInitParameter(java.lang.String arg0, java.lang.String arg1);
    void setStopping();
    FilterHolderInterface addFilter(java.lang.Class<? extends javax.servlet.Filter> arg0, java.lang.String arg1, java.util.EnumSet<javax.servlet.DispatcherType> arg2);
    void setResourceBase(java.lang.String arg0);
    void setUsingSecurityManager(boolean arg0);
    void contextDestroyed() throws java.lang.Exception;
    void setSecurityHandler(SecurityHandlerInterface arg0);
    java.util.Map<java.lang.String, java.lang.String> getInitParams();
    void unmanage(java.lang.Object arg0);
    void lambda$named$0(java.lang.String arg0, java.lang.Object arg1, java.lang.Appendable arg2, java.lang.String arg3) throws java.io.IOException;
    void dumpObjects(java.lang.Appendable arg0, java.lang.String arg1, java.lang.Object... arg2) throws java.io.IOException;
    java.lang.String getInitParameter(java.lang.String arg0);
    void setAliasChecks(java.util.List<org.eclipse.jetty.server.handler.ContextHandler.AliasCheck> arg0);
    void removeLifeCycleListener(org.eclipse.jetty.util.component.LifeCycle.Listener arg0);
    void setContextPath(java.lang.String arg0);
    <T> T getBean(java.lang.Class<T> arg0);
    void stop() throws java.lang.Exception;
    void addRoles(java.lang.String... arg0);
    void addServlet(ServletHolderInterface arg0, java.lang.String arg1);
    ErrorHandlerInterface getErrorHandler();
    org.eclipse.jetty.server.Handler[] getChildHandlers();
    <T> void getContainedBeans(java.lang.Class<T> arg0, java.util.Collection<T> arg1);
    void updateBean(java.lang.Object arg0, java.lang.Object arg1);
    void addAliasCheck(org.eclipse.jetty.server.handler.ContextHandler.AliasCheck arg0);
    FilterHolderInterface addFilter(java.lang.String arg0, java.lang.String arg1, java.util.EnumSet<javax.servlet.DispatcherType> arg2);
    void destroyServlet(javax.servlet.Servlet arg0);
    BeanInterface getBean(java.lang.Object arg0);
    boolean isStarted();
    void setWelcomeFiles(java.lang.String[] arg0);
    boolean isUsingSecurityManager();
    void setAttributes(org.eclipse.jetty.util.Attributes arg0);
    boolean isStopping();
}