package org.apache.hadoop.hdfs.remoteProxies;

public interface ServletHolderInterface {
    void doStart() throws java.lang.Exception;
    ServletHandlerInterface getServletHandler();
    void predestroyServlet(javax.servlet.Servlet arg0);
    java.util.Map<java.lang.String, java.lang.String> getInitParameters();
    int getInitOrder();
    javax.servlet.Servlet getServletInstance();
    void setDisplayName(java.lang.String arg0);
    void setRunAsRole(java.lang.String arg0);
    UnavailableExceptionInterface getUnavailableException();
    boolean isEnabled();
//    void setInstance(T arg0);
    void dumpObjects(java.lang.Appendable arg0, java.lang.String arg1, java.lang.Object arg2, java.lang.Object... arg3) throws java.io.IOException;
    void setClassFrom(ServletHolderInterface arg0) throws javax.servlet.ServletException;
    boolean isAvailable();
    java.lang.String dump(org.eclipse.jetty.util.component.Dumpable arg0);
    boolean isJspServlet();
//    T getInstance();
//    <W> T wrap(T arg0, java.lang.Class<W> arg1, java.util.function.BiFunction<W, T, T> arg2);
    void prepare(RequestInterface arg0, javax.servlet.ServletRequest arg1, javax.servlet.ServletResponse arg2) throws javax.servlet.ServletException, javax.servlet.UnavailableException;
    javax.servlet.Servlet getServlet() throws javax.servlet.ServletException;
    java.lang.String getClassName();
    void setStarted();
    java.util.Map<java.lang.String, java.lang.String> getRoleRefMap();
    void setUserRoleLink(java.lang.String arg0, java.lang.String arg1);
    void setInitParameters(java.util.Map<java.lang.String, java.lang.String> arg0);
    boolean isStarted();
    javax.servlet.Servlet newInstance() throws javax.servlet.ServletException, java.lang.IllegalAccessException, java.lang.InstantiationException, java.lang.NoSuchMethodException, java.lang.reflect.InvocationTargetException;
    javax.servlet.Servlet ensureInstance() throws javax.servlet.ServletException;
    java.lang.String getContextPath();
    long getStopTimeout();
    void start() throws java.lang.Exception;
    int compareTo(ServletHolderInterface arg0);
    java.lang.String getJspPackagePrefix();
    java.lang.String getState(org.eclipse.jetty.util.component.LifeCycle arg0);
    void initServlet() throws javax.servlet.ServletException;
    boolean isRunning();
    void stop(java.lang.Object arg0);
    void handle(RequestInterface arg0, javax.servlet.ServletRequest arg1, javax.servlet.ServletResponse arg2) throws javax.servlet.ServletException, javax.servlet.UnavailableException, java.io.IOException;
    void setStopping();
    void illegalStateIfContextStarted();
//    void setHeldClass(java.lang.Class<? extends T> arg0);
    void removeLifeCycleListener(org.eclipse.jetty.util.component.LifeCycle.Listener arg0);
    boolean isFailed();
    void dumpIterable(java.lang.Appendable arg0, java.lang.String arg1, java.lang.Iterable<?> arg2, boolean arg3) throws java.io.IOException;
    java.lang.String toString();
//    T unwrap(T arg0);
    void start(java.lang.Object arg0);
    java.lang.String getName();
    void dumpObject(java.lang.Appendable arg0, java.lang.Object arg1) throws java.io.IOException;
    java.lang.String getPackageOfJspClass(java.lang.String arg0);
//    java.lang.Class<? extends T> getHeldClass();
    java.lang.String getInitParameter(java.lang.String arg0);
    javax.servlet.ServletRegistration.Dynamic getRegistration();
    void initMultiPart() throws java.lang.Exception;
    void setFailed(java.lang.Throwable arg0);
    void setServletHandler(ServletHandlerInterface arg0);
    void setStopped();
    void setInitOrder(int arg0);
    void addLifeCycleListener(org.eclipse.jetty.util.component.LifeCycle.Listener arg0);
    void initialize() throws java.lang.Exception;
    boolean isStarting();
    void setName(java.lang.String arg0);
    java.lang.String getNameOfJspClass(java.lang.String arg0);
    java.lang.String getDisplayName();
    void setForcedPath(java.lang.String arg0);
    void checkServletType() throws javax.servlet.UnavailableException;
    boolean isJspServlet(java.lang.String arg0);
    boolean isInstance();
    int hashCode();
    java.lang.String getUserRoleLink(java.lang.String arg0);
    void dump(java.lang.Appendable arg0, java.lang.String arg1) throws java.io.IOException;
    void dumpMapEntries(java.lang.Appendable arg0, java.lang.String arg1, java.util.Map<?, ?> arg2, boolean arg3) throws java.io.IOException;
    void detectJspContainer();
    void setClassName(java.lang.String arg0);
    org.eclipse.jetty.util.component.Dumpable named(java.lang.String arg0, java.lang.Object arg1);
    void setAsyncSupported(boolean arg0);
    void setEnabled(boolean arg0);
    void destroyInstance(java.lang.Object arg0);
    boolean isAsyncSupported();
    void setServlet(javax.servlet.Servlet arg0);
    java.lang.String getClassNameForJsp(java.lang.String arg0);
    void appendPath(java.lang.StringBuffer arg0, java.lang.String arg1);
    void stop() throws java.lang.Exception;
    java.lang.String getForcedPath();
    void setInitParameter(java.lang.String arg0, java.lang.String arg1);
    void initJspServlet() throws java.lang.Exception;
    void setStopTimeout(long arg0);
    boolean isStopped();
    void lambda$named$0(java.lang.String arg0, java.lang.Object arg1, java.lang.Appendable arg2, java.lang.String arg3) throws java.io.IOException;
    void doStop() throws java.lang.Exception;
    java.lang.String dumpSelf();
    void checkInitOnStartup();
    ContextHandlerInterface getContextHandler();
    javax.servlet.Servlet makeUnavailable(UnavailableExceptionInterface arg0);
    SourceInterface getSource();
    boolean isStopping();
    void dumpContainer(java.lang.Appendable arg0, java.lang.String arg1, org.eclipse.jetty.util.component.Container arg2, boolean arg3) throws java.io.IOException;
    boolean equals(java.lang.Object arg0);
    void setStarting();
    java.lang.String getState();
    java.lang.String getRunAsRole();
    java.util.Enumeration<java.lang.String> getInitParameterNames();
    java.lang.String dump();
    void makeUnavailable(java.lang.Throwable arg0);
}