package org.apache.hadoop.hdfs.remoteProxies;

public interface StorageInterface {
    boolean confirmFormat(java.lang.Iterable<? extends org.apache.hadoop.hdfs.server.common.Storage.FormatConfirmable> arg0, boolean arg1, boolean arg2) throws java.io.IOException;
    void nativeCopyFileUnbuffered(java.io.File arg0, java.io.File arg1, boolean arg2) throws java.io.IOException;
    void setFieldsFromProperties(java.util.Properties arg0, StorageDirectoryInterface arg1) throws java.io.IOException;
    java.util.Iterator<org.apache.hadoop.hdfs.server.common.Storage.StorageDirectory> dirIterator();
    void writeProperties(java.io.File arg0, StorageDirectoryInterface arg1) throws java.io.IOException;
    void unlockAll() throws java.io.IOException;
    java.lang.String getClusterIdFromColonSeparatedString(java.lang.String arg0);
    java.util.Properties readPropertiesFile(java.io.File arg0) throws java.io.IOException;
    void setStorageInfo(StorageInfoInterface arg0);
    int getNamespaceID();
    void checkStorageType(java.util.Properties arg0, StorageDirectoryInterface arg1) throws org.apache.hadoop.hdfs.server.common.InconsistentFSStateException;
    boolean is203LayoutVersion(int arg0);
    java.lang.String toString();
    void setServiceLayoutVersion(int arg0);
    java.lang.String toColonSeparatedString();
    java.lang.String getBuildVersion();
    boolean containsStorageDir(java.io.File arg0) throws java.io.IOException;
    void writeProperties(java.io.File arg0, java.util.Properties arg1) throws java.io.IOException;
    java.util.List<org.apache.hadoop.hdfs.server.common.Storage.StorageDirectory> getStorageDirs();
    void readProperties(StorageDirectoryInterface arg0) throws java.io.IOException;
    long getCTime();
    java.util.Iterator<org.apache.hadoop.hdfs.server.common.Storage.StorageDirectory> dirIterator(boolean arg0);
    boolean versionSupportsFederation(java.util.Map<java.lang.Integer, java.util.SortedSet<org.apache.hadoop.hdfs.protocol.LayoutVersion.LayoutFeature>> arg0);
    java.lang.String listStorageDirectories();
    java.util.Map<java.lang.Integer, java.util.SortedSet<org.apache.hadoop.hdfs.protocol.LayoutVersion.LayoutFeature>> getServiceLayoutFeatureMap();
    java.lang.String getProperty(java.util.Properties arg0, StorageDirectoryInterface arg1, java.lang.String arg2) throws org.apache.hadoop.hdfs.server.common.InconsistentFSStateException;
    void addStorageDir(StorageDirectoryInterface arg0);
    boolean isPreUpgradableLayout(StorageDirectoryInterface arg0) throws java.io.IOException;
    void rename(java.io.File arg0, java.io.File arg1) throws java.io.IOException;
    void setcTime(java.util.Properties arg0, StorageDirectoryInterface arg1) throws org.apache.hadoop.hdfs.server.common.InconsistentFSStateException;
    void deleteDir(java.io.File arg0) throws java.io.IOException;
    void setClusterId(java.util.Properties arg0, int arg1, StorageDirectoryInterface arg2) throws org.apache.hadoop.hdfs.server.common.InconsistentFSStateException;
    void readPreviousVersionProperties(StorageDirectoryInterface arg0) throws java.io.IOException;
    boolean containsStorageDir(StorageLocationInterface arg0) throws java.io.IOException;
    void checkOldLayoutStorage(StorageDirectoryInterface arg0) throws java.io.IOException;
    void setNamespaceID(java.util.Properties arg0, StorageDirectoryInterface arg1) throws org.apache.hadoop.hdfs.server.common.InconsistentFSStateException;
    int getServiceLayoutVersion();
    java.util.Iterator<org.apache.hadoop.hdfs.server.common.Storage.StorageDirectory> dirIterator(org.apache.hadoop.hdfs.server.common.Storage.StorageDirType arg0, boolean arg1);
    boolean containsStorageDir(StorageLocationInterface arg0, java.lang.String arg1) throws java.io.IOException;
    void setLayoutVersion(java.util.Properties arg0, StorageDirectoryInterface arg1) throws org.apache.hadoop.hdfs.server.common.IncorrectVersionException, org.apache.hadoop.hdfs.server.common.InconsistentFSStateException;
    java.lang.String getClusterID();
    void writeProperties(StorageDirectoryInterface arg0) throws java.io.IOException;
    java.lang.Iterable<org.apache.hadoop.hdfs.server.common.Storage.StorageDirectory> dirIterable(org.apache.hadoop.hdfs.server.common.Storage.StorageDirType arg0);
    int getLayoutVersion();
    java.util.Iterator<org.apache.hadoop.hdfs.server.common.Storage.StorageDirectory> dirIterator(org.apache.hadoop.hdfs.server.common.Storage.StorageDirType arg0);
    NamespaceInfoInterface getNamespaceInfo();
    void checkVersionUpgradable(int arg0) throws java.io.IOException;
    StorageDirectoryInterface getSingularStorageDir();
    java.lang.String getRegistrationID(StorageInfoInterface arg0);
    int getNsIdFromColonSeparatedString(java.lang.String arg0);
    void writeAll() throws java.io.IOException;
    int getNumStorageDirs();
    StorageDirectoryInterface getStorageDir(int arg0);
    void setPropertiesFromFields(java.util.Properties arg0, StorageDirectoryInterface arg1) throws java.io.IOException;
    java.util.List<java.io.File> getFiles(org.apache.hadoop.hdfs.server.common.Storage.StorageDirType arg0, java.lang.String arg1);
}