package org.apache.hadoop.hdfs.remoteProxies;

public interface TokenProtoInterface {
    boolean hasPassword();
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList newIntList();
    void writeTo(java.io.OutputStream arg0) throws java.io.IOException;
    java.util.Map convertMapEntryListToMap(java.util.List arg0);
    TokenProtoInterface parseFrom(java.io.InputStream arg0) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.security.proto.SecurityProtos.TokenProto> getParserForType();
    <K, V> void serializeMapTo(CodedOutputStreamInterface arg0, java.util.Map<K, V> arg1, MapEntryInterface<K, V> arg2, int arg3) throws java.io.IOException;
    TokenProtoInterface parseFrom(ByteStringInterface arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    int hashLong(long arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.FloatList arg0);
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsRaw();
    int hashBoolean(boolean arg0);
    BuilderInterface newBuilder();
    void writeDelimitedTo(java.io.OutputStream arg0) throws java.io.IOException;
    void makeExtensionsImmutable();
    TokenProtoInterface parseFrom(ByteStringInterface arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    BuilderInterface newBuilder(TokenProtoInterface arg0);
    org.apache.hadoop.thirdparty.protobuf.MessageLite getDefaultInstanceForType();
    java.lang.Object invokeOrDie(java.lang.reflect.Method arg0, java.lang.Object arg1, java.lang.Object... arg2);
    TokenProtoInterface parseFrom(java.nio.ByteBuffer arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    DescriptorInterface getDescriptorForType();
    void writeStringNoTag(CodedOutputStreamInterface arg0, java.lang.Object arg1) throws java.io.IOException;
    FieldDescriptorInterface getOneofFieldDescriptor(OneofDescriptorInterface arg0);
    boolean compareMapField(java.lang.Object arg0, java.lang.Object arg1);
    int hashFields(int arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    FieldAccessorTableInterface internalGetFieldAccessorTable();
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsMutable(boolean arg0);
    void writeTo(CodedOutputStreamInterface arg0) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder toBuilder();
    ByteStringInterface toByteString(java.lang.Object arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList emptyDoubleList();
//    BuilderInterface newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
//    TokenProtoInterface getDefaultInstanceForType();
    TokenProtoInterface parseFrom(CodedInputStreamInterface arg0) throws java.io.IOException;
    java.lang.String getService();
    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType();
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.MessageLite> getParserForType();
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3> getParserForType();
    <MessageType, T> ExtensionInterface<MessageType, T> checkNotLite(ExtensionLiteInterface<MessageType, T> arg0);
    java.lang.String getKind();
    boolean parseUnknownFieldProto3(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.AbstractMessage.BuilderParent arg0);
    void enableAlwaysUseFieldBuildersForTesting();
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.security.proto.SecurityProtos.TokenProto> parser();
//    org.apache.hadoop.thirdparty.protobuf.Message getDefaultInstanceForType();
    int computeStringSize(int arg0, java.lang.Object arg1);
    java.lang.String getInitializationErrorString();
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList newFloatList();
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList newDoubleList();
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList newLongList();
    ByteStringInterface getKindBytes();
    boolean compareFields(java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    boolean hasField(FieldDescriptorInterface arg0);
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.List<? super T> arg1);
    UnknownFieldSetInterface getUnknownFields();
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList arg0);
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.Message> getParserForType();
    boolean parseUnknownField(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    boolean compareBytes(java.lang.Object arg0, java.lang.Object arg1);
//    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder newBuilderForType();
    ByteStringInterface getServiceBytes();
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList emptyFloatList();
    java.lang.Object getRepeatedField(FieldDescriptorInterface arg0, int arg1);
    boolean hasIdentifier();
//    BuilderInterface toBuilder();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.IntList arg0);
    UninitializedMessageExceptionInterface newUninitializedMessageException();
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList emptyBooleanList();
    int getMemoizedSerializedSize();
    boolean canUseUnsafe();
    java.lang.reflect.Method getMethodOrDie(java.lang.Class arg0, java.lang.String arg1, java.lang.Class... arg2);
    int hashEnum(org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite arg0);
    ByteStringInterface toByteString();
    ByteStringInterface getIdentifier();
    boolean equals(java.lang.Object arg0);
    int getSerializedSize();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder toBuilder();
    java.lang.String toString();
    int hashCode();
    TokenProtoInterface parseFrom(CodedInputStreamInterface arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    boolean isInitialized();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    boolean hasService();
    byte[] toByteArray();
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.LongList arg0);
    TokenProtoInterface parseDelimitedFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList emptyLongList();
    boolean hasOneof(OneofDescriptorInterface arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList newBooleanList();
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.Collection<? super T> arg1);
    <V> void serializeBooleanMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList arg0);
    java.lang.Object getField(FieldDescriptorInterface arg0);
    TokenProtoInterface parseFrom(byte[] arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    <V> void maybeSerializeBooleanEntryTo(CodedOutputStreamInterface arg0, java.util.Map<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3, boolean arg4) throws java.io.IOException;
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    boolean hasKind();
    void checkByteStringIsUtf8(ByteStringInterface arg0) throws java.lang.IllegalArgumentException;
    DescriptorInterface getDescriptor();
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    int computeStringSizeNoTag(java.lang.Object arg0);
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFields();
    TokenProtoInterface parseDelimitedFrom(java.io.InputStream arg0) throws java.io.IOException;
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1) throws java.io.IOException;
    <V> void serializeLongMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Long, V> arg1, MapEntryInterface<java.lang.Long, V> arg2, int arg3) throws java.io.IOException;
    TokenProtoInterface parseFrom(byte[] arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList emptyIntList();
    TokenProtoInterface parseFrom(java.nio.ByteBuffer arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    ByteStringInterface getPassword();
    void writeString(CodedOutputStreamInterface arg0, int arg1, java.lang.Object arg2) throws java.io.IOException;
    TokenProtoInterface parseFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
    TokenProtoInterface getDefaultInstance();
    <V> void serializeStringMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.String, V> arg1, MapEntryInterface<java.lang.String, V> arg2, int arg3) throws java.io.IOException;
    java.lang.String getSerializingExceptionMessage(java.lang.String arg0);
    int getRepeatedFieldCount(FieldDescriptorInterface arg0);
    java.util.List<java.lang.String> findInitializationErrors();
    void setMemoizedSerializedSize(int arg0);
    int hashMapField(java.lang.Object arg0);
    MapFieldInterface internalGetMapField(int arg0);
    <V> void serializeIntegerMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Integer, V> arg1, MapEntryInterface<java.lang.Integer, V> arg2, int arg3) throws java.io.IOException;
    java.lang.Object getFieldRaw(FieldDescriptorInterface arg0);
    int hashEnumList(java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite> arg0);
//    BuilderInterface newBuilderForType();
    java.lang.Object writeReplace() throws java.io.ObjectStreamException;
}