package org.apache.hadoop.hdfs.remoteProxies;

public interface UninterpretedOptionInterface {
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsRaw();
    boolean parseUnknownFieldProto3(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    ByteStringInterface toByteString();
    BuilderInterface toBuilder();
    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType();
    java.lang.reflect.Method getMethodOrDie(java.lang.Class arg0, java.lang.String arg1, java.lang.Class... arg2);
    void enableAlwaysUseFieldBuildersForTesting();
    boolean hasPositiveIntValue();
    void setMemoizedSerializedSize(int arg0);
    long getPositiveIntValue();
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList arg0);
    UninterpretedOptionInterface parseFrom(java.nio.ByteBuffer arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
//    BuilderInterface newBuilderForType();
    <V> void maybeSerializeBooleanEntryTo(CodedOutputStreamInterface arg0, java.util.Map<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3, boolean arg4) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.LongList arg0);
    boolean canUseUnsafe();
    java.util.List<java.lang.String> findInitializationErrors();
    NamePartInterface getName(int arg0);
    boolean equals(java.lang.Object arg0);
    java.lang.Object getRepeatedField(FieldDescriptorInterface arg0, int arg1);
    void writeDelimitedTo(java.io.OutputStream arg0) throws java.io.IOException;
    java.util.Map convertMapEntryListToMap(java.util.List arg0);
    java.lang.String getAggregateValue();
    java.lang.Object getField(FieldDescriptorInterface arg0);
    DescriptorInterface getDescriptor();
    boolean compareMapField(java.lang.Object arg0, java.lang.Object arg1);
    boolean compareBytes(java.lang.Object arg0, java.lang.Object arg1);
    void writeTo(java.io.OutputStream arg0) throws java.io.IOException;
    MapFieldInterface internalGetMapField(int arg0);
    boolean compareFields(java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    UninterpretedOptionInterface parseFrom(java.io.InputStream arg0) throws java.io.IOException;
    int hashEnumList(java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite> arg0);
    boolean hasAggregateValue();
    long getNegativeIntValue();
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.AbstractMessage.BuilderParent arg0);
    UninterpretedOptionInterface parseDelimitedFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    BuilderInterface newBuilder(UninterpretedOptionInterface arg0);
    UninterpretedOptionInterface parseFrom(CodedInputStreamInterface arg0) throws java.io.IOException;
//    BuilderInterface newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    <V> void serializeBooleanMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Boolean, V> arg1, MapEntryInterface<java.lang.Boolean, V> arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList newLongList();
    UnknownFieldSetInterface getUnknownFields();
    byte[] toByteArray();
    UninterpretedOptionInterface getDefaultInstanceForType();
//    org.apache.hadoop.thirdparty.protobuf.Message getDefaultInstanceForType();
    <V> void serializeStringMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.String, V> arg1, MapEntryInterface<java.lang.String, V> arg2, int arg3) throws java.io.IOException;
    int hashLong(long arg0);
    java.lang.String getIdentifierValue();
    java.lang.String getInitializationErrorString();
    int getRepeatedFieldCount(FieldDescriptorInterface arg0);
    boolean hasNegativeIntValue();
    <MessageType, T> ExtensionInterface<MessageType, T> checkNotLite(ExtensionLiteInterface<MessageType, T> arg0);
    FieldDescriptorInterface getOneofFieldDescriptor(OneofDescriptorInterface arg0);
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList newFloatList();
    boolean hasField(FieldDescriptorInterface arg0);
    int computeStringSize(int arg0, java.lang.Object arg1);
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFieldsMutable(boolean arg0);
    java.lang.Object getFieldRaw(FieldDescriptorInterface arg0);
    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.MessageLite> getParserForType();
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList emptyFloatList();
    ByteStringInterface getStringValue();
    int getSerializedSize();
    org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOption.NamePartOrBuilder getNameOrBuilder(int arg0);
    UninterpretedOptionInterface parseFrom(byte[] arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    <V> void serializeLongMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Long, V> arg1, MapEntryInterface<java.lang.Long, V> arg2, int arg3) throws java.io.IOException;
    UninterpretedOptionInterface parseFrom(java.nio.ByteBuffer arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList emptyBooleanList();
    boolean hasStringValue();
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList emptyIntList();
    UninterpretedOptionInterface getDefaultInstance();
    UninterpretedOptionInterface parseDelimitedFrom(java.io.InputStream arg0) throws java.io.IOException;
    java.util.List<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOption.NamePart> getNameList();
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList newDoubleList();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    ByteStringInterface toByteString(java.lang.Object arg0);
    UninitializedMessageExceptionInterface newUninitializedMessageException();
    ByteStringInterface getIdentifierValueBytes();
    UninterpretedOptionInterface parseFrom(ByteStringInterface arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.List<? super T> arg1);
    UninterpretedOptionInterface parseFrom(java.io.InputStream arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    <M> M parseDelimitedWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, java.io.InputStream arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    <K, V> void serializeMapTo(CodedOutputStreamInterface arg0, java.util.Map<K, V> arg1, MapEntryInterface<K, V> arg2, int arg3) throws java.io.IOException;
    java.util.List<? extends org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOption.NamePartOrBuilder> getNameOrBuilderList();
    UninterpretedOptionInterface parseFrom(ByteStringInterface arg0) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList newIntList();
    int hashMapField(java.lang.Object arg0);
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder toBuilder();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList newBooleanList();
    boolean hasIdentifierValue();
    int getMemoizedSerializedSize();
//    org.apache.hadoop.thirdparty.protobuf.MessageLite getDefaultInstanceForType();
    int hashCode();
    int hashBoolean(boolean arg0);
    <V> void serializeIntegerMapTo(CodedOutputStreamInterface arg0, MapFieldInterface<java.lang.Integer, V> arg1, MapEntryInterface<java.lang.Integer, V> arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.LongList emptyLongList();
    org.apache.hadoop.thirdparty.protobuf.Internal.FloatList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.FloatList arg0);
    java.lang.Object invokeOrDie(java.lang.reflect.Method arg0, java.lang.Object arg1, java.lang.Object... arg2);
    boolean parseUnknownField(CodedInputStreamInterface arg0, BuilderInterface arg1, ExtensionRegistryLiteInterface arg2, int arg3) throws java.io.IOException;
    org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.BooleanList arg0);
    int computeStringSizeNoTag(java.lang.Object arg0);
    java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> getAllFields();
    double getDoubleValue();
    <M> M parseWithIOException(org.apache.hadoop.thirdparty.protobuf.Parser<M> arg0, CodedInputStreamInterface arg1, ExtensionRegistryLiteInterface arg2) throws java.io.IOException;
    int getNameCount();
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.Message> getParserForType();
    org.apache.hadoop.thirdparty.protobuf.Internal.DoubleList emptyDoubleList();
    void checkByteStringIsUtf8(ByteStringInterface arg0) throws java.lang.IllegalArgumentException;
    int hashEnum(org.apache.hadoop.thirdparty.protobuf.Internal.EnumLite arg0);
    void writeString(CodedOutputStreamInterface arg0, int arg1, java.lang.Object arg2) throws java.io.IOException;
    java.lang.String getSerializingExceptionMessage(java.lang.String arg0);
    ByteStringInterface getAggregateValueBytes();
    DescriptorInterface getDescriptorForType();
    <T> void addAll(java.lang.Iterable<T> arg0, java.util.Collection<? super T> arg1);
    UninterpretedOptionInterface parseFrom(byte[] arg0, ExtensionRegistryLiteInterface arg1) throws org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException;
//    org.apache.hadoop.thirdparty.protobuf.Message.Builder newBuilderForType(org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3.BuilderParent arg0);
    java.lang.String toString();
//    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder newBuilderForType();
    boolean hasOneof(OneofDescriptorInterface arg0);
    int hashFields(int arg0, java.util.Map<org.apache.hadoop.thirdparty.protobuf.Descriptors.FieldDescriptor, java.lang.Object> arg1);
    java.lang.Object writeReplace() throws java.io.ObjectStreamException;
    boolean isInitialized();
    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOption> parser();
//    org.apache.hadoop.thirdparty.protobuf.Parser<org.apache.hadoop.thirdparty.protobuf.DescriptorProtos.UninterpretedOption> getParserForType();
    void writeStringNoTag(CodedOutputStreamInterface arg0, java.lang.Object arg1) throws java.io.IOException;
    boolean hasDoubleValue();
    FieldAccessorTableInterface internalGetFieldAccessorTable();
//    org.apache.hadoop.thirdparty.protobuf.MessageLite.Builder toBuilder();
    org.apache.hadoop.thirdparty.protobuf.Internal.IntList mutableCopy(org.apache.hadoop.thirdparty.protobuf.Internal.IntList arg0);
    void writeTo(CodedOutputStreamInterface arg0) throws java.io.IOException;
    BuilderInterface newBuilder();
    UninterpretedOptionInterface parseFrom(CodedInputStreamInterface arg0, ExtensionRegistryLiteInterface arg1) throws java.io.IOException;
    void makeExtensionsImmutable();
//    org.apache.hadoop.thirdparty.protobuf.Parser<? extends org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3> getParserForType();
}