package org.apache.hadoop.hdfs.remoteProxies;

public interface WithNameInterface {
    INodeFileInterface asFile();
    PermissionStatusInterface getPermissionStatus();
    boolean isDirectory();
    INodeInterface getReferredINode();
    short getFsPermissionShort();
    AclFeatureInterface getAclFeature(int arg0);
    long getPermissionLong();
    void setUser(java.lang.String arg0);
    void setAccessTime(long arg0);
    void setPermission(FsPermissionInterface arg0);
    INodeInterface removeAclFeature(int arg0);
    long getAccessTime();
    FsPermissionInterface getFsPermission();
    boolean shouldRecordInSrcSnapshot(int arg0);
    java.lang.String getFullPathName();
    boolean isFile();
    int hashCode();
    INodeInterface setAccessTime(long arg0, int arg1, boolean arg2);
    void setGroup(java.lang.String arg0);
    boolean isValidAbsolutePath(java.lang.String arg0);
    java.lang.String getParentString();
    byte getStoragePolicyID();
    java.lang.String getGroupName();
    FsPermissionInterface getFsPermission(int arg0);
    QuotaCountsInterface computeQuotaUsage(BlockStoragePolicySuiteInterface arg0, boolean arg1);
    long getModificationTime(int arg0);
    QuotaCountsInterface getQuotaCounts();
    INodeDirectoryInterface getParent();
    int tryRemoveReference(INodeInterface arg0);
    int getDstSnapshotId();
    boolean isReference();
    void setParent(INodeDirectoryInterface arg0);
    byte getStoragePolicyIDForQuota(byte arg0);
    INodeInterface setUser(java.lang.String arg0, int arg1);
    ContentSummaryInterface computeAndConvertContentSummary(int arg0, ContentSummaryComputationContextInterface arg1) throws org.apache.hadoop.security.AccessControlException;
    int removeReference(INodeReferenceInterface arg0);
    QuotaCountsInterface computeQuotaUsage(BlockStoragePolicySuiteInterface arg0, byte arg1, boolean arg2, int arg3);
    boolean isSetStoragePolicy();
    byte[] getKey();
    boolean isSymlink();
    INodeInterface addXAttrFeature(XAttrFeatureInterface arg0, int arg1);
    AclFeatureInterface getAclFeature();
//    K getKey();
    void cleanSubtree(ReclaimContextInterface arg0, int arg1, int arg2);
    boolean isRoot();
    void addAclFeature(AclFeatureInterface arg0);
    int getPriorSnapshot(INodeReferenceInterface arg0);
    boolean isLastReference();
    INodeSymlinkInterface asSymlink();
    boolean isAncestorDirectory(INodeDirectoryInterface arg0);
    INodeInterface removeXAttrFeature(int arg0);
    boolean equals(java.lang.Object arg0);
    int getLastSnapshotId();
    ContentSummaryInterface computeContentSummary(BlockStoragePolicySuiteInterface arg0) throws org.apache.hadoop.security.AccessControlException;
    INodeReferenceInterface asReference();
    void setLocalName(byte[] arg0);
    int getSelfSnapshot();
    XAttrFeatureInterface getXAttrFeature();
    long getId();
    byte[][] getPathComponents(java.lang.String arg0);
    void destroyAndCollectBlocks(ReclaimContextInterface arg0);
    java.lang.String[] getPathNames(java.lang.String arg0);
    void clear();
    INodeInterface setGroup(java.lang.String arg0, int arg1);
    ContentSummaryComputationContextInterface computeContentSummary(int arg0, ContentSummaryComputationContextInterface arg1) throws org.apache.hadoop.security.AccessControlException;
    long getModificationTime();
    java.lang.String getUserName();
    byte[] getLocalNameBytes();
    java.lang.StringBuffer dumpTreeRecursively();
    void dumpTreeRecursively(java.io.PrintWriter arg0, java.lang.StringBuilder arg1, int arg2);
    java.lang.String getObjectString();
    java.lang.String getUserName(int arg0);
    void removeXAttrFeature();
    java.lang.String getLocalName();
    INodeDirectoryInterface asDirectory();
    boolean isInLatestSnapshot(int arg0);
    QuotaCountsInterface computeQuotaUsage(BlockStoragePolicySuiteInterface arg0);
    long getAccessTime(int arg0);
    byte[][] getPathComponents();
    void dumpTreeRecursively(java.io.PrintStream arg0);
    XAttrFeatureInterface getXAttrFeature(int arg0);
    org.apache.hadoop.hdfs.server.namenode.INodeAttributes getSnapshotINode(int arg0);
    boolean isQuotaSet();
    INodeInterface addAclFeature(AclFeatureInterface arg0, int arg1);
    INodeReferenceInterface getParentReference();
    INodeInterface setPermission(FsPermissionInterface arg0, int arg1);
    void checkAbsolutePath(java.lang.String arg0);
    java.lang.String getGroupName(int arg0);
    java.lang.String toDetailString();
    INodeInterface setModificationTime(long arg0, int arg1);
    void addXAttrFeature(XAttrFeatureInterface arg0);
    void setParentReference(INodeReferenceInterface arg0);
    void setModificationTime(long arg0);
    byte getLocalStoragePolicyID();
    void removeAclFeature();
    int compareTo(byte[] arg0);
    boolean isDeleted();
    boolean isInCurrentState();
    PermissionStatusInterface getPermissionStatus(int arg0);
    void recordModification(int arg0);
    INodeInterface updateModificationTime(long arg0, int arg1);
    void addSpaceConsumed(QuotaCountsInterface arg0);
    java.lang.String toString();
}