package org.apache.hadoop.hdfs.remoteProxies;

public interface WithCountInterface {
    java.lang.String getGroupName(int arg0);
    FsPermissionInterface getFsPermission(int arg0);
    boolean isValidAbsolutePath(java.lang.String arg0);
    long getPermissionLong();
    java.lang.String getParentString();
    void cleanSubtree(ReclaimContextInterface arg0, int arg1, int arg2);
    void setParentReference(INodeReferenceInterface arg0);
    XAttrFeatureInterface getXAttrFeature(int arg0);
    boolean isRoot();
    WithNameInterface getPriorWithName(WithNameInterface arg0);
    long getModificationTime();
    INodeSymlinkInterface asSymlink();
    boolean isInLatestSnapshot(int arg0);
    void addAclFeature(AclFeatureInterface arg0);
    boolean isFile();
    int compareTo(byte[] arg0);
    java.lang.StringBuffer dumpTreeRecursively();
    INodeReferenceInterface getParentReference();
    long getAccessTime(int arg0);
    ContentSummaryComputationContextInterface computeContentSummary(int arg0, ContentSummaryComputationContextInterface arg1) throws org.apache.hadoop.security.AccessControlException;
    boolean isInCurrentState();
    java.lang.String getLocalName();
    byte getLocalStoragePolicyID();
    java.lang.String[] getPathNames(java.lang.String arg0);
    java.lang.String toString();
    INodeInterface setPermission(FsPermissionInterface arg0, int arg1);
    QuotaCountsInterface computeQuotaUsage(BlockStoragePolicySuiteInterface arg0, byte arg1, boolean arg2, int arg3);
    boolean isSymlink();
    INodeInterface getReferredINode();
    int tryRemoveReference(INodeInterface arg0);
    QuotaCountsInterface computeQuotaUsage(BlockStoragePolicySuiteInterface arg0);
    byte[][] getPathComponents();
    long getModificationTime(int arg0);
    int getReferenceCount();
    AclFeatureInterface getAclFeature(int arg0);
    byte getStoragePolicyIDForQuota(byte arg0);
    FsPermissionInterface getFsPermission();
    INodeReferenceInterface asReference();
    int getPriorSnapshot(INodeReferenceInterface arg0);
    AclFeatureInterface getAclFeature();
    XAttrFeatureInterface getXAttrFeature();
    INodeDirectoryInterface getParent();
    void dumpTreeRecursively(java.io.PrintWriter arg0, java.lang.StringBuilder arg1, int arg2);
    INodeInterface updateModificationTime(long arg0, int arg1);
    INodeInterface setAccessTime(long arg0, int arg1, boolean arg2);
    void addReference(INodeReferenceInterface arg0);
    void setPermission(FsPermissionInterface arg0);
//    K getKey();
    void removeReference(INodeReferenceInterface arg0);
    boolean isQuotaSet();
    boolean equals(java.lang.Object arg0);
    PermissionStatusInterface getPermissionStatus(int arg0);
    ContentSummaryInterface computeAndConvertContentSummary(int arg0, ContentSummaryComputationContextInterface arg1) throws org.apache.hadoop.security.AccessControlException;
    INodeInterface addAclFeature(AclFeatureInterface arg0, int arg1);
    java.lang.String getGroupName();
    short getFsPermissionShort();
    INodeInterface removeXAttrFeature(int arg0);
    void removeXAttrFeature();
    long getAccessTime();
    boolean isReference();
    int getDstSnapshotId();
    java.lang.String getFullPathName();
    INodeReferenceInterface getParentRef(int arg0);
    java.lang.String getObjectString();
    void setLocalName(byte[] arg0);
    void destroyAndCollectBlocks(ReclaimContextInterface arg0);
    ContentSummaryInterface computeContentSummary(BlockStoragePolicySuiteInterface arg0) throws org.apache.hadoop.security.AccessControlException;
    INodeInterface addXAttrFeature(XAttrFeatureInterface arg0, int arg1);
    WithNameInterface getLastWithName();
    INodeDirectoryInterface asDirectory();
    boolean shouldRecordInSrcSnapshot(int arg0);
    java.lang.String getUserName();
    void setAccessTime(long arg0);
    byte getStoragePolicyID();
    java.lang.String getUserName(int arg0);
    INodeFileInterface asFile();
//    int removeReference(INodeReferenceInterface arg0);
    INodeInterface setUser(java.lang.String arg0, int arg1);
    java.lang.String toDetailString();
    INodeInterface setGroup(java.lang.String arg0, int arg1);
    void removeAclFeature();
    QuotaCountsInterface getQuotaCounts();
    INodeInterface removeAclFeature(int arg0);
    void recordModification(int arg0);
    boolean isDeleted();
    boolean isDirectory();
    void checkAbsolutePath(java.lang.String arg0);
    boolean isLastReference();
    void setParent(INodeDirectoryInterface arg0);
    void setGroup(java.lang.String arg0);
    byte[] getLocalNameBytes();
    void clear();
    void setModificationTime(long arg0);
    PermissionStatusInterface getPermissionStatus();
    int hashCode();
    void addSpaceConsumed(QuotaCountsInterface arg0);
    INodeInterface setModificationTime(long arg0, int arg1);
    byte[] getKey();
    byte[][] getPathComponents(java.lang.String arg0);
    boolean isSetStoragePolicy();
    boolean isAncestorDirectory(INodeDirectoryInterface arg0);
    QuotaCountsInterface computeQuotaUsage(BlockStoragePolicySuiteInterface arg0, boolean arg1);
    void addXAttrFeature(XAttrFeatureInterface arg0);
    org.apache.hadoop.hdfs.server.namenode.INodeAttributes getSnapshotINode(int arg0);
    void dumpTreeRecursively(java.io.PrintStream arg0);
    long getId();
    void setUser(java.lang.String arg0);
}